### ISSUE TITLE
getMap Key error in Remote Mode

### ISSUE THREAD

**Issue by Kai-FengChen** [sdss/marvin#100]
I'm encountering a problem when using the getMap function when the fits file is called remotely.
When I have the file locally, everything works fine.
`mapfile = './manga-8083-12704-MAPS-SPX-GAU-MILESHC.fits.gz'`
`maps = Maps(filename=mapfile)`
`maps.getMap('spx_ellcoo', channel='elliptical_radius')`
`<Marvin Map (plateifu='8083-12704', property='spx_ellcoo', channel='elliptical_radius')>`
But when I called the file remotely,
`maps = Maps(plateifu="8083-12704", mode="remote")`
`maps.getMap('spx_ellcoo', channel='elliptical_radius')`
I got Key Error:
/Users/Kevin/.pyenv/versions/HPSC/lib/python2.7/site-packages/marvin/tools/map.pyc in __init__(self, maps, property_name, channel)
     94             self._load_map_from_db()
     95         elif maps.data_origin == 'api':
---> 96             self._load_map_from_api()
     97 
     98     def __repr__(self):
/Users/Kevin/.pyenv/versions/HPSC/lib/python2.7/site-packages/marvin/tools/map.pyc in _load_map_from_api(self)
    201 
    202         self.value = numpy.array(data['value'])
--> 203         self.ivar = numpy.array(data['ivar'])
    204         self.mask = numpy.array(data['mask'])
    205         self.unit = data['unit']

KeyError: 'ivar'

**Comment by albireox** [comment]
Fixed as of d01bec1d32548ff7a27812e44782e547aeb23e87. See #103.
