### ISSUE TITLE
Marvin Bin units are incorrect

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#109]
Currently the units associated to a Marvin Bin are incorrect or, at least, confusing (thanks to Kyle for pointing it). The DAP measurements for binned Maps are still in per spaxel units, and those get propagated to Marvin Bin. I think we have two choices here:

- Modify the value and unit of the properties in Marvin Bin. The value would be the addition of each one of the constituting spaxels in the bin, and the units would loose the `/spaxel`.

- Keep the values and units as they are and document this clearly. The user would need to use the number of spaxels for a given bin (easily accessible in Marvin Bin) to get the total value, but things would be more consistent with the results from the DAP.

Thoughts?

**Comment by havok2063** [comment]
My vote would be for choice 1, since we are making Marvin Bin be a real class / tool that is usable beyond just a grouping.  So I think we should properly convert the units.  (And document it of course).  Choice 2 is more transparent but requires more work by the user.  Your last point brings up an interesting issue.  How much should we keep in line with the DAP even if it doesn't make much sense?  As the DAP workflow occurs first, it will always in some sense define things, but should Marvin be beholden to that?  If we want Marvin to service the end user, then I think we are free to "improve" things beyond the DAP. 

Right now people think of the DAP products as the final MaNGA layer people deal with.  Do we want to get people moving to the idea that Marvin is the final MaNGA layer that people should be interacting with?  We should bring Kyle in on this thread once he's a team member, and this should be added to a higher level discussion topic somewhere somewhen.

**Comment by bretthandrews** [comment]
Marvin should make interacting with MaNGA data as easy as possible, which in this case would be the first option. I think that the target audience should be people that are not intimately familiar with the DAP data model, so we should go with whatever would be most intuitive.

**Comment by albireox** [comment]
I've started to look into this again (hey, it's only been 1.5 years) and, well, I'm panicking a bit. I'd like to discuss this next Monday and would be good to get @kbwestfall input on this.

Basically, our current implementation for `Bin` is ok (with some caveats) for VOR10 and other, old, binning types, but somewhere between useless and incorrect for HYB10.

The main problem is that for HYB10 you cannot encapsulate the value of the bin in a single value for emission line properties (the values of those change from spaxel to spaxel within the same bin). In general, and this not only affects HYB10, there are properties that cannot be averaged into a single value. For instance, the values `SPX_SKYCOO` in a binned MAPS are still different for different spaxel within the same bin, as they should. If you want to average it you'd need to do something more intelligent than taking a single value (either average, take the centre of mass, etc, all this that are not really obvious to the user). Furthermore, even for bintypes and properties that can be reduced to a single value, the type of the property determines what that value should be. For stellar velocity the value of the bin is the same as for each one of the pixels in the bin, for emission lines I think it would be the sum, for others such as EW or spectral indices I'm not even sure what we'd need to do.

I'm fairly convinced we cannot release DR15 with this issue. So, this brings us to Yet Another Refactor of Bin™, 2018 Edition. A few possible solutions/implementations, open for discussion:

1. We can keep the concept of a `Bin` having a single value per property (same as `Spaxel`) and calculate that value more intelligently. It would mean that somewhere in the datamodel we need to add information about how to compress that property+channel to a single value (which may not be trivial at all for LOGCUBE). For instance, emission lines would be `sum()`, `stellar_vel` would be `None`, etc. We'd need to be very careful about this and document it well. The advantage is that the implementation of `Bin` probably would need to change a huge lot.
2. We replace properties with list of values, one for each spaxel in the bin. The advantage is that we don't need to do anything, just use the DAP output. The users still need to know how to deal with different properties, but that's up to them and the units would be correct (I think). It requires a medium-sized change to `Bin` (not sure how large until I get into doing it).
3. Same as 2. but instead of a list of values each property is a masked 2D array the size of the original map in which only the values for that property and bin are unmasked. It has the advantage of maintaining the original map shape (which is sometimes useful) but it may be less useful for other situations. Probably same level of implementation difficulty as 2.
4. We give up, accept the inevitability of death and the fact that the Universe is just a despairing container of ever-growing entropy, and open a coffee shop.

In principle I'm quite opposed to 1., ambivalent between 2 and 3, and totally onboard with 4.
