### ISSUE TITLE
Shift Spectrum to Rest Frame in Marvin-web Display

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#112]
As FuHeng (Eric) Liang suggested, the spectral plot in Marvin-web would be more useful if it was in rest frame.

**Comment by kbwestfall** [comment]
Maybe a stupid suggestion, but could we have the rest wavelength be labeled on the top axis so that people could see both the observed and rest wavelength?  Would we de-redshift based on the NSA redshift, the stellar velocity, or the gas velocity?  To keep it simple, I imagine we want to use the bulk redshift from the NSA.

**Comment by bretthandrews** [comment]
Dual wavelength axes is a good suggestion. We'll have to look into Dygraphs to see if it has that functionality (it's not that feature-heavy, so I wouldn't be surprised if it cannot).

As for the redshift to use...I think that the gas or stellar velocity would be more helpful in high S/N regimes but could lead to catastrophic errors in low S/N spaxels.

**Comment by havok2063** [comment]
Yeah I agree, dual axes is a better suggestion than replacement or making it toggleable. I had a quick look and it seems Dygraphs does not allow for multiple x axes.  y axes yes.   The closest out-of-the-box thing looks like plotting it as an independent series.

**Comment by kbwestfall** [comment]
If it's easier to toggle, that might be the best solution.

**Comment by havok2063** [comment]
it wouldn't be trivial to implement.

**Comment by havok2063** [comment]
Just to expand a bit on the work needed to make it toggleable.  We would need to write javascript and html to 
1. Store the wavelength array on the client side
2. Add a toggle button / checkbox to the interface 
3. Store or compute the rest wavelength on the client side
4. Re-render the Dygraphs plot fresh from upon button click.

Most of the work is in steps 2 and 4.

**Comment by kbwestfall** [comment]
Yeah, doesn't sound trivial.  I personally would put this at low priority.  It's basically a "polishing" issue, I think.

**Comment by havok2063** [comment]
I would agree.  I would put this in the category of user freedoms or preferences, similar to maps range rescaling.

**Comment by kbwestfall** [comment]
The rescaling of the maps is arguably more important.  I think many more people will play with the maps than will actually look at individual spectra.

**Comment by havok2063** [comment]
I agree but I think, right now, adding user flexibility on the web interface is a low priority in general, given everything else.  I do think moving the DAP custom color scale and custom ranges for defined map-types from the client side into the Marvin data-model, and pushing those custom values to the web, is a priority however.

**Comment by albireox** [comment]
Just a comment that this was discussed again today in the DevCon and we agreed to look into it. I'm moving it to backlog.

**Comment by havok2063** [comment]
This has been implemented and merged in 2.3.5 for MPL-9
