### ISSUE TITLE
NSA hybrid colours are egregiously wrong

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#117]
As referenced in #108, the colours we calculate as hybrid properties/method in the NSA ModelClasses (e.g., `petroth50_el_r_g`) are calculated assuming that `petroth50_el` are magnitudes, when they are half-light radii.

We need to fix this by using `petroflux_el` and calculating the asinh magnitudes (I think those are the ones we want) for each band. Probably we want to create two types of hybrid properties (and corresponding hybrid methods):

- `petromag_el_X` containing the asinh magnitudes from `petroflux_el`.
- `petromag_el_X_Y` containing the colours (which, at this point would just be the difference of two `petromag_el_X`)

**Comment by havok2063** [comment]
Yeah, I think that's what we want as well.

**Comment by albireox** [comment]
Ok. I'll work on that today and add some tests. In the meantime I have added it to the known issues and updated the documentation at Utah.

**Comment by havok2063** [comment]
ok sounds good.
