### ISSUE TITLE
maskbits should be (more easily) queryable

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#118]
I think right now it is either not possible, or very complicated and ambiguous to query on maskbits.  This should be made a bit easier, or at the very least, an example using the complicated fits_header method written up.   This issue appeared in a recent Sentry entry.  https://sentry.io/manga/marvin2/issues/190347591/

Someone tried to join `mangadatadb.Cube` and `mangaauxdb.MaskBit`.

```
brain/db/modelGraph.py in _getShortestPath at line 288
NetworkXNoPath
it is not possible to join tables mangadatadb.cube and mangaauxdb.maskbit. Please, review your query.
```

**Comment by joelbrownstein** [comment]
Did you check out the saw for its very simple modal (macro) for querying on bitmasks which makes the sqlalchemy query trivial?

On Dec 5, 2016, at 2:09 PM, Brian Cherinka <notifications@github.com<mailto:notifications@github.com>> wrote:


I think right now it is either not possible, or very complicated and ambiguous to query on maskbits. This should be made a bit easier, or at the very least, an example using the complicated fits_header method written up. This issue appeared in a recent Sentry entry. https://sentry.io/manga/marvin2/issues/190347591/

Someone tried to join mangadatadb.Cube and mangaauxdb.MaskBit.

brain/db/modelGraph.py in _getShortestPath at line 288
NetworkXNoPath
it is not possible to join tables mangadatadb.cube and mangaauxdb.maskbit. Please, review your query.

**Comment by havok2063** [comment]
No I haven't.  Can you point me to the relevant bits of code? And provide an example of usage?

**Comment by joelbrownstein** [comment]
Hi Brian,

If you go to either the
optical spectrum search: https://dr13.sdss.org/optical/spectrum/search?tab=bitmasks
or
infrared spectrum search: https://dr13.sdss.org/infrared/spectrum/search?tab=bitmasks
you will see the various bitmasks, each with a corresponding modal to facilate your selection

Here is one of the tutorial examples: Permalink for this search<https://dr13.sdss.org/optical/spectrum/search?id=52>
which uses EBOSS_TARGET1 to
refine the search to the LRG program
and also with ZWARNING=0 and SPECPRIMARY=BOSS_PRIMARY
so this example actually demos 3 of the bitmask modals (highlighted in btn-info) being set.

The code is in 3 places (macro, jquery, python), for e.g. grep for bitmask in:
https://trac.sdss.org/browser/repo/sdss/webapps/saw/trunk/python/saw/templates/optical/macros.html
https://trac.sdss.org/browser/repo/sdss/webapps/saw/trunk/python/saw/static/jquery/optical/spectrum_search.js
https://trac.sdss.org/browser/repo/sdss/webapps/saw/trunk/python/saw/tools/optical.py

Cheers, Joel

On Dec 5, 2016, at 2:37 PM, Brian Cherinka <notifications@github.com<mailto:notifications@github.com>> wrote:


No I haven't. Can you point me to the relevant bits of code? And provide an example of usage?

**Comment by havok2063** [comment]
Thanks, Joel.  I'll have a look at this.  Currently, I'm primarily thinking about queries from the terminal, rather than the web.  Since we're not using forms per se, it may not be as useful, but I'll take a look at the back end code.  I like your form layout though.  If we end up adding any forms to the web to make queries easier, I'll definitely do something like this.
