### ISSUE TITLE
downloadList() error

### ISSUE THREAD

**Issue by goyarzun** [sdss/marvin#121]
I am trying to download a list of cubes using marvin.utils.general.general.downloadList(). However, I am getting an error. I assume it is because “release” is misspelled. Thanks!

**Comment by havok2063** [comment]
Fixed!

**Comment by goyarzun** [comment]
Can you confirm that this has been fixed? I keep getting the same error, so I want to make sure it is not an error on my part. Thanks!

**Comment by havok2063** [comment]
Yes it is fixed but it has not been pushed into the next release of Marvin.  That should be happening by the end of this week.
