### ISSUE TITLE
Add a banner to Marvin 1 for people to try Marvin 2?

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#125]
Should we add some kind of banner or text in Marvin 1 indicating that Marvin 2 is out of alpha and that people can go there and test it? It would mean stressing the servers even more, but maybe we would get more people using it and reporting issues.

**Comment by havok2063** [comment]
This is easier said than done I think.  It requires either modifying the current svn tag of Marvin 1, or setting up Marvin 1 at Utah to run off of the git repo.  The svn marvin repo trunk is now marvin 2 correct?, so we only have tags of this left?

**Comment by albireox** [comment]
I see. Well, you can create a new branch from a tag, make the modifications and then tag a new version from there. But if it's a lot of work we may want to wait until Marvin 2 is a bit more stable.

**Comment by albireox** [comment]
Actually, there is a branch `marvin1` set to the latest version of Marvin 1. If we modify and release a new version, I can sync it to the SVN.

**Comment by havok2063** [comment]
Since a recent sasvm machine reboot, Marvin1 is down, with no intention of coming back online.

**Comment by bretthandrews** [comment]
Could we automatically redirect users to Marvin 2? Or even reclaim sas.sdss.org/marvin as the default Marvin URL?

**Comment by joelbrownstein** [comment]
On Jan 25, 2017, at 10:58 AM, Brett Andrews <notifications@github.com<mailto:notifications@github.com>> wrote:


Could we automatically redirect users to Marvin 2?

Sure, do you want me to set that up?

Or even reclaim sas.sdss.org/marvin<http://sas.sdss.org/marvin> as the default Marvin URL?

Yes, that could also be done, but do you want to keep marvin1 available (if so what URL)?

**Comment by joelbrownstein** [comment]
It actually looks like marvin2 needs to know it is routing to marvin, so you guys need to fix that via the @route decorators or blueprints
But for now, I have https://sas.sdss.org/marvin trying to proxy to marvin2, and then marvin is rewriting the URL to https://sas.sdss.org/marvin2
Conversely, https://sas.sdss.org/marvin/search/ is successfully proxying to marvin2 with no URL rewrite.


On Jan 26, 2017, at 3:29 AM, Joel Brownstein <joelbrownstein@astro.utah.edu<mailto:joelbrownstein@astro.utah.edu>> wrote:


On Jan 25, 2017, at 10:58 AM, Brett Andrews <notifications@github.com<mailto:notifications@github.com>> wrote:


Could we automatically redirect users to Marvin 2?

Sure, do you want me to set that up?

Or even reclaim sas.sdss.org/marvin<http://sas.sdss.org/marvin> as the default Marvin URL?

Yes, that could also be done, but do you want to keep marvin1 available (if so what URL)?

**Comment by havok2063** [comment]
I think this should be good for now.  We've gotten people used to using marvin2 as the site address.  I think eventually we do want to convert all marvin2 references back to just marvin and unify everything.  We could time that for the public release of Marvin in DR15?

**Comment by albireox** [comment]
As painful a it sounds this doesn't seem to be necessary anymore since Marvin 1 has been down for a while. Closing.
