### ISSUE TITLE
improve efficiency of object creation in a query result set. 

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#131]
Converting query results into Marvin objects takes a long time.  After some cuts of 50,000 objects, I have a set of ~800 results.  Converting 500 of them to Spaxels took ~30 minutes, and pickling the Results object results in a 1.5 GB pickle file.  Also, attempt one to convert all 800 crashed as one mangaid could be not identified and nulled all prior object creation.    

Needless to say, this should be improved.

**Comment by albireox** [comment]
This is a general issue related to how `Spaxel` objects are created, and how we can improve efficiency. It will probably will require some refactoring of the `Spaxel` class, and maybe exploring the option to use `cfitsio` for FITS reading.

**Comment by havok2063** [comment]
`Spaxels` now are created using a `Cube` first.  Closing.
