### ISSUE TITLE
Make query_params doc page use the DAP datamodel

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#134]
The `query_params` documentation page is currently static and a simple list of all possible parameter. It should be possible to use the datamodel, which contains all channels and description to generate that page dynamically and with much more complete information.

**Comment by havok2063** [comment]
Since the `query_params` also include parameters outside of the DAP Maps, do we want to build a bigger data_model that this gets generated from?  And if so, how do we want to do that?
