### ISSUE TITLE
Add link to NED in Galaxy page

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#142]
Do you think it better to add a button for each gal. that links to its entry in NED (NASA/IPAC Extragalactic Database) i.e. a button to automatically send a request table in NED to search for this gal. This is for the convenience such as in finding literatures on a certain object etc.

Originally requested by FuHeng (Eric) Liang liangfh13@mails.tsinghua.edu.cn

**Comment by havok2063** [comment]
I think this is a good idea.  There is some duplication of effort here.  We provide a link to the CAS explore page for each galaxy, which already includes links to NED, Simbad, etc.  I think this is a question of 'do we go with what has been done?' or 'do we try to do it better?'

**Comment by bretthandrews** [comment]
I (and Eric) did not realize that we could get to NED, Simbad, etc. via the CAS explore page, so either we need to advertise this ability or just implement the same (or better) functionality directly into Marvin so that it is intuitive.
