### ISSUE TITLE
Limit number of querable parameters in the web

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#145]
For now, let's hardcode the 20-ish most used query parameters that are shown in the dropdown menu of the web search (and the autocomplete). The tools query should still be able to use the full set of parameters.

In the future, we'll want to include a complete list of reasonably querable, well vetted parameters, probably with aliases, but for now this should make the web search more usable.

**Comment by havok2063** [comment]
This has been finished.  There is now a config file inside python/marvin/data containing a list of query parameters to be used.  These query parameters are displayed in the web, and are accessed via the Marvin query object method get_best_params.   When we update the list, the changes should propagate downwards.  One will need to restart their browsers to have the updated autocomplete list take effect.
