### ISSUE TITLE
Marvin Tools getMap from API returns a map that is not oriented correctly

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#148]
From file:
![screen shot 2017-01-20 at 10 12 42 am](https://cloud.githubusercontent.com/assets/12723826/22154338/1e71a30c-def9-11e6-9547-a57cd19d20f1.png)

From API (in tools):
![screen shot 2017-01-20 at 10 12 59 am](https://cloud.githubusercontent.com/assets/12723826/22154349/27f2b6c8-def9-11e6-876d-434364e89d22.png)

Image:
![screen shot 2017-01-20 at 10 14 27 am](https://cloud.githubusercontent.com/assets/12723826/22154403/67011896-def9-11e6-9fd8-1b089ae0883a.png)

Web (JS):
![screen shot 2017-01-20 at 10 15 18 am](https://cloud.githubusercontent.com/assets/12723826/22154409/6e624916-def9-11e6-8610-b564465bac69.png)

**Comment by havok2063** [comment]
This could be an issue with the spaxel x, y coordinates in the DB, how the map is plotted in the tools, or how the data is returned via the API, etc.  Or an issue between Maps versus cube.maps.   

The web display of maps is pulled via a local db, using cube.getMaps.
