### ISSUE TITLE
marvin __version__ discrepancy with setup.py

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#158]
Using my email branch, made from py3-dev, when I import marvin and look at `marvin.__version__`, I get '2.0.7', even though the version specified in setup.py is '2.0.9'.  

Is this an issue with `dist = get_distribution('sdss-marvin')`?

**Comment by albireox** [comment]
Do you have a marvin version installed from pip? If so, it may be that the `__version__` code is grabbing it, even if the one with precedence in your PYTHONPATH. Also, check that you don't have any `lib/`, `dist/`, or other directory in your marvin that may cause confusion.

**Comment by havok2063** [comment]
Well a `pip list` shows I have sdss-marvin 2.0.7 installed.  However when I attempt to uninstall it I get the error `Can't uninstall 'sdss-marvin'. No files were found to uninstall.`

I did have a `dist/` directory in my marvin git directory.  I removed it but my marvin still says the version is `2.0.7`

**Comment by albireox** [comment]
If `pip list` says so I guess it thinks you have a version of marvin installed and that is confusing `get_distribution` (which is not something I wrote, so it may even work). Can you check the directory where pip install files (in my case is `/usr/local/lib/python2.7/site-packages` but it may be different with conda) and make sure there is no directory there for `marvin` or `sdss-marvin`? Also, check the corresponding directory for python 3.

**Comment by havok2063** [comment]
I've checked my site-packages directory for both python2.7 and 3.5 and there is nothing there relating to `marvin` or `sdss-marvin`.  

It seems `get_distribution` is getting confused by something in my github directory
```
In [8]: dist = get_distribution('sdss-marvin')

In [9]: dist
Out[9]: sdss-marvin 2.0.7 (/Users/Brian/Work/github_projects/Marvin/python)
```
I found a `python/sdss_marvin.egg-info` directory, from my last attempt to build a pypi distribution.  I deleted that and now when I import marvin, and check `marvin.__version__` I get `dev`.

So I think the code is doing what it's supposed to now.  Is this the version we want when working off the github source?

**Comment by havok2063** [comment]
I think having a `dev` version is good for us, but that also means that right now, if anyone else installs and runs marvin from source, their version will also be `dev`.   I think we still want to know what the latest version of that is, but maybe just a dev version.  Maybe `2.0.9dev`?

**Comment by albireox** [comment]
`dev` is what it says when it cannot find any version using `get_distribution`. Having it mention the version plus dev is not a bad idea, but I'd make it say (for the case right now) `2.1.0dev`, indicating that we are working in the `2.1.0` version.

**Comment by havok2063** [comment]
That's fine.  So just so I'm on the same page,  the VERSION as specified in the `setup.py` should always be the version of the lastest PyPi installation when we do the build.  The default version when from source will be hardcoded in `marvin.__init__.py`, when there is no distribution.  And we just make sure that one leads the other and we don't forget to manually increment the dev version?

One problem if someone installs `sdss-marvin` with pip and installs marvin from source, this code at the top will always use the version from pip, even if the source code has taken precedence. 

Once errors start flying in, we just want to make sure we have the correct version information.

**Comment by albireox** [comment]
I think I'd prefer to have to hardcode the version in only one place (half the chances of screwing it up). I'd say the workflow could be:

- We set the development version, with dev, we are working on in `setup.py` (right now it would `2.1.0dev`)
- When we are ready to release we change it to `2.0.1`. We release.
- The moment we start working on the new release we change `setup.py` to `2.1.1dev` or `2.2dev`).

This is how I see people work for other packages like atom.

I'm not sure how confused `get_distribution` will get if people have a git clone and a pip install. I assume that will be uncommon. I think as long as people don't build their own versions (like the egg you had) things should be ok.

When we get a bug from somebody, the first step should be to make sure we know what version they are running. Maybe we should write a `How to report a bug` section in the documentation with instructions on how to check things like that.

**Comment by havok2063** [comment]
That workflow sounds good to me.   We'll need to rework the version location so both setup.py and the code in `__init__.py` see it.  

In the Sentry logging, I send the `marvin.__version__` as the release version with the exception.  In addition, for the web, if an error occurs and sentry can produce an event_id for it, then a user feedback form will pop up allowing the user to comment on the error that just occurred if they want.   Sentry sends a lot of information already back with the exception.  I still need to test if this works in production mode.  This form may only work when we capture exceptions with Sentry explicitly, rather than uncaught ones. 

In any case, it's still a good idea to describe somewhere how to file bug reports and look up the version.

**Comment by albireox** [comment]
Closed that by mistake.

**Comment by havok2063** [comment]
I've updated py3-dev with changes that I think fixes this.  During `setup.py`, a `version.py` file is generated inside `python/marvin` that contains the version information as deduced from the `setup.py VERSION`.  Marvin then gets the version from this file, first attempting from `get_distribution` then from `marvin.version`, and sets it to the internal `__version__`.  Not sure if this is the easiest solution to this.
