### ISSUE TITLE
Queries and results do no respect config.mode

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#161]
From Grecco's example, it seems that queries are not using the access mode as expected. I think we need:

- If whether `config.mode='local'` or queries are called with `mode='local'` and there is no local database the query should fail (unlike now, that is automatically changing to remote mode).
- The results should record the mode in which the query was originally called (that means that if the query was done in auto mode, the results should have auto mode, even if the query was done remotely).
- When an object is created from a result, the load mode should be the same as in the result.
- Ultimately, the workflow should be optimised for a user running in auto mode, without a local DB.

**Comment by havok2063** [comment]
Because Query is not a MarvinToolsClass, it has its own decision tree.  Either when mode is passed in explicitly or retrieved by config, it performs this tree check.  

* If the mode is local:
  - looks for a db, if found, keeps it local
  - if not db, switched mode to remote
* if the mode is remote:
  - looks for urlmap, if no, raises error
  - if urlmap, keeps mode as remote
* if the mode is auto
  - performs doLocal check
  - performs doRemote check

So because there is no local Query for anyone usually, it always gets internally set to `remote`.  That internal mode gets passed to Results.  Results will accept the `config.mode` if no mode is explicitly passed.  The same internal `Results.mode` is used when converting results to tools.  

The changes you suggest should be ok.  I just have to code the decision tree into the Results object.

**Comment by albireox** [comment]
I think not necessarily, but if it's easy to fix and we are done with the other stuff ... If not this can be a bugfix in 2.1.x.

**Comment by bretthandrews** [comment]
It might help encourage more feedback if we fix this quickly even if it is beyond the scope of 2.1.

**Comment by albireox** [comment]
Yeah, I agree. If it’s easy to change the decision tree for Queries and add
some tests, let’s try to have it fixed for 2.1.

On January 23, 2017 at 18:28:47, Brett Andrews (notifications@github.com)
wrote:

It might help encourage more feedback if we fix this quickly even if it is
beyond the scope of 2.1.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/sdss/marvin/issues/161#issuecomment-274683186>, or mute
the thread

**Comment by havok2063** [comment]
I'm having seconds thoughts about pieces of this.  For the vast majority of users they will not have a database.  That means that local mode and auto mode will fail.  If we switch to raising an error, then we will get notified every single time someone in auto mode tries to run a query.  Instead we can issue a warning, which I do now already, but also don't switch the mode.  If I do that then I have to make sure queries are actually halted.

**Comment by albireox** [comment]
My feeling is that if the mode is local the query should fail and stop if you don't have a database. If the mode is auto it should try the local mode, not find a database, and then go into remote mode. In the latter case (which will be the normal one) I think we don't want to issue a warning. It would be there every single time and would get annoying and confusing.

**Comment by havok2063** [comment]
Ok.  I've implemented raising a MarvinError when queries are attempted in local mode.  We'll get notified every single time now. For auto mode I'm doing the same thing we do in the Tools when local mode fails, i.e. issue a warning and switch to remote mode.

**Comment by havok2063** [comment]
Also, the auto mode for queries does the same thing as the auto mode for every other tool.  It runs a _doLocal or _doRemote and sets the mode to either local or remote internally.  That mode gets passed into the Results as well.  In none of the tools do we code for `mode=auto`.   

If we want the Results to have a different mode than query then we can't pass it in from the Query and the Results needs it own decision tree starting from the config.  

If we want the Results to the same mode as the Query then it is as it is now.  We explicitly pass it in from Query and it always only ever be `local` or `remote`
