### ISSUE TITLE
Add option to save query results to JSON, txt, csv, or other human readable format

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#162]
While pickling a results object should be the preferred method of saving query results, pickling has a few drawbacks:
- potential incompatibility across python versions 
- not human-readable

A common use case might be to run a query to do galaxy sample selection and then download all of those cubes. If the results from this query are pretty straightforward, even as simple as just plate-ifu (but potentially with a few other columns), then people might rather have a human readable output of it, so that they can inspect it later on without reloading the pickle file or so that they can share it with someone.

We might choose to not even implement a way to reconstruct the results or Tools objects from such a file, since doing so would be possible by looping over the file using standard python techniques.

**Comment by havok2063** [comment]
You can already save query results out as JSON, FITS, an Astropy Table, or a Pandas Dataframe.  I can add CSV.  These will only convert and save the list of results.  The advantage of pickling is that they save the original complete Marvin Results object, results, parameters, query string, converted tools, etc.

**Comment by bretthandrews** [comment]
I agreed that pickling is the cleanest way of saving and recovering a Results object, but there are other (and perhaps more frequently used) use cases. Since we already have these other methods, it should be pretty simple to add a "save as" kwarg to save() that accepts a filetype and would call these other methods plus the relevant dump to file command (since they only convert the object to another data type).

**Comment by havok2063** [comment]
I'd like to try and maintain some consistency in the code within our MarvinTools.  The save and restore methods are used for pickling across the suite of tools.  I completely agree with you that we should include methods for saving results in human-readable form.  I think we already have most of that in place that people can use, with the exception of CSV.  I'm following the astropy logic with the toJson, toFits, toTable, etc.  We can make a new method on Results that wraps all these other methods if you think that's more usable.  In that case, we'd probably hide all these other methods to avoid confusion.

**Comment by bretthandrews** [comment]
I like the astropy toDtype-style methods as opposed to a convert(type='json') method because the latter is more verbose. Until we get more feedback, I can be on board with the consistency of Marvin's save and restore methods. However, I think that we should include the code to output to human readable formats in tutorials.

The more I think about the use case of manipulation of query results, the more I think we just want to point people toward using the DataFrame (or Astropy Table) functions, so that we don't have to write a bunch of code that just wraps their functions. Again, it would be helpful to include example code in tutorials for doing things like plotting two columns against each other.

On a related note, I realized that we can just convert to DataFrame and then write to CSV.

**Comment by havok2063** [comment]
Yeah we can certainly expand our notebook tutorials to focus on different aspects of the Tools and the various features.  We should also explain how to do r.to(tab) to see all the to** options.  And also mention somewhere that users can to r.method? to see the docstring on how to use that method. 

I've already added a toCSV method which does the same thing as toFits, namely what you said but using astropy table.

**Comment by bretthandrews** [comment]
I didn't start relying on that tab trick until I saw you demoing the tools, so that will definitely be helpful
