### ISSUE TITLE
Add Python tip for showing spectrum

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#166]
Kate Rubin mentioned on the SciCon that she tried to use Marvin to get a spectrum but could not figure out how to do it. I showed her how to go to a galaxy page to get Python tips about using the Tools, but I realized that we should go one step further and extract wavelength, flux, ivar, and mask and then make a quick plot.

Can we add a Python tip to get a spectrum?

```
from marvin.tools.cube import Cube
cube = Cube(plateifu='8485-1901')
spaxel=cube[16,16]
spectrum=spaxel.spectrum
wave=spectrum.wavelength
flux=spectrum.flux
ivar=spectrum.ivar
mask=spectrum.mask
spec.plot()
```

**Comment by havok2063** [comment]
We can do this but I'd like to move away from people starting with the web.  If they are using the web then we can have these things to help, but really people ought to be starting with the tools themselves.  But I agree we should try to be more helpful to people who are new to Python or use IDL regularly.

**Comment by bretthandrews** [comment]
I'm actually coming more around to the idea that we want the web to be the gateway to the tools because so much of our user base only knows IDL.

**Comment by havok2063** [comment]
That's true.  And I think we do want it to be a gateway.  I'm just worried that users will only use the web.  I think one big issue holding people back (besides not knowing Python) is that the tools currently only really offer the same things people can already do in the web.  The Queries are more advanced in the Tools but are the other tools?

**Comment by bretthandrews** [comment]
We may want to try more screen sharing session on telecons, such as next week's DevCon when we announce 2.1 (assuming nothing catches on fire in the next week), to show people how to find the Python tips and then copy and paste them into ipython sessions.

The real power of the tools is that you can then manipulate the data, whereas with the web you can only see it as it already exists. Plus BPT.

**Comment by havok2063** [comment]
Right, so we should stress the data manipulation.  And yeah the BPT will be the first major thing, assuming people sign off on including it.
