### ISSUE TITLE
sdss_access may not be completely python 3 compatible

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#174]
After several hours, I finally managed to get my image utility tests to pass in Python 3 and 2.  sdss_access is now partially python3 compliant, but it may not be complete.  I've fixed only the areas of the code that were directly causing problems for my tests.  

We need to be aware that downloading via Marvin may be broken or intermittent until this can be fixed.   I've successfully been able to download a cube, and some images, but more extensive tests are needed.   Through these tests, several bits of sdss_access have been tested, but not the rest.   

These changes are in the Github repo of sdss_access but have not been pushed to the svn repo.

**Comment by bretthandrews** [comment]
I took a brief look through and there weren't any glaring python 3 incompatibilities

**Comment by havok2063** [comment]
The latest one was an issue between string and byte strings.   Parsing an rsync stream task output (inside `Rsync.generate_stream_task`), and trying to regex search on, plus doing string operations, gave some troubles.  After several trials and tribulations, I found a solution that worked for py2 and 3.

**Comment by albireox** [comment]
Seems to work for all of our purposes. Let's close and reopen if a new issue appears.
