### ISSUE TITLE
Improve Marvin Testing Suite

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#177]
Marvin Testing ToDo Items (over the next 6 months)

Here is a list of items and discussion points (in no particular order) on the road to the Summer Thaw.  Add, modify and update comments here as we move forward. 

- [x] Standardize (refactor) API / Web + add tests for api/web routing
        - [x] test web routes 
        - [x] api tests via tools
        - [ ] api tests via Interaction
        - [x] api tests via direct
        - [x] javascript and browser testing
- [x] Standardize the Python Marvin tests, e.g.
	- [x] always use MarvinTester
	- [x] consolidate common parameters / functions
	- [ ] decide on galaxies always to test
	- [x] decide testing etiquette , e.g.
- [x] Write more Python tests
	- [x] MPL-4 vs 5 vs 6  (can we systematize / generalize this?)
	- [x] covers bug, failure modes, and science vetting checks
- [x] Implement test production version of Marvin web at Utah (already have debug one)
- [x] Set up automated testing (e.g. Travis-CI + Coveralls or local python equivalent?)
	- [x] make small local testing db with agreed on test set of galaxies
	- [x] make a test data bank (decide how to grab any data files we need for tests)
	- [x] should handle py2.7, 3.5, 3.6 and at least a few os environments

**Comment by albireox** [comment]
Closing as this is implemented and passing for 2.1.4.
