### ISSUE TITLE
Issue import Marvin 2.1

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#179]
In [3]: import marvin
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-3-c829bc588ff7> in <module>()
----> 1 import marvin

/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/__init__.py in <module>()
     26 from marvin import extern
     27 
---> 28 from marvin.core.exceptions import MarvinUserWarning, MarvinError
     29 from brain.utils.general.general import getDbMachine
     30 from brain import bconfig

/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/core/exceptions.py in <module>()
     48             self.client = None
     49 
---> 50 ms = MarvinSentry(version=marvin.__version__)
     51 
     52 

/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/core/exceptions.py in __init__(self, version)
     44                         )
     45                 )
---> 46             self.client.context.merge({'user': {'name': os.getlogin(), 'system': '_'.join(os.uname())}})
     47         else:
     48             self.client = None

FileNotFoundError: [Errno 2] No such file or directory

**Comment by havok2063** [comment]
This is linked to Sentry Issue https://sentry.io/manga/marvin2/issues/220021783/

Hi Maria, 

Can you run this code in an ipython terminal and print the output here?

```
import sys
print(sys.version)

import os
print(os.uname())
```

**Comment by margudo** [comment]
Hi Biran,

Here is the output:

In [4]: import sys

In [5]: print(sys.version)
3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Dec  7 2015, 11:16:01)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

In [6]: import os

In [7]: print(os.uname())
posix.uname_result(sysname='Linux', nodename='totoro',
release='4.4.0-62-generic', version='#83-Ubuntu SMP Wed Jan 18 14:10:15 UTC
2017', machine='x86_64')

2017-02-16 17:45 GMT-03:00 Brian Cherinka <notifications@github.com>:

**Comment by albireox** [comment]
An attempt to fix this is included in 02fee050f656ee6665cbd7c53c7bf60514212529

**Comment by margudo** [comment]
Doesn't work.
I think that some dependency is not well defined, some missing file that you have and for some reason is not in github. I have checked that Iḿ using the correct pip for my anaconda distribution.

This is my report:

mamen@totoro:~/anaconda3/bin$ ipython
Python 3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Dec  7 2015, 11:16:01) 
Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import marvin
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/core/exceptions.py in __init__(self, version)
     48             try:
---> 49                 self.client.context.merge({'user': {'name': os.getlogin(),
     50                                                     'system': '_'.join(os.uname())}})

FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

NameError                                 Traceback (most recent call last)
<ipython-input-1-c829bc588ff7> in <module>()
----> 1 import marvin

/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/__init__.py in <module>()
     26 from marvin import extern
     27 
---> 28 from marvin.core.exceptions import MarvinUserWarning, MarvinError
     29 from brain.utils.general.general import getDbMachine
     30 from brain import bconfig

/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/core/exceptions.py in <module>()
     61             self.client = None
     62 
---> 63 ms = MarvinSentry(version=marvin.__version__)
     64 
     65 

/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/core/exceptions.py in __init__(self, version)
     51             except (OSError, IOError) as ee:
     52                 warnings.warn('cannot initiate Sentry error reporting: {0}.'.format(str(ee)),
---> 53                               MarvinWarning)
     54                 self.client = None
     55             except:

NameError: name 'MarvinWarning' is not defined

**Comment by albireox** [comment]
Mmm, no, the reason is that `MarvinWarning` is defined later in the same file, but I think this is encouraging. I'll fix this a release a new dev version for you to test in a bit.

**Comment by albireox** [comment]
OK, can you try doing 

`pip3 install --pre --upgrade sdss-marvin`

You should get version 2.1.2.dev2. Let me know if that one works.

**Comment by margudo** [comment]
Ok, with some warnings but I have it!

In case it helps, here is the report. I'll let you know if I have any problem doing things

Thanks!

In [1]: import marvin
/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/core/exceptions.py:53: UserWarning: cannot initiate Sentry error reporting: [Errno 2] No such file or directory.
  UserWarning)
WARNING: no SAS_BASE_DIR_DIR found. Creating it in /home/mamen/sas
WARNING: no MANGA_SPECTRO_REDUX_DIR found. Creating it in
         /home/mamen/sas/mangawork/manga/spectro/redux
WARNING: no MANGA_SPECTRO_ANALYSIS_DIR found. Creating it in
         /home/mamen/sas/mangawork/manga/spectro/analysis
INFO: No release version set. Setting default to MPL-5
WARNING: path /home/mamen/sas/mangawork/manga/spectro/redux/v2_0_1/drpall-v2_0_1.fits
         cannot be found. Setting drpall to None.
WARNING: metadata {'config': True} was set from the constructor.  Metadata should be set
         using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
WARNING: metadata {'config': True} was set from the constructor.  Metadata should be set
         using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
WARNING: metadata {'config': True} was set from the constructor.  Metadata should be set
         using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
WARNING: metadata {'config': True} was set from the constructor.  Metadata should be set
         using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
WARNING: metadata {'config': True} was set from the constructor.  Metadata should be set
         using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')

In [2]: marvin.__version__
Out[2]: WARNING: DisplayFormatter._ipython_display_formatter_default is deprecated: use @default
         decorator instead.
WARNING: PlainTextFormatter._singleton_printers_default is deprecated: use @default
         decorator instead.
WARNING: PlainTextFormatter._type_printers_default is deprecated: use @default decorator
         instead.
WARNING: PlainTextFormatter._deferred_printers_default is deprecated: use @default
         decorator instead.
'2.1.2.dev2'

**Comment by albireox** [comment]
Yes, Python 3 seems to be much more verbose with the warnings, but nothing there seems to be an obvious problem.

**Comment by havok2063** [comment]
If we want to push this we can make a new 2.1.2 release once the db is back up and running.  We'd get the BPT fix and the new NSA columns.  However, I didn't realize we would be doing this so soon.  I would have held off merging my apiredo branch into master since that hasn't been thoroughly tested.  (Just the standard way of running the tests we have).

**Comment by albireox** [comment]
So far only two people have reported this specific problem. I think waiting for the apiredo branch or not depends on how long you think it will take to test it thoroughly. I'd like to get this and the BPT fixes out quickly, but not necessarily immediately.

**Comment by havok2063** [comment]
I think most of it is in good shape.  I did a fair amount of testing and made sure all the API and web routes worked, but I don't have all the tests written.  Let's wrap up everything we want to include in this release, do a final sweep of all the tests we have, and each do some checks on the API and web calls once it's at Utah in marvintest.  Then we can release as soon as we all sign off on that.

**Comment by albireox** [comment]
Sounds good to me.

**Comment by havok2063** [comment]
I think this is fixed now, and will be pushed in the 2.1.2 patch release.
