### ISSUE TITLE
Set the names of the three default maps in MapSpecView to be selected

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#182]
Hi,

Some comments about maps in the web:

- The maps appear elongated in the X direction. Spaxels should be square, not elongated. I have seen that in the new version, the width is adapted to the browser, this should be proportional in both directions.

- By default, three maps are shown as example. However, the maps tab says ''nothing selected''. Maybe the three default maps can appear selected in the tab.

- Have you considered to remove the Map/SpecView ON-OFF button? It seems redundant.

**Comment by bretthandrews** [comment]
I tried for far too long to make the spaxels square. The issue is that the width is set dynamically, and it is very difficult to then reset the height to match.

**Comment by bretthandrews** [comment]
Returning the Map/SpecView requires sending a fair amount of data. If you have a fast connection, then you would be fine with loading all of that initially. However, if you are on a slow connection (I think that was an issue in Shanghai), then the page will take forever to load.

**Comment by margudo** [comment]
I see, I understand.

Regarding spaxels square, is this an issue related to the web or the tool you are using to create the maps?

**Comment by bretthandrews** [comment]
It's a javascript/bootstrap issue. (I'm not sure if you were asking if the plots are square in Marvin-tools, but they should be.)

**Comment by bretthandrews** [comment]
@havok2063 Select the names of the three default maps in MapSpecView

**Comment by havok2063** [comment]
This has been fixed.
