### ISSUE TITLE
Documentation link and order

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#184]
Hi, a couple of comments to enhance the documentation. 

- In Marvin page https://sas.sdss.org/marvin2/ there are two links to the documentation, both of them as ''help''. I would suggest to change the first link, at the top of the page (Marvin, Github, Help, Search), as ''Documentation'' or ''Docs'', and to keep the second one (about, image roulette, help).

- The order in ''about'' in https://sas.sdss.org/marvin2/ is web-API-tools, but in the documentation page https://api.sdss.org/doc/manga/marvin/ is Tools-API-web. I would suggest to keep the same order.

- Having a look to the documentation I have seen some typos, and some other things to improve, for example, when documenting NSA display, add the reference to NSA and the complete name of the catalogue when first introduced. I could help writing documentation if you want. 

Cheers

**Comment by bretthandrews** [comment]
We would definitely appreciate any help with writing the documentation. It can be difficult for us to maintain perspective, so we would be happy to get some help from fresh eyes.
