### ISSUE TITLE
Change what are listed as bolded parameters in NSA display

### ISSUE THREAD

**Issue by yanrenbin** [sdss/marvin#186]
In the NSA display, a smaller subset of parameters are bolded and can be selected as labels of the plots. I think we should list ELPETRO version of the absolute magnitude and stellar mass, rather than the Sersic version, because it is ELPETRO that is used in our target selection. And we believe they are better than the Sersic measurements. So, I suggest we use ELPETRO version of the ABSMAG (i-band, not r-band),  MASS, and MTOL (i-band) in the bolded list.   We can keep Sersic_n as it provides additional information that the ELPETRO doesn't.

**Comment by bretthandrews** [comment]
Terrific! This is exactly the sort of scientific feedback that we were hoping to get!

**Comment by havok2063** [comment]
Yeah I think this should be reasonable to do.

**Comment by havok2063** [comment]
This is now fixed and will be pushed into the 2.1.2 patch release.
