### ISSUE TITLE
Enable map plotting using the BPT mask

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#189]
Allow Map.plot() to take a mask (could be a generic mask but the specific use case was a BPT mask). This might involve using a np.ma.array.

**Comment by albireox** [comment]
+1 on this. I think it should be easy to implement. We just need to add a `user_mask` keyword to `.plot()` and pass it to `._make_image()` to be added to the spaxels to mask. Or, we may want to give the user-masked spaxels a specific colour to differentiate them from the no-data or bad-data spaxels.

**Comment by bretthandrews** [comment]
This now works after the map plotting code got refactored into utils/plot/map. See the plotting tutorial doc page for an example.
