### ISSUE TITLE
move unit-ed parameters to astropy quantities

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#191]
Should we move all our parameters that have units to Astropy Quantities, and use Units?  This could ensure proper coordinate conversions and prevent people from making mistakes.

**Comment by albireox** [comment]
Yes, I agree with this. For the DAP maps it would be as simple (it never is) as modifying the units in the datamodel to be Astropy units.

**Comment by havok2063** [comment]
Do we also want to convert all the values/ivar into Quantities as well?

**Comment by bretthandrews** [comment]
Sure. Though we might have to first sort out the per spaxel units of the binned maps.

**Comment by albireox** [comment]
This is done via the quantity classes.
