### ISSUE TITLE
Jupyter notebooks and documentation need to be version specific.

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#192]
A student brought this to my attention. From one of the notebook she got

```
maps = Maps(plateifu='8485-12701')
haflux = maps['emline_gflux_halpha_6564']
fig, ax = haflux.plot()
```

She is running an old version of marvin for which `.plot()` only returns `figure`, so that line fails. I cannot find those lines in the current version of the documentation, so this may already be fixed, but I'm opening this issue because at some point we should consider a method (e.g. readthedocs) to version control the documentation.

**Comment by albireox** [comment]
Related to this, it seems to be possible to have our own [private readthedocs server](http://docs.readthedocs.io/en/latest/install.html). Maybe we can install this at Utah and start using it to version control the documentation.

**Comment by havok2063** [comment]
Is there an advantage to this over using the real readthedocs?

**Comment by albireox** [comment]
Keeping all the pieces of Marvin under the same roof (I.e. Utah). If that does not feel like a strong need (it does not for me) we can use the hosted read the docs.

**Comment by havok2063** [comment]
I don't have a strong need either.  Can we continue to develop our docs the same way with readthedocs?  Are there any maintenance considerations?  i.e. updating readthedocs versus updating the sdss api docs.  Would we just deprecate the sdss api docs?

**Comment by albireox** [comment]
This is mostly ready to deployed with the next release. The documentation for 2.1.2 should build on readthedocs, but we won't be able to build any previous version.
