### ISSUE TITLE
Bin not loading from local sas

### ISSUE THREAD

**Issue by KateRowlands** [sdss/marvin#196]
When I have a logcube in my local sas and I load a Bin with the same plateifu, it fails. Loading a bin only works if I specify mode='remote' and config.download = 'True'. If mode='remote' and config.download = 'False' the Bin loading also fails with the same error.

Reproduction steps:
config.mode = 'local'
config.download = False
bin_dump = Bin(binid=0, plateifu='8719-12701', bintype='VOR10')

Note that the VOR10 logcube of 8719-12701 is in my local sas and loads successfully with
cc = ModelCube(plateifu='8719-12701', bintype='VOR10')

Expected results:
Bin loads successfully.

Actual result:
Crashes with error message:
MarvinError: this is the end of the road. Try using some reasonable inputs..

See attached text document for stacktrace.
[Stacktrace.txt](https://github.com/sdss/marvin/files/815645/Stacktrace.txt)

**Comment by albireox** [comment]
Hi Kate,

Thanks for reporting this. I have been able to reproduce the problem, so we should be able to fix it.

There are two problems here: first, you are using 

```
config.mode = 'local'
config.download = False
```

In general I would advice not to use `config.mode = 'local'`, and keep it in `'auto'`. If you have all the necessary files in your local SAS, Marvin should be smart enough to use them if `config.mode='auto'`.

Now, to load the bin from your example from files, you need not only the DAP logcube, but the DRP logcube, the DAP Maps for VOR10, and the Maps and logcube for SPX (yes, it's a lot of information, maybe we can reduce this in the future).

If you do this

```
config.mode = 'auto'
config.download = True
bin_dump = Bin(binid=0, plateifu='8719-12701', bintype='VOR10')
```

Marvin should download all the files you need. The second issue is that, if you do this, you'll see and error like 

```
OSError: filename /Users/albireo/Documents/MaNGA/mangawork/manga/spectro/redux/v2_0_1/8719/stack/manga-8719-12701-LOGCUBE.fits.gz cannot be found: [Errno 2] No such file or directory: '/Users/albireo/Documents/MaNGA/mangawork/manga/spectro/redux/v2_0_1/8719/stack/manga-8719-12701-LOGCUBE.fits.gz'
```

Even if the file has been downloaded. I think this has to do with Marvin trying to load the logcube too quickly, before the file is in the right path. In any case, if after this error you restart Marvin and run

```
config.mode = 'local'
config.download = False
bin_dump = Bin(binid=0, plateifu='8719-12701', bintype='VOR10')
```

it should work and get all the information from your files. Can you give a try and see if this behaves the same in your system?

This is a good example of use to help us decide how to restructure the Bin class, as I commented in #197.

**Comment by KateRowlands** [comment]
Hi Jose,

The above code works for me. Thanks for your help with this, I didn't have the DRP logcube which was causing issues. 

The first time I run 

config.mode = 'auto'
config.download = True
bin_dump = Bin(binid=0, plateifu='8719-12701', bintype='VOR10')

I get this message:
WARNING: PLATEID = 8719 / Current plate 
a string value was expected.

But I can access the bin.

If I rerun then all is fine and I get no warning.

**Comment by albireox** [comment]
Terrific! There is still an issue here, but I'm glad you got it working for now.

The warning `WARNING: PLATEID = 8719 / Current plate` is expected (it has to do with astropy and a non-default FITS value). It will only appear once per plate and session, but it should not be a problem in any case.

**Comment by havok2063** [comment]
Not sure if this got fixed or not in 2.1.2 but bumping it to 2.1.3

**Comment by margudo** [comment]
Is this issue already fixed?

**Comment by albireox** [comment]
I think this is all fixed now. Closing.
