### ISSUE TITLE
should we move to Bokeh for all plotting

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#198]
Should we move to Bokeh to replace all plotting in the Tools and the Web?  It's a Python plotting package that is similar in structure to matplotlib, and allows to create D3 style interactive graphics and push them to the web or Jupyter notebooks.  

This could consolidate all the plotting stuff together and would literally allow people to recreate what they see in the web.  We would be sacrificing some advanced visualization stuff in the web, but we may be gaining in the seamless connectivity or reproducibility between the web and tools. 

Main: http://bokeh.pydata.org/en/latest/
Gallery: http://bokeh.pydata.org/en/latest/docs/gallery.html
Example integration in Flask: http://blog.thedataincubator.com/2015/09/painlessly-deploying-data-apps-with-bokeh-flask-and-heroku/

**Comment by joelbrownstein** [comment]
Just curious. Did you do a feature comparison of plotly vs bokeh (not that I have any experience with either)?

On Mar 4, 2017, at 12:03 PM, Brian Cherinka <notifications@github.com<mailto:notifications@github.com>> wrote:


Should we move to Bokeh to replace all plotting in the Tools and the Web? It's a Python plotting package that is similar in structure to matplotlib, and allows to create D3 style interactive graphics and push them to the web or Jupyter notebooks.

Main: http://bokeh.pydata.org/en/latest/
Gallery: http://bokeh.pydata.org/en/latest/docs/gallery.html
Example integration in Flask: http://blog.thedataincubator.com/2015/09/painlessly-deploying-data-apps-with-bokeh-flask-and-heroku/

**Comment by albireox** [comment]
It's certainly neat but I'm wary of dropping the advanced plotting functionalities from matplotlib. How do the two of them compare? Right now most of our plots are relatively simple (maybe with the exception of the BPTs, and that only because of the grid axes), but who knows what we'll want to do in the future.

Can we use Bokeh (or plotly) to ditch D3? That is, can we do interactive JS stuff like the ones D3 does? Can we, for instance, replace the point-and-click spectrum with Bokeh?

**Comment by havok2063** [comment]
I have only briefly looked at Plotly compared to Bokeh, but they seem very similar.  I know of people who use both.  They are both designed for creating interactive visualizations in Python and pushing them to the web, in html or in Jupyter notebooks.  Plotly seems to have a pricing scheme associated with it, but there may be a free component.  Plotly may also be more chart-oriented.    

Here is a nice article comparing the current state of Python visualization tools.  https://blog.modeanalytics.com/python-data-visualization-libraries/

Here is a blog post which compares creating the same plot in different Python tools.
https://lisacharlotterost.github.io/2016/05/17/one-chart-code/

Bokeh is certainly newer than Matplotlib and not as feature rich.  Its focus seems to be on creating interactive D3 style plots for the web but from the comfort of Python.  A lot of people in the astro software groups are using it now since Jupyter notebooks are growing in popularity.  Bokeh also provides easy ways of linking datasets between plots, which is a big thing people are doing now.  I'm not sure if you can use Bokeh to display a local figure or if it always outputs to a web/notebook.  

Yes, the idea for us to use Bokeh (or Plotly) would be to ditch D3 and the javascript libraries we use for visualization and adopt some kind of standard.  We currently use 4 different JS libraries.   Although there will never be one library that can provide us with everything.   The point-and-click spectrum would work the same way.  Click, do an Ajax call, get new spaxel, return the new Bokeh plot.  Point-and-click on the maps would be the same.  Click, do an Ajax call, get new maps, return the new Bokeh plots.

**Comment by havok2063** [comment]
Closing.  Out of scope.
