### ISSUE TITLE
Add Astropy badge

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#199]
Astropy suggests adding a badge if your project uses it.

http://www.astropy.org/about.html#acknowledge

add this to README:
[![astropy](http://img.shields.io/badge/powered%20by-AstroPy-orange.svg?style=flat)](http://www.astropy.org/)

**Comment by bretthandrews** [comment]
That was easier than I thought.

**Comment by havok2063** [comment]
These are the kinds of issues we like.  We should make a powered by Marvin badge. Or Marvin's Brain badge.
