### ISSUE TITLE
Web error

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#200]
This is the error reported by Kevin, I'm obtaining the same.

MarvinError: Could not retrieve cube for plate-ifu 8484-9101: Unknown exception: (psycopg2.OperationalError) FATAL: password authentication failed for user "sdss" . You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new). Fill out a subject and some text describing the error that just occurred. If able, copy and paste the full traceback information into the issue as well.

**Comment by havok2063** [comment]
This should now be fixed with the db back up and running.
