### ISSUE TITLE
BPT on custom data

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#201]
Hi,

I wonder if I could apply the BPT tool on my stacked MaNGA spectra.

Thanks!

**Comment by albireox** [comment]
Hi María,

We'd need more information to know if that's possible. How have you created the stacked spectra? The BPT tool uses a DAP MAPS file / data. So, unless the format of your stacked spectra is the same, I think the answer is no. But maybe you can take a look at the code and adapt it to your needs.

**Comment by margudo** [comment]
Hi José,

Yes, I have been thinking on that. I'm stacking DRP spectra following a modification of the DAP stacking routine in IDL, but I don't have emission line measurements at this moment. So yes, I guess the best way is to adapt the code, it's so cool!

Thanks!

**Comment by albireox** [comment]
I think we can close this. It would be nice to be able to get BPTs on custom data but, at least in the way explained in this issue, that's beyond the scope of Marvin right now.
