### ISSUE TITLE
no release "trunk"

### ISSUE THREAD

**Issue by blanton144** [sdss/marvin#203]
There is no release "trunk." Of course, "trunk" is unlikely to be complete, but it does seem as if a good use case for Marvin is to look at data in progress. I.e. even if there are not cubes, I might want to look at RSS files, for example.

**Comment by albireox** [comment]
This is a good point but it would mean to ingest data into Marvin as soon as it is reduced. I don't think this was included in our original planning (and wouldn't be totally trivial to implement) but it is worth discussing.

**Comment by havok2063** [comment]
I think this is no longer relevant.
