### ISSUE TITLE
change nsa colors to absolute magnitude colors

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#204]
As requested by Matt Bershady, the colors as computed from the absolute magnitudes would be more valuable, rather than from apparent magnitudes.  We should compute these and add them to the list of available NSA parameters accessible from the tools, and make these the default plottable ones on the web.  

He also suggested adding, in the web, the ability to have the user combine different NSA parameters together using different specified mathematical operations.

**Comment by blanton144** [comment]
Yes, I just noticed this one too. You probably also want the ELPETRO magnitudes and colors rather than SERSIC.

**Comment by havok2063** [comment]
the switch to elpetro is already done and will get pushed in a 2.1.2 patch release
