### ISSUE TITLE
Query without necessarily returning Cube

### ISSUE THREAD

**Issue by blanton144** [sdss/marvin#205]
Hi Folks, I would like to use the Marvin Query tool to access the database WITHOUT returning the cube ID. In particular, I would like to avoid the Join with the cubes, so that I can retrieve data that doesn't necessarily have an associated Cube. Specifically I want to query on the full NSA catalog. It'd be cool to have that through the API too, but the first step is just to have the Query tool get at it locally, I suppose. The Query tool, though, has the default parameters to return set pretty deep in it. I haven't quite figured the code out yet enough to see where the base query is ACTUALLY made, but before I do --- how should I imagine customizing this? Should I create a subclass from Query and just adjust set_defaultparams()? I can't tell yet whether that would even work. But that solution might survive best any coming abstraction of Query to the brain.

**Comment by havok2063** [comment]
Oh boy.  You're really digging into things.  I think right now you can't turn off any of the default parameters.  That would be a good feature to add.   Thinking only slightly about it, it would be fairly complex to implement this feature, but it's doable.   

The base Query is made in a method called `_createBaseQuery`  which is checked and called via decarator `makeBaseQuery` at various other places in the code.    I think right now, the easiest way to customize this would be to subclass the Marvin Query and override `set_defaultparams`.   There's a lot of other things the Query does to prepare itself for being constructed and run, but just changing that method should be sufficient.  

You could also fork Marvin, install the dev version, and modify the Query code directly, and potentially start prepping the Query for abstraction.

**Comment by blanton144** [comment]
OK, I'm going to close this as an issue, since it occurs to me it isn't exactly an issue. I'll note that Query, it turns out, has deeper requirements on Cube existing (my local db doesn't have Cube, so this fails immediately). OTOH, I'm not sure generalization of Query is something that I should start, at least not without a lot of discussion first. I'll stick w/ subclassing for the moment.

**Comment by havok2063** [comment]
Reopening since this is an enhancement and issues can be anything really.  And it's good to leave this out there so we keep it relevant.  

Yeah, we also use the Cube ModelClass as a nexus point to traverse the db schema path.   If you don't have a Cube table in your db, or a Cube ModelClass, you can provide a different nexus point.  In your case, you'd want to use the `marvindb.sampledb.NSA` ModelClass as the nexus.  You can override the `_join_tables` method to update this.  The modelgraph, which is the thing used to build the schema-node-traversal-tree, is built and loaded from the marvindb object.

**Comment by blanton144** [comment]
This turned out to not be so bad to deal with, using a subclass of Query. Code is below. My local db only contains the mangasampledb schema, which means that I had to turn off _addPipeline(). The join construction seems like the thing that will be hardest to generalize in Query.

This experience showed me how much there is to abstract still, which is a lot. Much of Query is totally general, but it is interspersed with some pretty specific stuff.

Anyway, this will allow me to use nsaQuery in local mode until a more general solution is created. Obviously I can't use in remote mode because the server doesn't allow. Even though this is just one table, just being able to do this is quite useful.

============================

from marvin import marvindb
from marvin.tools.query import Query
from marvin.tools.query.query import makeBaseQuery


class nsaQuery(Query):
    def __init__(self, *args, **kwargs):
        super(nsaQuery, self).__init__(*args, **kwargs)

    def set_defaultparams(self):
        ''' Loads the default params for a given return type
        '''
        self.defaultparams = ['nsa.nsaid']

        # add to main set of params
        self.params.extend(self.defaultparams)

    @makeBaseQuery
    def _join_tables(self):
        ''' Build the join statement from the input parameters '''
        self._modellist = [param.class_ for param in self.queryparams]

        # Gets the list of joins from ModelGraph. 
        joinmodellist = self._modelgraph.getJoins(self._modellist, format_out='models', nexus=marvindb.sampledb.NSA)

        # sublist = [model for model in modellist if model.__tablename__ not in self._basetable and not self._tableInQuery(model.__tablename__)]
        # self.joins.extend([model.__tablename__ for model in sublist])
        # self.query = self.query.join(*sublist)
        for model in joinmodellist:
            name = '{0}.{1}'.format(model.__table__.schema, model.__tablename__)
            if not self._tableInQuery(name):
                self.joins.append(model.__tablename__)
                self.query = self.query.join(model)

    def _addPipeline(self):
        pass

**Comment by havok2063** [comment]
This has been implemented in the Marvin 3.0 refactor of Query for DR15.
