### ISSUE TITLE
Velocity maps are hatched near zero velocity contour

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#206]
As pointed out by @kbwestfall.

The velocity maps are hatched near the zero velocity contour because the signal value is close to zero, so these spaxels do not meet the minimum SNR threshold.

The simplest solution would be to not set a minimum SNR for the velocity maps, though this might show spaxels with very slow real SNR. The SNR cut should probably be done on the velocity relative to Earth (not the NSA redshift of the galaxy).

**Comment by kbwestfall** [comment]
This was actually the thought that I had on my walk to the bus this morning.  Measurement over error as an assessment of the quality of the velocity doesn't work very well.  We (meaning me) basically just need to figure out where we trust the velocity measurements.  The cut will most likely be based on the spectrum S/N, measured sigma, and/or measured velocity error, but not any of those relative to the measured velocity.

**Comment by kbwestfall** [comment]
I think the short-term fix is that you just plot all the velocities, but work under the assumption that there will eventually be flags in the mask (like UNRELIABLE or DONOTUSE) that Marvin can use to decide whether or not to plot the velocity measurements.
