### ISSUE TITLE
Get Maps in MapSpecView of Galaxy page sometimes fails to return selected maps

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#207]
In MapSpecView of the Galaxy page, the select DAP Maps and Get Maps button will SOMETIMES return the following error:

"Could not get map for one of supplied parameters"
(see web/controllers/galaxy.py line 126)

However, redoing the same process sometimes works when page is reloaded, so reproduction is difficult. Alsot, there is no error returned in the JS console.

**Comment by havok2063** [comment]
This is a feature not a bug! I think this occurs when one map cannot be retrieved or does not exist.  The entire set of 3 will get flagged and this message will return.  If you see it again when you know the maps should exist and get returned, we can reopen.
