### ISSUE TITLE
marvin version from pip install is incorrect

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#209]
The version of Marvin as indicated by `marvin.__version__` is incorrect after either a fresh pip install of an old version, or when you `pip install --upgrade`

**Comment by havok2063** [comment]
This seems to work now in my fresh Conda environment for 2.7, and 3.5.  I was able to upgrade from `2.1.2dev3` to `2.1.2` and then to downgrade to `2.1.0`.

**Comment by albireox** [comment]
It still doesn't seem to work on Python 3.6.1 (homebrewed). Let's keep this open until we are sure it work on all versions and in the future.

**Comment by albireox** [comment]
Fixed enough as of 2.1.4. We have talked about switching to bumpversion for versioning in the future, so if there are lingering issues we can deal with them then,
