### ISSUE TITLE
Use of WTForm Validation

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#21]
<a href="https://github.com/havok2063"><img src="https://avatars.githubusercontent.com/u/1836302?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [havok2063](https://github.com/havok2063)**
_Thursday Jul 07, 2016 at 14:33 GMT_
_Originally opened as https://github.com/marvin-manga/marvin/issues/16_

----

Marvin query should use WTForm validation where it can. Move to natural language sql string makes this a bit difficult, especially since using WTForm-Alchemy auto generates the forms from sqlalchemy modelclasses.

**Comment by albireox** [comment]
<a href="https://github.com/havok2063"><img src="https://avatars.githubusercontent.com/u/1836302?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [havok2063](https://github.com/havok2063)**
_Thursday Jul 07, 2016 at 14:34 GMT_

----

Brian

I've implemented a MainForm in MarvinForm to contain the simple single search box, to be used in the web. This is validated for no input, and not enough characters. Requires a minimum of 3 characters in text box (e.g. z<1). 

Also implemented individual parameter validation for the filter parameters, however this currently does nothing as no validation as been built in. E.g. 

p = 'nsa_redshift < 0.012' 

will get parsed and 0.012 will get validated, but always returns True. I still need a way to automatically assign WTForm validators during the Form generation, based on the type of Field that gets created by WTForm-Alchemy. 

Column name crashes as expected in the right place, but still need to catch this....

**Comment by albireox** [comment]
<a href="https://github.com/havok2063"><img src="https://avatars.githubusercontent.com/u/1836302?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [havok2063](https://github.com/havok2063)**
_Thursday Jul 07, 2016 at 14:34 GMT_

----

Not sure if this is relevant or important anymore.

**Comment by havok2063** [comment]
Don't think we need this anymore.
