### ISSUE TITLE
do queries allow searches on array values?

### ISSUE THREAD

**Issue by blanton144** [sdss/marvin#211]
When I try a searchfilter in Query like "nsa.elpetro_absmag[4] < -24." this returns a syntax error, that originates in sqlalchemy_boolean_search's parse_boolean_search. It appears to be complaining about the [4].

How does one reference array elements in the searchfilter? If there is no way to do this I think it is a problem.

**Comment by havok2063** [comment]
I think you can do it in SQLAlchemy and Postgres but not yet in sqlalchemy_boolean_search.  We have to code that option in sqlalchemy_boolean_search.  You can currently query on individual array elements that we have explicitly expanded out via `hybrid properties`.  E.g. the `nsa.elpetro_mag_[ugriz]` and `nsa.elpetro_mag_g_r` etc.  We would have to do the same for the `nsa.elpetro_absmag`, and any other arrays.  See `db/models/SampleModelClasses/` line 206+ on hybrid colours, mags, properties, and methods.  

You can also ask, if the parameter is an array, where any value in that array satisfies the condition, I think using, `spaxel.flux > 100` converts to `return rows where the flux array has any value larger than 100`, but you can't query on specific indices.  It's always been on the mind but no one expressed a large enough voice to make querying within arrays a priority.  
  
The other option is to create new rules and cases in boolean_search to parse the syntax of `absmag[i]`.  One thing that we need to do is expand the capabilities of boolean_search all around.  Currently accepted syntax is conditional `parameter operator value` or function conditional `fxn(condition) operator value`.

**Comment by blanton144** [comment]
I can work with this. It is easy to create a hybrid property for what I need it looks like. Note however the other issue I reported with parse_boolean_search.

In general, I'm curious about the motivation for shortcuts and hybrid properties in the python rather than in the database. It may not matter *much* in this case but it seems like all of these needs could be fulfilled with database views, using functions and aliases.

The disadvantage is that you'd not be able to make changes in the shortcuts without possibly big changes in the db.

But it would have the advantage that it would look the same to a user no matter how they connected to the db. Perhaps more importantly it would allow indexing on (e.g.) g-r or absmag_r or whatever (I'm pretty sure anyway).

**Comment by havok2063** [comment]
The shortcuts are just a column name replacement designed to make it easier on the user when they type their filters.  They don't really have anything to do with the database per se.   People say "h alpha flux" so we make a shortcut "haflux" that converts to "emline_gflux_ha_6564".  Marvin simply remaps it when it's constructing the query.     

Hybrid properties make it easy to customize and modify additional columns without adding new columns all the time.  It's kind of a pain to add new columns to a table in such a way that it doesn't take a long time to run.  We ran into this before, and our final solution ended up being to dump the entire table and recreate it.  That ended up being way faster.   We have talked about making some of the more common computed attributes real columns in the db.  And yeah, you're right in that we then could index them, which we don't get now.   I don't think we're opposed to it, but I'd want to know that we'll gain significant improvements in query times.  Our hybrid properties currently consist of logmass, colors, and some emission-line ratios.       

I think the end user sees the same thing now no matter how they connect to the db.  Even via direct API call, the back-end still uses Marvin Tools, so shortcut names are acceptable and get converted.  It would be a different story if our API mapped directly to the DB tables, which is an option people do when building APIs.

**Comment by blanton144** [comment]
What I'm saying is that you could make the shortcuts native in the database with Views. I do hear you that it is easier to create the Hybrid property than to change the backend database (but you don't have to add new columns, you have to change the View --- it is re-indexing that would be the painful part I'll bet, though maybe you can get around that). Anyway, I doubt it is a performance problem for most of your tables (though the maps tables must be pretty big).

**Comment by havok2063** [comment]
Yeah adding new columns is only really and issue for the spaxel property tables.  I've experimented with creating Materialized Views before for the clean version of the spaxelprop tables, but ran into problems.  The view didn't propagate all the way up our chain.  A new table or view needs a new sqlalchemy ModelClass representing it, to be seen by WTForms, integrated into MarvinForm, understandable by boolean_search, etc.  I can't quite remember, but I think my last attempt at making a view broke at either the SQLA or WTForm stage in our chain.  

If we created a single view of shortcuts and hybrid properties, we'd also have to decide what it's called and how people reference it.  People don't have to specify table names if parameters are unique, but we've been advocating the practice of using `tablename.propertyname` at all times.  From a semantic point-of-view, it's a bit odd to have users specify, e.g. `shortcut.g_r` or `shortcut.nii_to_ha` rather than have them be in the tables that make the most sense.  But maybe there's a workaround.  

I don't think it's impossible to do and may be better for us, I'm just saying there are several things to consider.

**Comment by albireox** [comment]
This seems to be all implemented as of 2.1.4, with the exception of being able to query on `nsa.elpetro_absmag[4] < -24`. We discussed this and agreed that it is clearer to always specify the band on which we are querying, e.g, `nsa.elpetro_absmag_g` instead of the array index.
