### ISSUE TITLE
BPT plot image does not show up on readthedocs

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#212]
http://sdss-marvin.readthedocs.io/en/latest/tools/bpt.html

Image missing:
http://sdss-marvin.readthedocs.io/en/latest/tools/_static/bpt.png

**Comment by havok2063** [comment]
Someone else yesterday had an issue with links and images not showing up in readthedocs.  Not with the BPT pages but with other things.  It eventually started working for them.

**Comment by bretthandrews** [comment]
I needed to `git add -f _static/bpt.png` to override the `.gitignore` file
