### ISSUE TITLE
shortcuts applied blindly to searchfilter

### ISSUE THREAD

**Issue by blanton144** [sdss/marvin#213]
The way the shortcuts are applied to the searchfilter in query.py is dangerous. The short cuts are replaced wherever they appear in the text of the search filter.

I ran into this because "elpetro_absmag_r" was being replaced with "elpetro_absmaelpetro_mag_g_r" (because "g_r" was replaced by "elpetro_mag_g_r"). I'm pretty sure this must affect other things (e.g. what if I query with "maps_header_value"? is this replaced with "maps_maps_header_value"?).

You could be cleverer by identifying specific words and only replacing full words.

Or ... you could just solve shortcut problem in the db using views (for table short cuts) or views with aliases (for column short cuts).

**Comment by havok2063** [comment]
Yeah, that will be a problem, at least for colors.  We can certainly make the shortcut system smarter.   It may only affect parameter names and not table names.  At least I haven't been able to create a false replacement using `maps_header_value` or others like `ifu`.

**Comment by albireox** [comment]
I thought I had commented on this put it seems no. This should be fixed as per PR #230, which now uses regex to replace only full words, as suggested by @blanton144.
