### ISSUE TITLE
extern packages have no knowledge of each other

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#214]
I'm running into the problem where the marvin_brain package in extern does not know about the sdss_access package also in extern.  Marvin knows and can import and use both.  I think we should add something to make sure that at least the internal Brain knows about other internal packages it needs, especially if we're going to use the Brain more for generic things.  

Eventually, the solution should probably be to make all of these things pip installable packages, but for the short term, maybe we can just add another explicit import.  Or to make it more difficult, make sdss_access a submodule of the Brain as well as Marvin.

**Comment by havok2063** [comment]
Note this won't be reproducible if you have an explicit reference to marvin_brain via a MARVIN_BRAIN_DIR pointing to either the git or svn module.

**Comment by albireox** [comment]
We discussed this and the agreed that the final solution should be to make all submodules be pip-installable. In the meantime, as long as it doesn't prevent us from implementing something, let's live with the shortcomings of the current implementation.

**Comment by havok2063** [comment]
No more extern packages.  Closing.
