### ISSUE TITLE
can't seem to install marvin?

### ISSUE THREAD

**Issue by malmolina** [sdss/marvin#215]
I cannot seem to correctly import marvin onto my computer. I tried using Anaconda and got the following message: 
>>> import marvin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/malm/anaconda/lib/python2.7/site-packages/marvin/__init__.py", line 26, in <module>
    from marvin import extern
  File "/Users/malm/anaconda/lib/python2.7/site-packages/marvin/extern/__init__.py", line 31, in <module>
    wtforms_alchemy = _import_module('wtforms_alchemy', 'wtforms-alchemy/')
  File "/Users/malm/anaconda/lib/python2.7/site-packages/marvin/extern/__init__.py", line 20, in _import_module
    return imp.load_module(name, fp, filename, description)
  File "/Users/malm/anaconda/lib/python2.7/site-packages/marvin/extern/wtforms-alchemy/wtforms_alchemy/__init__.py", line 13, in <module>
    from wtforms_components import DateRange, Email, TimeRange
ImportError: No module named wtforms_components
-----------------------------------------------

Then I tried using Ureka and got the following message: 

> In [1]: import marvin
> INFO: No release version set. Setting default to MPL-5
> WARNING: path /Users/malm/sas/mangawork/manga/spectro/redux/v2_0_1/drpall-v2_0_1.fits
>          cannot be found. Setting drpall to None.
> 
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-1-c829bc588ff7> in <module>()
> ----> 1 import marvin
> 
> /Users/malm/Ureka/variants/common/lib/python2.7/site-packages/sdss_marvin-2.1.3dev0-py2.7.egg/marvin/__init__.pyc in <module>()
>     465 
>     466 # Inits the URL Route Map
> --> 467 from marvin.api.api import Interaction
>     468 config.sasurl = 'https://api.sdss.org/marvin2/'
>     469 # config.sasurl = 'http://24147588.ngrok.io/marvin2/'  # this is a temporary measure REMOVE THIS
> 
> /Users/malm/Ureka/variants/common/lib/python2.7/site-packages/sdss_marvin-2.1.3dev0-py2.7.egg/marvin/api/__init__.py in <module>()
>       8 from marvin.core.exceptions import MarvinError
>       9 from marvin.utils.dap.datamodel import dap_datamodel as dm
> ---> 10 from marvin.tools.maps import _get_bintemps
>      11 from webargs import fields, validate, ValidationError
>      12 from webargs.flaskparser import use_args, use_kwargs, parser
> 
> /Users/malm/Ureka/variants/common/lib/python2.7/site-packages/sdss_marvin-2.1.3dev0-py2.7.egg/marvin/tools/maps.py in <module>()
>      24 import marvin.core.core
>      25 import marvin.core.exceptions
> ---> 26 import marvin.tools.cube
>      27 import marvin.tools.map
>      28 import marvin.tools.spaxel
> 
> /Users/malm/Ureka/variants/common/lib/python2.7/site-packages/sdss_marvin-2.1.3dev0-py2.7.egg/marvin/tools/cube.py in <module>()
>      17 import marvin
>      18 import marvin.core.exceptions
> ---> 19 import marvin.tools.spaxel
>      20 import marvin.tools.maps
>      21 import marvin.utils.general.general
> 
> /Users/malm/Ureka/variants/common/lib/python2.7/site-packages/sdss_marvin-2.1.3dev0-py2.7.egg/marvin/tools/spaxel.py in <module>()
>      30 from marvin.core.exceptions import MarvinError, MarvinUserWarning, MarvinBreadCrumb
>      31 from marvin.tools.analysis_props import AnalysisProperty, DictOfProperties
> ---> 32 from marvin.tools.spectrum import Spectrum
>      33 
>      34 breadcrumb = MarvinBreadCrumb()
> 
> /Users/malm/Ureka/variants/common/lib/python2.7/site-packages/sdss_marvin-2.1.3dev0-py2.7.egg/marvin/tools/spectrum.py in <module>()
>      20     import seaborn as sns
>      21 else:
> ---> 22     plt.style.use('seaborn-darkgrid')
>      23 
>      24 
> 
> AttributeError: 'module' object has no attribute 'style'

Do you have any idea what I am doing wrong?

**Comment by bretthandrews** [comment]
Hi! Thanks for reporting your error!

I just tried installing Marvin myself in clean virtual environments using Python 2.7 and 3.6. I couldn't recreate your error, so your problem isn't due to a new bug that we recently introduced. We'll need to take a closer look into the exact versions of the packages that you have installed. I suspect that the very last error is caused by an older version of Matplotlib not having styles. Would you mind checking with:
`import matplotlib`
`matplotlib.__version__`

**Comment by malmolina** [comment]
Yeah I do have an older version of Matplotlib, 1.3.1.

Is there a specific version of Matplotlib I should upgrade to so that Marvin will run properly?

**Comment by bretthandrews** [comment]
I upgraded to matplotlib 2.0 a few weeks ago and really like it. They made a bunch of major changes, though, including the default colors and settings. If you need to keep those, then I believe that the last 1.x version is 1.5

**Comment by malmolina** [comment]
I'm thinking both my ureka and anaconda versions of python are outdated to the point of making modern code difficult to deal with. Would you happen to know if I can run marvin in a virtual environment or should I try to reinstall Anaconda?

**Comment by malmolina** [comment]
Nevermind, I figured it out! I just had to completely uninstall and reinstall Anaconda. My version was several years old, but the newest Anaconda version does allow me to successfully run Marvin.

**Comment by bretthandrews** [comment]
Terrific!
