### ISSUE TITLE
mangaid2plateifu error in MapSpecView 

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#216]
For mangaid =  1-218280 (plateifu = 8942-12702)

1. Clicked on Map/SpecView button
2. Error message appeared (see below)
3. But then spectrum and maps appeared after a second
4. Page also shows a plate-ifu (8942-12702) at the top.

Note: mangaid is wrong.

`MarvinError: mangaid2plateifu was not able to find a plate-ifu for mangaid=1-558296 either local or remotely.`

When I tried to reproduce the error, I got the same error, but a different incorrect mangaid:

`MarvinError: mangaid2plateifu was not able to find a plate-ifu for mangaid=4444-0000 either local or remotely.`

**Comment by bretthandrews** [comment]
When I tried it in Firefox, I get this error:

`MarvinError: Could not retrieve cube for plate-ifu 8937-3701: No Results Found: No row was found for one(). `

This galaxy is 8942-12702.

**Comment by bretthandrews** [comment]
Safari has a different version:
`MarvinError: Could not retrieve cube for plate-ifu 8937-3701: No Results Found: No row was found for one().`

**Comment by yanrenbin** [comment]
I encountered this issue as well. When searching for 7991-12702. It reports: "MarvinError: mangaid2plateifu was not able to find a plate-ifu for mangaid=1-377875 either local or remotely.. " This mangaid is different from the mangaid displayed near the top of the page, which is "1-24145".

**Comment by bretthandrews** [comment]
@yanrenbin: thanks for reporting your run-in with this bug! This is a really weird bug because it is giving us random outputs.

I am trying to reproduce this bug locally, and I got one of the error modes:
1. entered 7443-12701 in galaxy search box
2. Got a ```raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Undefined is not JSON serializable``` (because I don't have 7443-12701 locally)
3. I then searched for 8485-1901 (which I do have locally) and then clicked on MapSpecView. The spectrum and maps displayed correctly with this error message:
`MarvinError: Could not retrieve cube for plate-ifu 7443-12701: No Results Found: No row was found for one()`

So perhaps the browser or db cached the last search?

**Comment by havok2063** [comment]
Can you try some browser tests?   Do these errors occur right away from a fresh browser?  Once the errors occur, do they continue happening?  Once they happen, do they happen again if you close and start a fresh browser?   This doesn't seem *just* like a browser cache issue.  

I don't think there's any db cache happening here.  If there is then I think we should see the same problem with the Tools.  Do we?

**Comment by bretthandrews** [comment]
1. entered 7443-12701 in galaxy search box
2. Got a `raise TypeError(repr(o) + " is not JSON serializable") TypeError: Undefined is not JSON serializable` (because I don't have 7443-12701 locally)
3. **Switched browsers**
4. I then searched for 8485-1901 (which I do have locally) and then clicked on MapSpecView. The spectrum and maps displayed correctly with this error message:
`MarvinError: Could not retrieve cube for plate-ifu 7443-12701: No Results Found: No row was found for one()`

When I search for 8485-1901 in a fresh browser session and a fresh local Marvin web server session, I don't get any errors.

**Comment by kbwestfall** [comment]
Brian told me to add this comment:

I went here:  https://sas.sdss.org/marvin2/galaxy/8461-3702

Clicked on Map/SpecView On

Then I got this error:
MarvinError: Could not retrieve cube for plate-ifu 8081-72103: No Results Found: No row was found for one(). You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new). Fill out a subject and some text describing the error that just occurred. If able, copy and paste the full traceback information into the issue as well.

This happened a few times, but the plate-ifu that could not be retrieved was different:  9719-12704

I tried this on both Firefox and Chrome.

**Comment by havok2063** [comment]
I can't recreate this issue.  I've tested the test marvin site running off master and everything seems fine.  I restarted the 2.1.2 server where these errors originally occurred, and now they no longer occur.  Maybe the server had a weird reboot, or there is some weird caching issue.  Holding off on this for now until we can reproduce it, or we see it again.

**Comment by albireox** [comment]
Closing it as it seems fixed with the server restart even if we don't know the exact reason why. If this happens again we'll reopen the issue.
