### ISSUE TITLE
Error when getting nsa outputs from cube

### ISSUE THREAD

**Issue by goyarzun** [sdss/marvin#219]
Hi guys,

I am getting an error for some galaxies when trying to access the nsa outputs from the cube itself. The are no problems when looking for the outputs in the drp_all file. Example attached. Thanks! 

Grecco

[error.pdf](https://github.com/sdss/marvin/files/914702/error.pdf)

**Comment by bretthandrews** [comment]
In Marvin-web, the Galaxy Properties tab for 7991-1901 returns the following error: `This galaxy has no NSA information available in the MaNGA db.`

**Comment by albireox** [comment]
Hi Grecco,

I think this is fixed now (see #228). Could you please check that everything works for you?

**Comment by goyarzun** [comment]
Hi José,

Yes! It works now. Thank you!

Best,
Grecco

**Comment by albireox** [comment]
Great! Thanks for checking.
