### ISSUE TITLE
Marvin installation in python 3.6

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#227]
pip install sdss-marvin doesn't work in python 3.6, unless you previously pip install sdss-marvin in python 3.5

**Comment by havok2063** [comment]
Can you provide the error message that occurs when you try to install marvin?

**Comment by margudo** [comment]
I cannot, sorry, because I have already fixed it

**Comment by havok2063** [comment]
ok.  :)

**Comment by rspellman** [comment]
I just tried to install marvin on a system with anaconda installed, which is running python 3.6.  I don't know if this helps, but here is the error message I get when trying to install marvin.  It looks like there is problem with the installation of python-memcached:

root@a23407 ~]# pip install sdss-marvin
Collecting sdss-marvin
  Using cached sdss_marvin-2.1.3-py3-none-any.whl
Requirement already satisfied: scipy>=0.18.1 in /usr/local/lib/python3.6/site-packages (from sdss-marvin)
Requirement already satisfied: networkx>=1.11 in /usr/local/lib/python3.6/site-packages (from sdss-marvin)
Collecting flask-profiler>=1.0.1 (from sdss-marvin)
  Using cached flask_profiler-1.4.tar.gz
Collecting WTForms>=2.1 (from sdss-marvin)
  Using cached WTForms-2.1.zip
Requirement already satisfied: pandas>=0.18.1 in /usr/local/lib/python3.6/site-packages (from sdss-marvin)
Requirement already satisfied: numpy>=1.11.2 in /usr/local/lib/python3.6/site-packages (from sdss-marvin)
Requirement already satisfied: astropy>=1.2.1 in /usr/local/lib/python3.6/site-packages (from sdss-marvin)
Collecting blinker>=1.4 (from sdss-marvin)
  Using cached blinker-1.4.tar.gz
Collecting sphinx-bootstrap-theme>=0.4.12 (from sdss-marvin)
  Using cached sphinx-bootstrap-theme-0.5.3.tar.gz
Requirement already satisfied: ipython>=5.0.0 in /usr/local/lib/python3.6/site-packages (from sdss-marvin)
Collecting Flask-FeatureFlags>=0.6 (from sdss-marvin)
  Using cached Flask-FeatureFlags-0.6.tar.gz
Collecting Flask-JSGlue>=0.3 (from sdss-marvin)
  Using cached Flask-JSGlue-0.3.1.tar.gz
Collecting python-memcached>=1.58 (from sdss-marvin)
  Using cached python-memcached-1.58.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-l3pdvhxf/python-memcached/setup.py", line 8, in <module>
        version=get_module_constant('memcache', '__version__'),
      File "/usr/local/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/depends.py", line 164, in get_module_constant
      File "/usr/local/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/depends.py", line 195, in extract_constant
    IndexError: tuple index out of range
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-l3pdvhxf/python-memcached/


The system is CentOS 7, running anaconda 1.6.0, and python and pip currently return:

[root@a23407 ~]# python --version
Python 3.6.0 :: Anaconda 4.3.1 (64-bit)
[root@a23407 ~]# pip --version
pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)

**Comment by rspellman** [comment]
Looks like a problem with setuptools.  I upgraded from 27.2.0 to 36.0.1, and was able to successfully install python-memcached and sdss-marvin.

**Comment by albireox** [comment]
Great! I think we encountered this problem before. Maybe it should be included in the installation FAQ.

Also, `memcache` is one of the (arguably many) libraries that are not needed by a user. It should be removed from the basic `requirements.txt` once we split the requirements in several sections.

**Comment by albireox** [comment]
This seems to be a problem with `memcached` trying to be installed with an old version of `setuptools`. The solution is to manually run `pip install -U setuptools` and then try installing marvin again. Once `setuptools` is up to date, all new marvin upgrades should work fine.
