### ISSUE TITLE
Remove seaborn import and plt.style.use('seaborn-darkgrid')

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#232]
Importing seaborn or setting the matplotlib style as seaborn-darkgrid changes the rcparams for the whole python session, which Francesco and Kyle find aggravating (understandably so).

**Comment by bretthandrews** [comment]
Reintroduce calls to `import seaborn` or `plt.style.use('seaborn-dark-grid')` but reset matplotlibrc defaults by calling `matplotlib.rcdefaults()` after each plotting function.

**Comment by bretthandrews** [comment]
A better solution is using a [temporary styling](http://matplotlib.org/users/customizing.html#temporary-styling) via the matplotlib context manager `with plt.style.context('seaborn-darkgrid'):`

**Comment by kbwestfall** [comment]
Temporary styling sounds like a better approach.  As much as we can, I'd want to have the "session" rcParams and the Marvin rcParams be distinct.  If possible, the functionality I would want is:
 - to have Marvin create plots in it's own style by default
 - be able to overwrite the Marvin style with my own session style and vice versa either by using a kwarg or using some function call
 - to maintain the scope of the session rcParams and Marvin rcParams without having to explicitly run anything in the session that reverts the style after running a Marvin plotting function.

**Comment by bretthandrews** [comment]
For Map plotting, Marvin uses the 'seaborn-darkgrid' style sheet but can accept other ones (e.g., 'ggplot').

```
from marvin.tools.maps import Maps
gal = Maps(plateifu='8485-1901')
ha = gal['emline_gflux_ha_6564']
ha.plot(plt_style='ggplot')
```

It now also restores the session rcParams.
