### ISSUE TITLE
More intelligent parsing of input parameters

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#24]
<a href="https://github.com/albireox"><img src="https://avatars.githubusercontent.com/u/568775?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [albireox](https://github.com/albireox)**
_Thursday Aug 11, 2016 at 23:50 GMT_
_Originally opened as https://github.com/marvin-manga/marvin/issues/27_

----

Currently when one initialises a Cube or Maps it requires defining `filename=`, `plateifu=`, or `mangaid=`. If the keyword is ignored, there should be enough information in the input string for Marvin to decide whether it's a file path, a mangaid, or a plateifu and act accordingly.

**Comment by havok2063** [comment]
Implemented in MPL6 release.
