### ISSUE TITLE
Rename Spaxel and Bin attribute model_flux as model_input_flux

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#246]
The `model_flux` attribute of Spaxel and Bin is spectrum that the model fit (which could be a binned flux) and NOT the model fit spectrum (which is just `model`), which confused me and I assume would be confusing to users, too.

I suggest renaming this attribute as`model_input_flux` but I am open to better ideas.

**Comment by albireox** [comment]
Yes, I agree this is confusing. We have changes this a couple times so it would be good to agree on some definitive names.

Right now the attribute names are selected to match the extension names in the FITS files. In the logcube file, flux is the input flux, which is a bit confusing as well.. Maybe we should consider changing the DAP datamodel for clarity.

I like your suggestion of `model_input_flux`. On the other hand, given that a spaxel with modelcube attributes is, on default mode, loaded with the original spectrum, we could arguably not include the input model flux and access it as `spaxel.spectrum`.

Thoguhts?

**Comment by albireox** [comment]
Done but, as agreed in Pittsburg, I'm calling it `binned_flux`. Also

`model -> full_fit`
`emline -> emline_fit`

and the stellar continuum fit is called `stellarcont_fit`.
