### ISSUE TITLE
Add citation text to documentation

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#25]
<a href="https://github.com/albireox"><img src="https://avatars.githubusercontent.com/u/568775?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [albireox](https://github.com/albireox)**
_Saturday Aug 13, 2016 at 18:45 GMT_
_Originally opened as https://github.com/marvin-manga/marvin/issues/29_

----

We should add a LaTeX-ready citation text to the documentation and, eventually, something like [this](https://ipython.org/citing.html) for a potential Marvin paper.

**Comment by albireox** [comment]
<a href="https://github.com/havok2063"><img src="https://avatars.githubusercontent.com/u/1836302?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [havok2063](https://github.com/havok2063)**
_Monday Oct 17, 2016 at 10:01 GMT_

----

Once we move our code to the public repo, we should load it in Zenodo, and get a DOI and a Bibtex link. https://zenodo.org/record/8475.  We can add this to the documentation.

**Comment by albireox** [comment]
<a href="https://github.com/havok2063"><img src="https://avatars.githubusercontent.com/u/1836302?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [havok2063](https://github.com/havok2063)**
_Tuesday Oct 18, 2016 at 14:30 GMT_

----

We should also consider putting our code up on ASCL http://ascl.net/

**Comment by havok2063** [comment]
Done.  See https://zenodo.org/record/166031 for first release.
