### ISSUE TITLE
pip install sdss-marvin should not upgrade matplotlib from v1 to v2 and Marvin should not overwrite matplotlibrc settings

### ISSUE THREAD

**Issue by francbelf** [sdss/marvin#251]
I have re-installed Marvin and I noticed that it upgraded my matplotlib from v1 to v2. While this is not intrinsically bad, I would like to
1. know whether the upgraded is necessary to the marvin functionality.
2. have the pip install ASK ME explicitly whether to upgrade any python packages I already have.

More on the same theme. After I import marvin in python, every plot I make with matplotlib comes out with default setting which I do not recognize (maybe it's the Seaborn style setting?). Some users would have customised their default matplotlib settings and will therefore be even more surprised at this change. 
I found that the command

matplotlib.rcdefaults() 

works for me to restore the default matplotlib plotting style. I suggest that marvin should call this command internally so that the user does not have to include it in its code.

**Comment by havok2063** [comment]
Hi Francesco, 

Thanks for this.  For future reference, if you only want to upgrade Marvin and none of its dependencies, you can use this command `pip install --upgrade --upgrade-strategy only-if-needed sdss-marvin`.   I think this is your best bet regarding pip.  We don't have much control over how pip gets used.   Maybe there are other options we don't know about.  We can try to make it more explicit in the installation instructions on what the different options are for pip.    

Regarding your matplotlib changes, we agree and cross-linking this to existing issue #232.

**Comment by bretthandrews** [comment]
@francbelf I removed the code that changed the matplotlib rcdefaults (via `import seaborn` or `plt.style.use('seaborn-darkgrid')`. However, I don't like the resulting plots, so I'm going to adopt your suggestion of restoring the defaults after each plotting call via `matplotlib.rcdefaults()`

**Comment by francbelf** [comment]
Hi Brett,

Sounds like a good solution!

Thanks,
F.
----------------------------------------------------------------------------
Francesco Belfiore
Astrophysics Group and Kavli Institute for Cosmology,
Cavendish Laboratory,
Cambridge, CB3 0HE,
United Kingdom
&
University of California Santa Cruz,
1156 High Street,
Santa Cruz, CA 95064,
Mailstop: UCO/Lick,
USA

On 3 May 2017, at 07:48, Brett Andrews <notifications@github.com<mailto:notifications@github.com>> wrote:


@francbelf<https://github.com/francbelf> I removed the code that changed the matplotlib rcdefaults (via import seaborn or plt.style.use('seaborn-darkgrid'). However, I don't like the resulting plots, so I'm going to adopt your suggestion of restoring the defaults after each plotting call via matplotlib.rcdefaults()

**Comment by bretthandrews** [comment]
@francbelf instead of restoring to the matplotlib rc defaults, the map plotting code restores to the rc params of the session before the plotting code was called. It can also accept a matplotlib style sheet keyword argument ala:

```
from marvin.tools.maps import Maps
gal = Maps(plateifu='8485-1901')
ha = gal['emline_gflux_ha_6564']
ha.plot(plt_style='ggplot')
```
