### ISSUE TITLE
repeated sdss login in Marvin web

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#265]
This is feedback from Dominika Wylezalek:

''To get the Marvin website show the data for an individual galaxy, one has to re-type the sdss login data two or three times using which is a bit much.''

**Comment by havok2063** [comment]
I think this is an issue with the nginx server and the httpauth we use to authenticate.  Currently we authenticate once for Marvin at sas.sdss.org, and then again once to data.sdss.org.    @joelbrownstein can probably comment more on why this happens, and on possible solutions.  Is there any way to consolidate our logins down to one?

**Comment by havok2063** [comment]
This is no longer an issue.
