### ISSUE TITLE
Galaxy region selection

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#266]
This is a suggestion from Dominika Wylezalek:

''I understand that the following might be hard to implement but it would be very useful if there was an option to select a region in a galaxy and get the average spectrum in that region.''

I think this can be done somehow with the tools, selecting spaxels by coordinates, but I guess this is more similar to the area selection you can do with ds9, where you select a region with your mouse and it returns an average stacked spectra.

**Comment by albireox** [comment]
This is moderately implemented in `Cube.getAperture()` but it was never totally functional, and it may be broken now. I'll give it a try in following weeks.

**Comment by albireox** [comment]
I'm going to close this since #449 correctly implements a method to recover the spaxels within a region. Producing the average spectrum is a planned feature but not something we are addressing right at this time.
