### ISSUE TITLE
Cube flux from file error

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#268]
```
from marvin.tools.cube import Cube
cc = Cube(filename='manga-8485-1901-LOGCUBE.fits.gz')
cc.flux

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-d272fc71a037> in <module>()
----> 1 cc.flux

/Users/andrews/projects/sdss/sas/mangawork/manga/marvin/python/marvin/tools/cube.py in flux(self)
    278     def flux(self):
    279         """Gets the ``FLUX`` data extension."""
--> 280         if not self._flux:
    281             self._flux = self._getExtensionData('FLUX')
    282         return self._flux

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by albireox** [comment]
Good catch. This seems to be a Numpy related problem. For some reason the ``astropy.io.fits`` extensions inherit from Numpy and, with new versions of Numpy, doing `if not self._flux` will raise a comparison error. Replacing those if with `if self._flux is None` fixes the problem. I have done that change in 852127d1f0f68343c88a52700a53a978243b608d.

I'll keep the issue open until we have had a chance to add some tests.

**Comment by bretthandrews** [comment]
I also noticed that `Cube.flux` wasn't behaving like a `np.array` when loaded from a file, but I haven't looked into it in detail.

**Comment by albireox** [comment]
This is indeed fixed and tested for. Closing it and releasing with 2.1.4.
