### ISSUE TITLE
BPT array sizing not compatible

### ISSUE THREAD

**Issue by christinawlindberg** [sdss/marvin#270]
![bpt_error](https://cloud.githubusercontent.com/assets/24800168/26763828/065a9776-490f-11e7-90db-448d9179bb3f.png)

Given that the arrays are all the same sizes, I don't understand why it is giving me an error saying that there's an array of size (32,). If anyone has any idea what's going on or how to fix it, it would be most helpful.

**Comment by havok2063** [comment]
Hi Christina, 

The BPT outputs are boolean mask arrays.  They are arrays that have the same array shape as the original, but are filled with boolean values of True or False.  When you use the sf mask as a mask you are filtering on only the True values.  In other words, you're only selecting the H-alpha flux values within the 2d array that have been classified as star-forming.  In your case, you get 32 spaxels satisfying that condition.

I think you want to select the same spaxels in all your arrays.  Try
`ha_int = haflux.value[sf] * 10 ** (0.4 * ha_dust_ext[sf] * color_excess[sf])`

Cheers,Brian
