### ISSUE TITLE
Problem in dowloading image.

### ISSUE THREAD

**Issue by RomainPaviot** [sdss/marvin#271]
Hi my name is Romain. Me and sebastien are Maria's students at Antofagasta university.  We have a problem in downloading the maps. We are both getting the same errors and we need your help please.

This is the error i have using the getImagesByList function.

"MarvinError: Error with sdss_access rsync.set_stream. AccessError: Return code 10
rsync: failed to connect to dtn01.sdss.org (204.99.128.57): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
.
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well."

Using maps.download() i get the following error : 

"AccessError: Return code 10
rsync: failed to connect to dtn01.sdss.org (204.99.128.57): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]"

We can plot map using python and this is the first problem we got so far. 

We also have a practical question if you don't mind. We are trying to calculate the sersic index in differents bands (halpha, oxygen,nitrogen ect) but to do that we need .fits images. Is there a way to retrieve the different emission lines flux in fits format?

Thanks you for reading this message.
Have a good day,
Regards,

Romain Paviot

**Comment by havok2063** [comment]
Hi Romain

It looks like this is a problem with sdss_access and rsyncing.   We had a similar issue with users in China.  It may be a firewall issue.  Do you know if you're behind a firewall or your institution blocks certain ports and addresses?   @joelbrownstein will have a better idea of what sdss_access is doing here.

**Comment by margudo** [comment]
Hi, 

I'm not sure if we tried this when using a shared phone connection (we had some connection issues in the University). Romain, please try to run it again from another internet connection.

About the second question, what we want to do is using DAP maps, in particular fluxes, in Halpha channel for instance, to run sextractor on it, for example. How could we do it with the Maps function? 

Maria

**Comment by RomainPaviot** [comment]
Yes you were right, it works on others 
connection !!

**Comment by havok2063** [comment]
Oops, sorry I missed your second part.   If you want to grab a specific map, just use the `Maps` object.  

```
# grabs the H-alpha flux map for a galaxy
from marvin.tools.maps import Maps
maps = Maps(plateifu='8485-1901')
haflux = maps['emline_gflux_ha_6564']
```
See how to use a single map here: http://sdss-marvin.readthedocs.io/en/latest/tools/map.html

**Comment by RomainPaviot** [comment]
Thanks you for the answer ! Have a good day !
