### ISSUE TITLE
New search page issue

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#272]
Hi, 
I'm doing this query in the web:

from marvin.tools.query import Query
filter='cube.mangaid = 1-93640'
returnparams=['spaxelprop.emline_gflux_ha_6564']
q = Query(searchfilter=filter, returnparams=returnparams)
r = q.run()

First, the returned value of spaxelprop.emline_gflux_ha_6564 for each spaxel is different than the value in the map (https://sas.sdss.org/test/marvin2/galaxy/1-93640).
And if I run it in python, it doesn't show me the table, not even the first 100 results.

And second, if my query is:

from marvin.tools.query import Query
filter='cube.mangaid = 1-93640'
returnparams=['spaxelprop.x', 'spaxelprop.y', 'spaxelprop.emline_gflux_ha_6564']
q = Query(searchfilter=filter, returnparams=returnparams)
r = q.run()

And I try to run it in python, it doesn't work.

Maria

**Comment by margudo** [comment]
Oh, and the results are duplicated. I'm getting two results for each spaxel, and with different values of Ha fluxes.

**Comment by havok2063** [comment]
Hi, María.  Could you be more specific?  Why doesn't your second query work? What is the error that it returns? 

As for the first query, can you provide some examples of discrepancies between the reported Ha-flux values in given spaxels from query results versus the map display in the web?  And cases where it's duplicated as well?   When you say "it doesn't show me the table, not even the first 100 results", what does it show you?  Does it error out, time out, succeed but return nothing?

**Comment by margudo** [comment]
Ok haha maybe too many things

First, the query 

from marvin.tools.query import Query
filter='cube.mangaid = 1-93640'
returnparams=['spaxelprop.emline_gflux_ha_6564']
q = Query(searchfilter=filter, returnparams=returnparams)
r = q.run()

When I run it in the web, it shows a table with two results for each spaxel (see attached image)

![screenshot from 2017-06-12 16-19-28](https://user-images.githubusercontent.com/7560892/27053390-2c0a1438-4f8b-11e7-85e5-7bbcbcc025a7.png)

As you can see, for example the spaxel (5,33) is duplicated, and if I compare the value of Ha with the one in the map (see figure attached) both values are different.

![screenshot from 2017-06-12 16-23-53](https://user-images.githubusercontent.com/7560892/27053639-f27ee238-4f8b-11e7-8951-ff7557a0c0a9.png)

 When I run the query in python, I get this:

In [3]: from marvin.tools.query import Query
   ...: filter='cube.mangaid = 1-93640'
   ...: returnparams=['spaxelprop.emline_gflux_ha_6564']
   ...: q = Query(searchfilter=filter, returnparams=returnparams)
   ...: r = q.run()
   ...: 
WARNING: No local database found. Cannot perform queries.
WARNING: local mode failed. Trying remote now.
Your parsed filter is: 
cube.mangaid=1-93640
Results contain of a total of 11648, only returning the first 100 results

That's all, nothing happens. So if I do:

In [4]: q.run()
Results contain of a total of 11648, only returning the first 100 results
Out[4]: 
Marvin Results(results=NamedTuple(mangaid='1-93640', plate=8482, plateifu='8482-12703', name='12703', emline_gflux_ha_6564=1.55637931824, x=5, y=33), 
query='SELECT mangadatadb.cube.mangaid AS "cube.mangaid", mangadatadb.cube.plate AS "cube.plate", concat(mangadatadb.cube.plate, \'-\', mangadatadb.ifudesign.name) AS "cube.plateifu", mangadatadb.ifudesign.name AS "ifu.name", mangadapdb.cleanspaxelprop5.emline_gflux_ha_6564 AS "spaxelprop.emline_gflux_ha_6564", mangadapdb.cleanspaxelprop5.x AS "spaxelprop.x", mangadapdb.cleanspaxelprop5.y AS "spaxelprop.y" \nFROM mangadatadb.cube JOIN mangadatadb.ifudesign ON mangadatadb.ifudesign.pk = mangadatadb.cube.ifudesign_pk JOIN mangadapdb.file ON mangadatadb.cube.pk = mangadapdb.file.cube_pk JOIN mangadapdb.cleanspaxelprop5 ON mangadapdb.file.pk = mangadapdb.cleanspaxelprop5.file_pk JOIN mangadatadb.pipeline_info AS drpalias ON drpalias.pk = mangadatadb.cube.pipeline_info_pk JOIN mangadatadb.pipeline_info AS dapalias ON dapalias.pk = mangadapdb.file.pipeline_info_pk \nWHERE mangadatadb.cube.mangaid ILIKE (\'%\' || \'1-93640\' || \'%\') AND drpalias.pk = 25 AND dapalias.pk = 26', 
count=100, 
mode=remote

So I'm not seeing the table.

**Comment by margudo** [comment]
When I run the second query in python:

from marvin.tools.query import Query
filter='cube.mangaid = 1-93640'
returnparams=['spaxelprop.x', 'spaxelprop.y', 'spaxelprop.emline_gflux_ha_6564']
q = Query(searchfilter=filter, returnparams=returnparams)
r = q.run()

I'm getting this error:

MarvinError: Cannot created NamedTuple from remote Results: Encountered duplicate field name: 'spaxelprop_x'.
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.

**Comment by havok2063** [comment]
Ok.  Here we go.  

Regarding your second query, this is because you are asking to return the spaxelprop.x and .y.  For all DAP queries that involve spaxels, these parameters are returned by default so you do not have to worry about them.   Try removing those two parameters from your list of returnparams and it should work.  It shouldn't fail here though and I will change this so Marvin removes them from the list if it finds them and proceeds normally.  

Regarding your first query, by default, all DAP queries will query and return any of the map types.  So it includes all bintypes and templates.  The duplicates you are seeing is for bintype ALL and NRE in that first page.  The maps displayed on the galaxy page are of bintype SPX.  That's why they are different.

If you only want unbinned spaxels, then you also need to specify in your filter "bintype.name == SPX".  

<img width="1665" alt="query_bintypes" src="https://user-images.githubusercontent.com/1836302/27055231-be4260f2-4f91-11e7-9264-8d12af55174d.png">

<img width="1663" alt="query_onlyspx" src="https://user-images.githubusercontent.com/1836302/27055241-c6c57de0-4f91-11e7-9f62-19b0d38cce62.png">

**Comment by havok2063** [comment]
Also for your first query, when you run it in Python with  ```r = q.run()```, the results are stored in an attribute called ```r.results```.    You can check how many results are returned with  ```r.count``` or ```len(r.results)```.    Here is a link that might help.  http://sdss-marvin.readthedocs.io/en/stable/results.html

**Comment by margudo** [comment]
Thanks!
Regarding the second query, is great if you correct that also in the tools. If not it's a bit confusing, the web shows you a python code that is not going to work. I understand where the problem is coming, but somebody that doesn't know python or with low computation skills is not going to use it anymore. 
The same to show the resulted table in python using the suggested code. 

And regarding the duplicated spaxels, I understand that then it's necessary to add the option to select the datacube you want to do the query. 

I will keep testing the page and send future bugs and comments. I haven try the multiple galaxy yet and the view galaxy, looks promising! 

Thanks!

**Comment by havok2063** [comment]
I'm not exactly sure what you mean by  "the web shows you a python code that doesn't work" or "the same to show the resulted table in python".  When I input your exact query in the web, and click ```See how to do it in Python```, I get this
```
from marvin.tools.query import Query
filter='cube.mangaid = 1-93640'
returnparams=['spaxelprop.emline_gflux_ha_6564']
q = Query(searchfilter=filter, returnparams=returnparams)
r = q.run()
```
which does work.  I run it in the terminal and get results.

**Comment by margudo** [comment]
The query works, yes, but I mean that I expect to do that in python and get the table, in the same way I'm getting a table in the web. If I want to see the table I have to run `r.results`, and to know that I have to go to the documentation. I think it should be simpler. 
I expect my comment it's clearer now =)

**Comment by havok2063** [comment]
I definitely agree that things should be more clear.  The query tools are more versatile than the web and a query has to return as similar a structure when running in local mode and remote mode.  That's why it returns a list of tuples, but from there, you can do much more with the results.  If you want a table similar to the one on the web, you can run this to convert the results into an Astropy Table. 

```
r = q.run()
mytable = r.toTable()
```

**Comment by havok2063** [comment]
I have fixed the issues here with returning parameters.  The default now for any DAP queries is to return the spaxel coordinates x and y, the bintype, and template.  If any of these parameters are also included as return parameters, we clean up the list so only one entry is included.  This is pushed to the pytest branch and will be included in the next patch release.
