### ISSUE TITLE
ha.value bug

### ISSUE THREAD

**Issue by RomainPaviot** [sdss/marvin#273]
Hello ! 
I just wanted to report a little bug which occurs with some h-alpha.
The h-alpha.value flux for some spaxels are totally different from the one of the h-alpha.plot()

For example : 
Plateifu : 8466-1902
ha.value[27][13]  = 75805 while the value should be zero

Plateifu : 8592-9101
ha.value[24][8] = 22481 while the value should be 1.73 

I can give all the plateifu that i have found with this problem if needed.
Have a good day !

**Comment by havok2063** [comment]
Thanks, Romain.  We'll take a look.  This could be a new problem with our plot mechanism since that recently changed.

**Comment by bretthandrews** [comment]
Both of the spaxels that you mentioned have been flagged as having an Ha flux that is "UNRELIABLE". By default, Marvin displays UNRELIABLE (and DONOTUSE and low S/N spaxels) as hatched.

For 8466-1902:
ha.value[27][13] == 75805.6171875
ha.mask[27][13] == 32 

This bitmask (32 == 2**5) means the DAP flagged the Ha flux in this spaxel as UNRELIABLE. You can see the description of the MANGA_DAPPIXMASK bitmasks [here](https://trac.sdss.org/wiki/MANGA/TRM/TRM_MPL-5/DAPMetaData#MANGA_DAPPIXMASK). The UNRELIABLE flag is described in more detail [here](https://trac.sdss.org/wiki/MANGA/TRM/TRM_MPL-5/DAPMetaData#TheUNRELIABLEflag).

For a more general intro to using bitmasks, check out [this tutorial](http://sdss-marvin.readthedocs.io/en/latest/tutorials/bitmasks.html) on the Marvin docs.
