### ISSUE TITLE
Ticks for log normalized colorbar

### ISSUE THREAD

**Issue by aleksds** [sdss/marvin#277]
Using code like [this](https://github.com/aleksds/bates_galaxies_lab/blob/master/manga/bdkr1_marvin_subplot.py), we have noticed that the ticks for log normalized colorbars have issues when the cbrange is larger than an order of magnitude.  This appears to be related to the _log_cbticks() function in [colorbar.py](https://github.com/sdss/marvin/blob/master/python/marvin/utils/plot/colorbar.py) and the number of ticks that get defined.

**Comment by havok2063** [comment]
Thanks, Aleks.  We'll take a look at this.

**Comment by bretthandrews** [comment]
@aleksds thanks for pointing this out! It required a pretty simple fix, which will be included in the next patch release.
