### ISSUE TITLE
marvin_test_if decorator breaks in python 2.7

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#278]
The marvin_test_if breaks when applied to methods in Python 2.7.  It returns the error `TypeError: test_save_and_restore() takes exactly 3 arguments (1 given)`.  It seems to work ok in Python 3.5

Example in `tools/test_map.py::TestMap`

```
    @marvin_test_if(mark='skip', map_=dict(data_origin=['db']))
    def test_save_and_restore(self, temp_scratch, map_):

        fout = temp_scratch.join('test_map.mpf')
        map_.save(str(fout))
        assert fout.check() is True

        map_restored = Map.restore(str(fout), delete=True)
        assert tuple(map_.shape) == tuple(map_restored.shape)
```

**Comment by albireox** [comment]
Fixed as of 2.1.4. It works with functions/methods, classes, and in parametrised tests.
