### ISSUE TITLE
DRP version v1_5_4 not found in lookup table. No associated MPL version.

### ISSUE THREAD

**Issue by izkgao** [sdss/marvin#285]
I tried to deal with a Cube file, but this error occurred.
```
---------------------------------------------------------------------------
MarvinError                               Traceback (most recent call last)
<ipython-input-14-3bce59e79e5a> in <module>()
      1 from marvin.tools.cube import Cube
----> 2 cc = Cube(filename='/home/isaac/manga/manga-7443-12703-LOGCUBE.fits')

/home/isaac/anaconda2/lib/python2.7/site-packages/marvin/tools/cube.pyc in __init__(self, *args, **kwargs)
     94 
     95         if self.data_origin == 'file':
---> 96             self._load_cube_from_file(data=self.data)
     97         elif self.data_origin == 'db':
     98             self._load_cube_from_db(data=self.data)

/home/isaac/anaconda2/lib/python2.7/site-packages/marvin/tools/cube.pyc in _load_cube_from_file(self, data)
    178         file_drpver = 'v1_5_1' if file_drpver == 'v1_5_0' else file_drpver
    179 
--> 180         file_ver = marvin.config.lookUpRelease(file_drpver)
    181         assert file_ver is not None, 'cannot find file version.'
    182 

/home/isaac/anaconda2/lib/python2.7/site-packages/marvin/__init__.pyc in lookUpRelease(self, drpver)
    377             raise MarvinError('DRP version {0} not found in lookup table. '
    378                               'No associated MPL version. Should one be added?  '
--> 379                               'Check for typos.'.format(drpver))
    380 
    381         return release

MarvinError: DRP version v1_5_4 not found in lookup table. No associated MPL version. Should one be added?  Check for typos..
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.

```
Set the release to MPL-4, but the error still occurred.
```
from marvin import config
config.setRelease('MPL-4')
```
drpall-v1_5_4.fits has been placed under this directory.
`/home/isaac/sas/mangawork/manga/spectro/redux/v1_5_4`

I tried to rename the directory and the file name to v1_5_1, but failed to fix it.

**Comment by albireox** [comment]
Hi,

At this moment Marvin only supports MPL-4 (v1_5_1) and MPL-5 (v2_0_1). A file from any other version will fail with that error. This was a conscious decision on our part given that we want to be sure Marvin can actually handle the file you are using. Also, given that the DB and API don't have other versions apart from MPL-4 and -5, we wanted to maintain the symmetry also for files.

Is there a specific reason why you are using v1_5_4? Could you use v1_5_1 or, better, MPL-5 (v2_0_1)?

**Comment by izkgao** [comment]
Hi,

The file I downloaded is from the link below.
`https://data.sdss.org/sas/dr13/manga/spectro/redux/v1_5_4/`
After your comment, I tried the file from dr14 (see the link below) but still got the error with different DRP version.
`https://data.sdss.org/sas/dr14/manga/spectro/redux/v2_1_2/`

```
WARNING: FITSFixedWarning: PLATEID = 7443 / Current plate 
a string value was expected. []
---------------------------------------------------------------------------
MarvinError                               Traceback (most recent call last)
<ipython-input-3-a20bd755ca40> in <module>()
      1 from marvin.tools.cube import Cube
----> 2 cc = Cube(filename='/home/isaac/manga/manga-7443-12703-LOGCUBE_dr14.fits.gz')

/home/isaac/anaconda2/lib/python2.7/site-packages/marvin/tools/cube.pyc in __init__(self, *args, **kwargs)
     94 
     95         if self.data_origin == 'file':
---> 96             self._load_cube_from_file(data=self.data)
     97         elif self.data_origin == 'db':
     98             self._load_cube_from_db(data=self.data)

/home/isaac/anaconda2/lib/python2.7/site-packages/marvin/tools/cube.pyc in _load_cube_from_file(self, data)
    178         file_drpver = 'v1_5_1' if file_drpver == 'v1_5_0' else file_drpver
    179 
--> 180         file_ver = marvin.config.lookUpRelease(file_drpver)
    181         assert file_ver is not None, 'cannot find file version.'
    182 

/home/isaac/anaconda2/lib/python2.7/site-packages/marvin/__init__.pyc in lookUpRelease(self, drpver)
    377             raise MarvinError('DRP version {0} not found in lookup table. '
    378                               'No associated MPL version. Should one be added?  '
--> 379                               'Check for typos.'.format(drpver))
    380 
    381         return release

MarvinError: DRP version v2_1_2 not found in lookup table. No associated MPL version. Should one be added?  Check for typos..
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.
```
It seems that the SAS show only two data release (DR13. DR14) with two DRP version v1_5_4 or v2_1_2.
I have no idea that where I can download the Cube files with DRP version v1_5_1 or v2_0_1.

**Comment by albireox** [comment]
That's correct. Right now we only provide access to MPL-4 and -5, not to DR13 and 14, since they don't include DAP data. That is something we should fix, but right now it is not an option.

You can download v1_5_1 and v2_0_1 from https://data.sdss.org/sas/mangawork/manga/spectro/redux/. The user and passwords are the normal credentials for SDSS, the ones you use for your netrc.

**Comment by izkgao** [comment]
The webmaster of SDSS told me that the URL is for SDSS collaborators only. But I'm not one of them. Maybe the only way is to deal with the Cube files by myself.

Thanks albireox for your help!

**Comment by havok2063** [comment]
Unfortunately, right now Marvin is only usable for members within the SDSS collaboration.  We are planning on releasing Marvin publicly for use outside the collaboration for DR15, in July 2018.  It's far off, but not so far off.  Marvin should be usable with any of the public data releases at that point.

**Comment by albireox** [comment]
Yes, unfortunately that webpage is collaboration only. I think there is a point in allowing users to open any version of cube, and I have open issue #288 to deal with that possibility. For now I'm going to close this as wontfix, but stay tuned for developments on that issue. Thanks for your comment!
