### ISSUE TITLE
Use fuzzywuzzy in DAP datamodel

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#287]
I think we can use fuzzywuzzy for the DAP datamodel, and for things such as selecting a map. Instead of having to write exactly `emline_gflux_ha_6564`, a simple `gflux ha` would probably suffice. We should be careful to make sure we don't produce false positives.

**Comment by havok2063** [comment]
fuzzywuzzy has different methods of extraction (of best results) and comparison algorithms.  I think it should be fairly straightforward to make it fairly robust to false positives.  I took a stab at a custom method with the `query_utils`.  We can probably expand on that and improve it.

**Comment by albireox** [comment]
Done. The scorer seems to produce good, reliable results, but more tuning may be needed.
