### ISSUE TITLE
api internal server errors of 500 return more info

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#29]
<a href="https://github.com/havok2063"><img src="https://avatars.githubusercontent.com/u/1836302?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [havok2063](https://github.com/havok2063)**
_Tuesday Oct 04, 2016 at 20:57 GMT_
_Originally opened as https://github.com/marvin-manga/marvin/issues/56_

----

API routes that crash on the server side return with a 500 status code, internal server error.  We should add more detail here.

**Comment by havok2063** [comment]
I think I've fixed this now, however there is no general way to add more info for all API methods we write.  We will have to do this for every call we write, and modify this existing ones manually.  Unless someone can come up with a better idea.  There is a traceback attribute now inside the configs that one can access.  This is auto-passed back and forth during any API call, and is default to None.  If you want to capture and return a traceback you need to something like 

```
        from marvin.utils.db import get_traceback
        try:
           some code
        except MarvinError as e:
            self.results['error'] = str(e)
            self.results['traceback'] = get_traceback(asstring=True)
```
See the cube_query inside marvin/api/query.py for an example.   This will stick the traceback in a hidden attribute on Marvin config called _traceback.  This attribute will always hold the last traceback until another one is captured and passed.
