### ISSUE TITLE
MPL-5 vs MPL-4 map plot center offset

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#295]
There is a difference between the maps plotted in MPL-4 and MPL-5 for galaxies that have the IFU center offset from the galaxy center, e.g. 7443-12701.  I suspect this might be because the definition of the named coordinates changed between MPL-4 and MPL-5, but I couldn't find anything like that in the map plotting utilities.   Maybe this is already expected and ok behavior and I just forgot. 

```
c = Cube(plateifu='7443-12701')
maps = c.getMaps()
data = maps.getMap('stellar_vel')
data.plot()
```

MPL-4
![mpl4_7443-12701](https://user-images.githubusercontent.com/1836302/30986876-fbc0501c-a462-11e7-9cd2-8c7a814bf36f.png)

MPL-5
![mpl5_7443-12701](https://user-images.githubusercontent.com/1836302/30986888-082cfbd4-a463-11e7-9619-7076d8ef485c.png)

**Comment by bretthandrews** [comment]
Since we aren't recommending that anyone use the MPL-4 DAP maps and this only affects a handful of galaxies on the commissioning plates, I'm going to close this issue.
