### ISSUE TITLE
Removing colorbar in map plotting

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#296]
@KateRowlands @havok2063 here's how to remove the colorbar from a heatmap:

```
from marvin.tools.maps import Maps
maps = Maps(plateifu='8485-1901')
ha = maps['emline_gflux_ha_6564']
fig, ax, cb = ha.plot(return_cb=True)
cb.remove()

# might also require:
# import matplotlib.pyplot as plt
# plt.draw()  # plt.show()
```

@KateRowlands would you mind describing your use case?

**Comment by KateRowlands** [comment]
Hi Brett,

Many thanks for looking into this. Your suggestion works great.

I'm using a mapplot.plot with a custom map and mask to make a multi-panel plot of spaxel classifications (see attached [Example_PCA.pdf](https://github.com/sdss/marvin/files/1380234/Example_PCA.pdf)
), and the plot is a bit crowded if I use a colour bar so I prefer to remove it.

**Comment by bretthandrews** [comment]
Gotcha! You could make one colorbar if the colors mean the same thing in each panel. Here's an example of a categorical colormap (if you haven't seen it already): http://sdss-marvin.readthedocs.io/en/latest/tutorials/plotting.html#qualitative-colorbar-new-in-version-2-1-4
