### ISSUE TITLE
Improved marvin import time

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#299]
Just doing `import marvin` takes some time. We should review what happens when we import marvin, what needs to happens on import, and what can be delayed.

**Comment by albireox** [comment]
Actually it seems this is only slow when you have a DB and Marvin imports the model classes. Otherwise it is fast. This warning shows up if you try to import Marvin without a DB

```python
WARNING: This declarative base already contains a class with the same class name and
         module name as marvin.db.models.SampleModelClasses.MangaTarget, and
         will be replaced in the string-lookup table.
```

which seems to indicate that Marvin is still trying to import the model classes.

**Comment by bretthandrews** [comment]
Perhaps we should remove that warning.

If it's too difficult to shave off import time for devs, then so be it.

**Comment by havok2063** [comment]
While annoying, I think the devs can deal with a slightly longer import time.   Just imagine we're getting the super secret important stuff. :)
