### ISSUE TITLE
Marvin install problem on MacOs Sierra

### ISSUE THREAD

**Issue by francbelf** [sdss/marvin#301]
I tried to install Marvin on a new machine running MacOS Sierra and Anaconda. I get the following error message

    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-2.7
    creating build/lib.macosx-10.9-x86_64-2.7/Levenshtein
    copying Levenshtein/__init__.py -> build/lib.macosx-10.9-x86_64-2.7/Levenshtein
    copying Levenshtein/StringMatcher.py -> build/lib.macosx-10.9-x86_64-2.7/Levenshtein
    running egg_info
    writing requirements to python_Levenshtein.egg-info/requires.txt
    writing python_Levenshtein.egg-info/PKG-INFO
    writing namespace_packages to python_Levenshtein.egg-info/namespace_packages.txt
    writing top-level names to python_Levenshtein.egg-info/top_level.txt
    writing dependency_links to python_Levenshtein.egg-info/dependency_links.txt
    writing entry points to python_Levenshtein.egg-info/entry_points.txt
    reading manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*pyc' found anywhere in distribution
    warning: no previously-included files matching '*so' found anywhere in distribution
    warning: no previously-included files matching '.project' found anywhere in distribution
    warning: no previously-included files matching '.pydevproject' found anywhere in distribution
    writing manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
    copying Levenshtein/_levenshtein.c -> build/lib.macosx-10.9-x86_64-2.7/Levenshtein
    copying Levenshtein/_levenshtein.h -> build/lib.macosx-10.9-x86_64-2.7/Levenshtein
    running build_ext
    building 'Levenshtein._levenshtein' extension
    creating build/temp.macosx-10.9-x86_64-2.7
    creating build/temp.macosx-10.9-x86_64-2.7/Levenshtein
    /usr/bin/clang -fno-strict-aliasing -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -I/Applications/anaconda2/include/python2.7 -c Levenshtein/_levenshtein.c -o build/temp.macosx-10.9-x86_64-2.7/Levenshtein/_levenshtein.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Applications/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-bRLimx/python-Levenshtein/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-vbj0yN-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-bRLimx/python-Levenshtein/

**Comment by albireox** [comment]
I don't use Anaconda so I cannot completely reproduce, but it seems you don't have the Mac command line tools needed to compile Levenshtein, which is a Marvin dependency. Can you try running

`xcode-select --install`

following the instructions, and then trying to install Marvin again?

**Comment by francbelf** [comment]
I can confirm that this solves the problem

**Comment by albireox** [comment]
Cool! Closing.
