### ISSUE TITLE
Old pyc files after upgrading marvin

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#306]
Some people in Campeche have had problem when upgrading marvin on a previous installation, with old `.pyc` files not being deleted and producing unexpected problems.

**Comment by bretthandrews** [comment]
Are they bad magic number errors? If so, I was doing this to fix the problem:
`find . -name '*.pyc' -delete`

**Comment by albireox** [comment]
I think this is not a Marvin problem so we can close.
