### ISSUE TITLE
get_BPT with show_plot=False returns wrong number of parameters

### ISSUE THREAD

**Issue by KateRowlands** [sdss/marvin#307]
In the documentation for get_BPT usage with show_plot=False says

masks, fig = maps.get_bpt(show_plot=False)

but this produces the following error:

ValueError                                Traceback (most recent call last)
<ipython-input-34-bc050e651bbe> in <module>()
      1 maps = Maps(plateifu='8485-1901')
----> 2 masks, figs = maps.get_bpt(use_oi=False, show_plot=False)

ValueError: too many values to unpack

Example code:
maps = Maps(plateifu='8485-1901')
masks, figs = maps.get_bpt(use_oi=False, show_plot=False)

This code works:

masks = maps.get_bpt(use_oi=False, show_plot=False)

Also, in a Jupyter notebook, the plot is still show when show_plot=False

**Comment by havok2063** [comment]
Thanks, Kate.  We'll have a look and fix this before we push an MPL-6 release.

**Comment by havok2063** [comment]
I think this is fixed.
