### ISSUE TITLE
Replacement code for getAperture

### ISSUE THREAD

**Issue by KateRowlands** [sdss/marvin#315]
Here is some example code I wrote to replace the functionality of getAperture, perhaps it is useful for Marvin.

https://gist.github.com/KateRowlands/f7964da6c2e82682c48925f93966fbe7

**Comment by havok2063** [comment]
Thanks, Kate.  This is helpful.  We'll look at adding this in as contributed code.

**Comment by albireox** [comment]
Related to #6
