### ISSUE TITLE
Workaround for getting marvin to work in windows

### ISSUE THREAD

**Issue by cvambarish** [sdss/marvin#316]
I have a windows 10 machine and had some problems installing marvin. Here's what I did to get it working.

For installation, I used pip3. Atleast in my machine pip by default was referring to Python 2.7. With Python 3.5 the installation was much smoother.

And secondly, since Marvin expects the .netrc file in the home directory. I used the following code snippet before the main python file.

`
import os;
os.environ['HOME']="<Path to directory you want as your MarvinHome>"
os.environ['SAS_BASE_DIR']="MarvinHome\sas"
`

With this, I am able to run Marvin just fine in Windows. It does not download cubes/maps of course, since the forward slashes (/) are harcoded into the path. If we use 'os' for forming the path, I think downloads should be possible too as far as I could see.

Cheers!
Ambarish

**Comment by havok2063** [comment]
Hi Ambarish.  This is very helpful and useful information.  Thanks for doing a lot of the hard work here.  Marvin isn't very Windows compatible out of the box.  We'll add this to a new page in the documentation to let others know.  If you encounter any other Windows oddities, please let us know.   The hard-coded slashes is definitely something we need to fix, probably in sdss-access, but shouldn't be too difficult.

**Comment by havok2063** [comment]
This has been resolved with PR #652 and merged in.  It will be available in the next release of Marvin.
