### ISSUE TITLE
marvin-web: switching to Galaxy Properties tab before MapSpec view tab has loaded

### ISSUE THREAD

**Issue by zpace** [sdss/marvin#319]
On a galaxy's page in marvin-web, if you activate MapSpec view and then switch immediately to the "Galaxy Properties" tab, when you switch back to MapSpec view, the interactive plots do not load (page must be refreshed)

**Comment by havok2063** [comment]
This was an issue where html5 canvases rendered in hidden divs will have zero size and not be drawn until the page is resized.  I've fixed this by adding an event handler when the user clicks the `MapSpec View` tab which forces a resize of the `OpenLayers` map and `Dygraph` spectra after 10 milliseconds.
