### ISSUE TITLE
Remove 'dev' and 'web' setup switches

### ISSUE THREAD

**Issue by hainest** [sdss/marvin#322]
06f12739 introduced the setup switches to configure the dev and web builds. However, the corresponding requirements files contain pip commands that can't be passed to `setup` via `install_requires` as it only understands package names and versions. The current marvin dev documentation instructs the user to import the requirements files using pip directly, so the 'dev' and 'web' switches appear to be undocumented and could be removed without worry.

Even after the removal of these switches, the setup process currently runs afoul of the [canonical example](https://caremad.io/posts/2013/07/setup-vs-requirement/) of crossing the separate concerns of the requirements files and the `install_requires` mechanism. Namely, in that concrete packages are being fed to `setup` where abstract ones should be used. The cited website suggests a solution. However, I will leave that for a larger discussion, but would be happy to help work to resolve this.

**Comment by havok2063** [comment]
I have removed the setup switches for `dev` and `web` builds in the latest commit, ef4201f, on the `feedback` branch.  I think you're right in that we don't really need them.  

As for your second point, I'm going to leave this as is for now.  I think we mostly got it working but never quite in the proper way and just left it.  I feel like I read about a new pythonic way of handling packaging and requirements that simplified setup and the need for req.txt files, but I couldn't recall exactly where I saw this, and 5 minutes of googling turned up nothing.  So maybe I was dreaming.  If you want to take a stab at refactoring it in a PR, feel free.

**Comment by albireox** [comment]
Regarding the concrete vs abstract packages, this doesn't seem to be something people completely agree upon. [This site](https://packaging.python.org/discussions/install-requires-vs-requirements/), which seems quite "official", recommends providing bounds on the `install_requires` packages.

In particular, if I understand it correctly, pip does not use `requirements.txt` at all (unless you do a `pip install -r`) but uses `install_requires`. It makes sense to me that in that case you want the versions in `install_requires` to be bounded.

**Comment by havok2063** [comment]
This is no longer relevant with the merge of #714.  Closing.
