### ISSUE TITLE
 Axis labels incorrectly labelled as 'spaxel' in mapplot.set_extent when sky_coords=True

### ISSUE THREAD

**Issue by KateRowlands** [sdss/marvin#326]
Axis labels incorrectly labelled as 'spaxel' - should be 'arcsec' in mapplot.set_extent when sky_coords=True

**Comment by bretthandrews** [comment]
`mapplot.set_extent` is now an internal function. To use sky coordinates, do the following:
```
from marvin.tools.maps import Maps
maps = Maps(plateifu='8485-1901')
ha = maps['emline_gflux_ha_6564']
ha.plot(sky_coords=True)
```
When the `sky_coords` keyword is used, the axis labels are correct.
