### ISSUE TITLE
Custom local SAS

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#328]
I'm trying to download rss datacubes and getting errors. It seems this comes from getting a KeyError: ‘SAS_BASE_DIR’

>>> import os
>>> print(os.environ['SAS_BASE_DIR'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mamen/anaconda3/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'SAS_BASE_DIR'

I have a MANGA_SPECTRO_REDUX and MANGA_SPECTRO_ANALYSIS defined in my bashrc for the DAP, but it is not recognized by Marvin.

**Comment by havok2063** [comment]
Marvin expects (and needs) a SAS_BASE_DIR environment variable.  If you don't have one it is supposed to set one for you.  Can you provide an example of what you are doing and the full traceback?

**Comment by margudo** [comment]
Fixed!
I had a mistake in my path. 
Sorry, my paths are paths to nowhere, it's a completely disaster.
I will deal a bit more with this kind of things before creating an issue.

**Comment by havok2063** [comment]
Ok.  That was easy.
