### ISSUE TITLE
get_bpt documentation bug

### ISSUE THREAD

**Issue by KateRowlands** [sdss/marvin#333]
There are several instances in the get_bpt documentation (http://sdss-marvin.readthedocs.io/en/latest/tools/bpt.html?highlight=bpt) where

masks, fig = maps.get_bpt()

throws this error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-116-71db88f5f076> in <module>()
----> 1 masks, fig = maps.get_bpt()

ValueError: too many values to unpack (expected 2)

The code should be

masks, fig, axes = maps.get_bpt()

**Comment by KateRowlands** [comment]
It would also be good to change the example used in the documentation from 8485-1901 to something else, because it doesn't have any star-forming spaxels and it crashes for some examples because of this.

**Comment by havok2063** [comment]
Updated the docs regarding the unpacked values.
