### ISSUE TITLE
get_bpt documentation bug -  spaxel.properties syntax changed

### ISSUE THREAD

**Issue by KateRowlands** [sdss/marvin#337]
In one of the examples it says 
spaxel.properties['emline_sew_ha_6564']

but this should be 
spaxel.emline_gew_ha_6564

**Comment by havok2063** [comment]
@KateRowlands in MPL-5 `emline_sew_ha_6564` is a valid property.  In MPL-6, both `emline_sew` and `emline_gew` are valid properties.  I think this ok.  Closing this.
