### ISSUE TITLE
API and web timeouts

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#34]
<a href="https://github.com/havok2063"><img src="https://avatars.githubusercontent.com/u/1836302?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [havok2063](https://github.com/havok2063)**
_Friday Oct 07, 2016 at 18:59 GMT_
_Originally opened as https://github.com/marvin-manga/marvin/issues/71_

----

We should better control for timeouts with the API calls to the server.  And on the web.  We can implement timeouts in requests, which gives us a bit more control on when and what we return to the user.  Long term we need to assess why the server (nginx, postgres, flask) is timing out on queries and web page loads.  

We have already adjusted some timeout on the Nginx side per this page
[nginx timeouts](http://www.doublecloud.org/2014/03/nginx-how-to-fix-timeout-issues-and-more/)
and changed 
`proxy_read_timeout = 300s (5 min)`

**Comment by albireox** [comment]
<a href="https://github.com/havok2063"><img src="https://avatars.githubusercontent.com/u/1836302?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [havok2063](https://github.com/havok2063)**
_Saturday Oct 08, 2016 at 22:17 GMT_

----

I have implemented a timeout in the requests for the Interaction class.  This has been merged into the main from my login branch.

**Comment by albireox** [comment]
Has this been merged into master? Can we close this?

**Comment by havok2063** [comment]
Closing this.  There are timeouts in place and some API calls contain more information in the return exception message.
