### ISSUE TITLE
Solve installation of marvin at Utah

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#36]
<a href="https://github.com/albireox"><img src="https://avatars.githubusercontent.com/u/568775?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [albireox](https://github.com/albireox)**
_Sunday Oct 09, 2016 at 20:22 GMT_
_Originally opened as https://github.com/marvin-manga/marvin/issues/79_

----

Now that marvin uses submodules and marvin_brain, sqlalchemy-boolean-search, and wtforms-alchemy are expected to live in `extern/`, checking out new versions of marvin and updating them at Utah becomes a bit more complicated. SubGit does not pushes the submodules, it just ignores them.

For now I have made a patchwork, manually cloning and linking versions at Utah, but this is not a sustainable solution. Some alternatives are:
- Stop using the SVN version altogether and clone the marvin repo, with its submodules. This can be done in /home/manga/software/svn.sdss.org/repo/manga/marvin or in a different directory reserved for git products. We can still clone each branch/tag to a different subdirectory so that modules will work with them. This seems like the best option.
- Keep the SVN and the submodules. For normal users that pip install marvin, marvin would use the submodules. For people who check out the SVN version (Utah, basically) would not have anything in the extern directory. Marvin would, in that case, default to using globally ignore versions. This would require changing the imports for brain, SABS, sdss_access, and wtforms-alchemy. Probably the easier way would be to add the paths in extern to the `sys.path` but with lower priority than the global versions, if they exists.

**Comment by havok2063** [comment]
After today, I think we're close to closing this.  We should do a few tests using the API and maybe sdss_access on a pip installed version.

**Comment by albireox** [comment]
I think we can close this now.
