### ISSUE TITLE
Trying to open a modelcube with Maps should fail in a nice way

### ISSUE THREAD

**Issue by KateRowlands** [sdss/marvin#366]
I tried to open a modelcube with Maps to see what would happen.

maps = Maps('/Users/katerowlands/mount/sdss4/manga/mpl6/HYB10-GAU-MILESHC/8325/12701/manga-8325-12701-LOGCUBE-HYB10-GAU-MILESHC.fits.gz', bintype='HYB10', release='MPL-6')

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-150-647dc17851bb> in <module>()
----> 1 maps = Maps('/Users/katerowlands/mount/sdss4/manga/mpl6/HYB10-GAU-MILESHC/8325/12701/manga-8325-12701-LOGCUBE-HYB10-GAU-MILESHC.fits.gz', bintype='HYB10', release='MPL-6')

//anaconda/envs/python3/lib/python3.6/site-packages/marvin/tools/spaxel.py in spaxel_factory(cls, *args, **kwargs)
     70 
     71     if cls is not SpaxelBase:
---> 72         return type.__call__(cls, *args, **kwargs)
     73 
     74     cube = kwargs.pop('cube', None)

//anaconda/envs/python3/lib/python3.6/site-packages/marvin/tools/maps.py in __init__(self, input, filename, mangaid, plateifu, mode, data, release, drpall, download, nsa_source, bintype, template, template_kin)
    106 
    107         if self.data_origin == 'file':
--> 108             self._load_maps_from_file(data=self.data)
    109         elif self.data_origin == 'db':
    110             self._load_maps_from_db(data=self.data)

//anaconda/envs/python3/lib/python3.6/site-packages/marvin/tools/maps.py in _load_maps_from_file(self, data)
    249 
    250         # We use EMLINE_GFLUX because is present in MPL-4 and 5 and is not expected to go away.
--> 251         header = self.data['EMLINE_GFLUX'].header
    252         naxis = header['NAXIS']
    253         wcs_pre = astropy.wcs.WCS(header)

//anaconda/envs/python3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in __getitem__(self, key)
    311         try:
    312             return self._try_while_unread_hdus(super(HDUList, self).__getitem__,
--> 313                                             self._positive_index_of(key))
    314         except IndexError as e:
    315             # Raise a more helpful IndexError if the file was not fully read.

//anaconda/envs/python3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in _positive_index_of(self, key)
    707         """
    708 
--> 709         index = self.index_of(key)
    710 
    711         if index >= 0:

//anaconda/envs/python3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in index_of(self, key)
    688 
    689         if (found is None):
--> 690             raise KeyError('Extension {!r} not found.'.format(key))
    691         else:
    692             return found

KeyError: "Extension 'EMLINE_GFLUX' not found."

Instead of this cryptic error the code should say something like "You tried to open a file which is not a map file".

The reverse is also true when opening a MAPS file with `ModelCube`

**Comment by havok2063** [comment]
Fixed.
