### ISSUE TITLE
Trying to open a modelcube with Cube should fail in a nice way

### ISSUE THREAD

**Issue by KateRowlands** [sdss/marvin#368]
cc = Cube(filename=MaNGA_HYB10_dir+'7443/12701/manga-7443-12701-LOGCUBE-HYB10-GAU-MILESHC.fits.gz', release='MPL-6')

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-7-0f907cb57b2a> in <module>()
----> 1 cc = Cube(filename=MaNGA_HYB10_dir+'7443/12701/manga-7443-12701-LOGCUBE-HYB10-GAU-MILESHC.fits.gz', release='MPL-6')

//anaconda/lib/python2.7/site-packages/marvin/tools/spaxel.pyc in spaxel_factory(cls, *args, **kwargs)
     70 
     71     if cls is not SpaxelBase:
---> 72         return type.__call__(cls, *args, **kwargs)
     73 
     74     cube = kwargs.pop('cube', None)

//anaconda/lib/python2.7/site-packages/marvin/tools/cube.pyc in __init__(self, input, filename, mangaid, plateifu, mode, data, release, drpall, download, nsa_source)
     84 
     85         if self.data_origin == 'file':
---> 86             self._load_cube_from_file(data=self.data)
     87         elif self.data_origin == 'db':
     88             self._load_cube_from_db(data=self.data)

//anaconda/lib/python2.7/site-packages/marvin/tools/cube.pyc in _load_cube_from_file(self, data)
    168                        self.data['FLUX'].header['NAXIS1'])
    169 
--> 170         self.plateifu = self.header['PLATEIFU']
    171 
    172         # Checks and populates the release.

//anaconda/lib/python2.7/site-packages/astropy/io/fits/header.pyc in __getitem__(self, key)
    148         else:
    149             keyword = key
--> 150         card = self._cards[self._cardindex(key)]
    151         if card.field_specifier is not None and keyword == card.rawkeyword:
    152             # This is RVKC; if only the top-level keyword was specified return

//anaconda/lib/python2.7/site-packages/astropy/io/fits/header.pyc in _cardindex(self, key)
   1672 
   1673         if not indices:
-> 1674             raise KeyError("Keyword {!r} not found.".format(keyword))
   1675 
   1676         try:

KeyError: "Keyword 'PLATEIFU' not found."

Related to #366

**Comment by havok2063** [comment]
Fixed.  All cube, maps and modelcube tools perform a check on the file contents to ensure a proper way is being opened by the proper Marvin Tool.  If not it raises a MarvinError with a message.
