### ISSUE TITLE
params = query.get_available_params('all') does not return full list of parameters

### ISSUE THREAD

**Issue by KateRowlands** [sdss/marvin#369]
from marvin.tools.query import Query

query = Query(release='MPL-6')
params = query.get_available_params('all')

# number of vetted parameters
len(params)

>>WARNING: No local database found. Cannot perform queries.
>>WARNING: local mode failed. Trying remote now.
>>41

41 is the list of 'best' parameters, not the full list which should be 700 parameters.

**Comment by havok2063** [comment]
This was an issue where, in `remote` mode, the `QueryDataModel` did not have access to the `MarvinForm` and parameter schema so could not retrieve the full list of parameters.  It only retrieved the `best` list.  I've given the `QueryDataModel` a tiny `remote` mode API call to grab the list and populate itself as expected.  This is now fixed.
