### ISSUE TITLE
logging sometimes breaks

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#37]
<a href="https://github.com/havok2063"><img src="https://avatars.githubusercontent.com/u/1836302?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [havok2063](https://github.com/havok2063)**
_Thursday Oct 13, 2016 at 17:14 GMT_
_Originally opened as https://github.com/marvin-manga/marvin/issues/81_

----

Sometimes the logging breaks with this error on many different occasions.  Just noting here to fix at some point.

```
Traceback (most recent call last):
  File "/Users/Brian/anaconda2/lib/python2.7/logging/__init__.py", line 853, in emit
    msg = self.format(record)
  File "/Users/Brian/anaconda2/lib/python2.7/logging/__init__.py", line 726, in format
    return fmt.format(record)
  File "/Users/Brian/Work/github_projects/Marvin/python/marvin/extern/marvin_brain/python/brain/core/logger.py", line 84, in format
    result = logging.Formatter.format(self, record)
  File "/Users/Brian/anaconda2/lib/python2.7/logging/__init__.py", line 468, in format
    s = self._fmt % record.__dict__
KeyError: 'origin'
Logged from file logger.py, line 127
```

**Comment by albireox** [comment]
<a href="https://github.com/albireox"><img src="https://avatars.githubusercontent.com/u/568775?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [albireox](https://github.com/albireox)**
_Thursday Oct 13, 2016 at 17:25 GMT_

----

This does sound familiar, but I cannot remember the exact reason. I think it has to do with the catching and logging of warnings. When this happens, are you sure you are doing

`warnings.warn('my text', ACertainWarning)`

If you skip the `ACertainWarning`, it usually fails. Or it may be something different. I'll have a look. If you have an example in which it fails it would help.

**Comment by albireox** [comment]
<a href="https://github.com/havok2063"><img src="https://avatars.githubusercontent.com/u/1836302?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [havok2063](https://github.com/havok2063)**
_Thursday Oct 13, 2016 at 17:45 GMT_

----

Well I've noticed it on many different occasions, but the most recent one (also the least helpful) that will reproduce it is
```
p = 'sersic_logmass >= 9.5 and sersic_logmass < 11 and sersic_n < 2'
q = Query(searchfilter=p)
q.session.prune()
```

**Comment by albireox** [comment]
This should now be fixed in the brain and updated in the submodule in marvin. It seems the origin was not being set for some types of warnings. Now, warning without origin will be logged (in the file) as

```
2016-11-04 11:08:23 - WARNING: SADeprecationWarning: The non-weak-referencing identity map feature is no longer needed. []
```

instead of the normal

```
2016-11-04 11:08:18 - WARNING: MarvinUserWarning: class Plate not Formable [marvin.tools.query.forms]
```

The warning shown on the terminal should now have changed.

**Comment by havok2063** [comment]
This reminds me.  How did you update the brain?  We should establish a policy on how to update our submodules.  I've been working under the guidelines of "always make changes in the real repos and then re-sync into the submodules.  Never make changes in the extern/submodule directory."  Even though I know you can.

**Comment by albireox** [comment]
I'm still getting used to submodules, so take what I'm saying with a bit of scepticism. It should not really matter where you make the changes, as the submodule and the repo itself are linked. The best way is probably to make changes in the repo for marvin_brain itself, push the change, and then go to  the extern/marvin_brain directory and make a `git pull`. You'll then need to commit the change in the submodule itself in marvin and push that to marvin.

You can also do the change directly in extern/marvin_brain and then push it to the marvin_brain repo with something like `git push --recurse-submodules=check`.

The thing with submodules is that they allow you to keep your submodule at a different state that the repo itself. For instance, the repo may be in tag 1.2.1, but your submodule can stay in tag 1.1.2 (not that _anybody_ would ever want to be outdated). As long as one is careful with what you want to do, both methods should work.

**Comment by havok2063** [comment]
keeping things outdated sounds like a recipe for disaster.

**Comment by havok2063** [comment]
This issue appears to be back.  I was playing around with the marvin log to start replacing some of our print statements with real log statements, and this happened. 

```
from marvin import log
log.debug('dfdfd')
log.debug('debug statement')
log.error('error')
ERROR: error

log.warning('warning')
WARNING: arning
Traceback (most recent call last):
  File "/Users/Brian/anaconda2/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/Users/Brian/anaconda2/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/Users/Brian/Work/github_projects/Marvin/python/marvin/extern/marvin_brain/python/brain/core/logger.py", line 84, in format
    result = logging.Formatter.format(self, record)
  File "/Users/Brian/anaconda2/lib/python2.7/logging/__init__.py", line 469, in format
    s = self._fmt % record.__dict__
KeyError: 'origin'
Logged from file <ipython-input-11-a3d9cad2ba0a>, line 1

log.info('this is an info statement')
INFO: this is an info statement
```
and here is the last few lines of output from marvin.log

```
2016-11-15 09:46:39 - INFO - No release version set. Setting default to MPL-5 [_checkConfig @ __ini$
2016-11-15 09:48:12 - DEBUG - dfdfd [<module> @ <ipython-input-8-d37949460bed>]
2016-11-15 09:48:16 - DEBUG - debug statement [<module> @ <ipython-input-9-a53fc08da177>]
2016-11-15 09:48:22 - ERROR - error [<module> @ <ipython-input-10-73ac118b3621>]
2016-11-15 09:54:23 - INFO - this is an info statement [<module> @ <ipython-input-12-e6ef237dc36f>]
```

**Comment by albireox** [comment]
I think I fixed it. I overrode the `warning` method to include an empty origin.

That said, in principle `log.warning` should not be called directly. The idea if that when you issue a warning you do

```
warnings.warn('This is a warnings', MyWarningClass)
```

and it will catch the warnings, output it nicely to the shell, and then log it with a correct origin.
