### ISSUE TITLE
marvin install with pip within conda environment

### ISSUE THREAD

**Issue by zpace** [sdss/marvin#373]
I finally found a solution to a persistent issue I've had `pip install`-ing both the Marvin software and other python packages. Installations have failed with a message like `PermissionError: [Errno 13] Permission denied: '/lib/python3.6'`.

One way to fix this is to delete the file `$HOME/.pydistutils.cfg`, which contains text that erroneously modifies the `prefix` of the installation. For cases where `sudo pip` is not an option, this is an alternative and (I think) preferable to setting the `--user` flag. I'd suggest you add this to the [Permissions Error](http://sdss-marvin.readthedocs.io/en/latest/installation.html#permissions-error) section of the installation walkthrough.

Original [conda issue](https://github.com/conda/conda/issues/1170)

**Comment by havok2063** [comment]
Thanks for this find.  I've added a note in the relevant section on in the installation page.
