### ISSUE TITLE
Cube tries to open cube before download is complete

### ISSUE THREAD

**Issue by KateRowlands** [sdss/marvin#375]
If I try to open a cube that is not in my local sas e.g. 8274-12701

cc = Cube(plateifu='8274-12701', download=True)

SDSS_ACCESS> syncing... please wait
SDSS_ACCESS> Done!
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-123-528b6035973d> in <module>()
----> 1 cc = Cube(plateifu=plateifu[100], download=True)

//anaconda/lib/python2.7/site-packages/marvin/tools/spaxel.pyc in spaxel_factory(cls, *args, **kwargs)
     70 
     71     if cls is not SpaxelBase:
---> 72         return type.__call__(cls, *args, **kwargs)
     73 
     74     cube = kwargs.pop('cube', None)

//anaconda/lib/python2.7/site-packages/marvin/tools/cube.pyc in __init__(self, input, filename, mangaid, plateifu, mode, data, release, drpall, download, nsa_source)
     84 
     85         if self.data_origin == 'file':
---> 86             self._load_cube_from_file(data=self.data)
     87         elif self.data_origin == 'db':
     88             self._load_cube_from_db(data=self.data)

//anaconda/lib/python2.7/site-packages/marvin/tools/cube.pyc in _load_cube_from_file(self, data)
    159                 self.data = fits.open(self.filename)
    160             except (IOError, OSError) as err:
--> 161                 raise OSError('filename {0} cannot be found: {1}'.format(self.filename, err))
    162 
    163         self.header = self.data[1].header

OSError: filename /Users/katerowlands/sas/mangawork/manga/spectro/redux/v2_3_1/8274/stack/manga-8274-12701-LOGCUBE.fits.gz cannot be found: [Errno 2] No such file or directory: u'/Users/katerowlands/sas/mangawork/manga/spectro/redux/v2_3_1/8274/stack/manga-8274-12701-LOGCUBE.fits.gz'

**Comment by havok2063** [comment]
I cannot recreate this error in Python 2 or 3.

Opening a cube I don't have in remote mode
```
c = Cube(plateifu='8485-1902')
WARNING: local mode failed. Trying remote now.
c
<Marvin Cube (plateifu='8485-1902', mode='remote', data_origin='api')>

```
Opening it with `download=True`
```
c = Cube(plateifu='8485-1902', download=True)
SDSS_ACCESS> syncing... please wait
SDSS_ACCESS> Done!

c
<Marvin Cube (plateifu='8485-1902', mode='auto', data_origin='file')>
```

**Comment by havok2063** [comment]
Attempting to test issue #359, I was able to recreate this error with

```
from marvin import config
INFO: No release version set. Setting default to MPL-6

config.mode='local'
config.download=True
from marvin.tools.cube import Cube
config.forceDbOff()

cc = Cube(mangaid='12-193481')
SDSS_ACCESS> syncing... please wait
SDSS_ACCESS> Done!
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-7-918c389341fc> in <module>()
----> 1 cc = Cube(mangaid='12-193481')

/Users/Brian/Work/github_projects/Marvin/python/marvin/tools/spaxel.pyc in spaxel_factory(cls, *args, **kwargs)
     70
     71     if cls is not SpaxelBase:
---> 72         return type.__call__(cls, *args, **kwargs)
     73
     74     cube = kwargs.pop('cube', None)

/Users/Brian/Work/github_projects/Marvin/python/marvin/tools/cube.pyc in __init__(self, input, filename, mangaid, plateifu, mode, data, release, drpall, download, nsa_source)
     84
     85         if self.data_origin == 'file':
---> 86             self._load_cube_from_file(data=self.data)
     87         elif self.data_origin == 'db':
     88             self._load_cube_from_db(data=self.data)

/Users/Brian/Work/github_projects/Marvin/python/marvin/tools/cube.pyc in _load_cube_from_file(self, data)
    159                 self.data = fits.open(self.filename)
    160             except (IOError, OSError) as err:
--> 161                 raise OSError('filename {0} cannot be found: {1}'.format(self.filename, err))
    162
    163         self.header = self.data[1].header

OSError: filename /Users/Brian/Work/sdss/sas/mangawork/manga/spectro/redux/v2_3_1/7443/stack/manga-7443-12703-LOGCUBE.fits.gz cannot be found: [Errno 2] No such file or directory: u'/Users/Brian/Work/sdss/sas/mangawork/manga/spectro/redux/v2_3_1/7443/stack/manga-7443-12703-LOGCUBE.fits.gz'
```

**Comment by havok2063** [comment]
Fixed.
