### ISSUE TITLE
queries should be asynchronous

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#38]
<a href="https://github.com/havok2063"><img src="https://avatars.githubusercontent.com/u/1836302?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [havok2063](https://github.com/havok2063)**
_Tuesday Oct 18, 2016 at 08:15 GMT_
_Originally opened as https://github.com/marvin-manga/marvin/issues/82_

----

Marvin queries should be asynchronous.  Ideally, users submit queries to the server which get queued into a system, run, and then return results or a notification when the results have finished. This may mean setting up a server-side user session which stores submitted queries and results.  

At some level, this means that requests should be asynchronous, rather than the queries themselves.  The Interaction class should not wait for a response from the server.

This all could go hand-in-hand with the move to Trac-based user authentication for the API, using oAuth, with user session and history, etc.

**Comment by albireox** [comment]
<a href="https://github.com/havok2063"><img src="https://avatars.githubusercontent.com/u/1836302?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [havok2063](https://github.com/havok2063)**
_Tuesday Oct 18, 2016 at 14:51 GMT_

----

I am looking at using requests-futures to make Python Requests asynchronous.  https://github.com/ross/requests-futures.  Another option is grequests https://github.com/kennethreitz/grequests.

E.g. something like 
```
# start requests
session = FuturesSession()
fone = session.post('https://api.sdss.org/marvin2/api/cubes/8485-1901')
ftwo = session.post('https://api.sdss.org/marvin2/api/query/cubes/', data={'searchfilter':'haflux>15', 'limit':100, 'release':'MPL-4'})
fthree = session.post('https://api.sdss.org/marvin2/api/query/cubes/', data={'searchfilter':'nsa.sersic_logmass > 9.5 and nsa.sersic_logmass < 10 and nsa.sersic_n < 1', 'limit':100, 'release':'MPL-4'})

# check if the requests are running or done
fone.running()
False
fone.done()
True

ftwo.done(), fthree.done()
(False, False)

# retrieve the response if they are done, or call it while running to block and wait for the response to return
resp1 = fone.results()
resp2 = ftwo.results()

# these are standard responses, rest of Interaction is the same, can do
resp1.status_code
resp1.json()
etc
```

I've played around with requests-future, and I'm liking it.  This would make all requests asynchronous, including queries and all tools.  The idea here would be to implement this in the Brain Interaction class, and create hooks to queue up responses.  If we don't want remote calls on Tools to be async to make it easier, in the Tools we can call .results() immediately, but for Queries and maybe Results, we queue up responses and add in methods for checking submitted requests, and grabbing finished responses, etc.  Thoughts?

**Comment by albireox** [comment]
<a href="https://github.com/havok2063"><img src="https://avatars.githubusercontent.com/u/1836302?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [havok2063](https://github.com/havok2063)**
_Tuesday Oct 18, 2016 at 20:58 GMT_

----

Also, should we try to push this in before the beta release?

**Comment by albireox** [comment]
<a href="https://github.com/havok2063"><img src="https://avatars.githubusercontent.com/u/1836302?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [havok2063](https://github.com/havok2063)**
_Tuesday Oct 18, 2016 at 21:35 GMT_

----

Also to note.  The above package is async in that in lets the user continue to use python while the request is happening.  It does nothing on the server side.  If the user exits python before those requests are finished, they would lose them.  We would have to implement something on the server side to actually save/store statuses, to be retrieved later.

**Comment by havok2063** [comment]
Can be closed.  Probably out of scope.
