### ISSUE TITLE
Many instances of pytest.approx() use incorrect syntax

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#383]
We have many instances of `assert pytest.approx(a, b)` but the correct syntax is `assert a == pytest.approx(b)`. The former syntax sets the relative tolerance to `b`.

**Comment by bretthandrews** [comment]
6cc4aa86821e4bf6b7fa1430fa074c5dfbe07b7c fixes the instances of incorrect `pytest.approx()` syntax, but now all of the tests in`test_sampledb.py` fail (all other tests modified pass).

**Comment by havok2063** [comment]
The hard-coded numbers in the tests are for 8485-1901.  The tests fail for 7443-12701.

**Comment by havok2063** [comment]
Looks like this is fixed now.
