### ISSUE TITLE
plotting a map ratio does not update the title 

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#384]
This code still has `NII` as the title rather than the ratio.  This could be confusing. 
```
niiha = maps.emline_gflux_nii_6585 / maps.emline_gflux_ha_6564
niiha.plot()
```
We could also use the latex formatting for nicer display, e.g `ha.datamodel.to_string('latex')`

**Comment by bretthandrews** [comment]
Possible options:

1. Remove public-facing `datamodel` attribute from EnhancedMap
a. Remove `EnhancedMap.datamodel` but leave the hidden version (i.e., `EnhancedMap._datamodel`)
b. convert all uses of `Map.datamodel` to `Map._datamodel`
c. Force no title when plotting EnhancedMap

2. Customize `utils.datamodel.dap.base.py/Property` for EnhancedMaps
