### ISSUE TITLE
Downloading maps with MPL-6 fails. (Fine with MPL-5 .)

### ISSUE THREAD

**Issue by ericliang45** [sdss/marvin#386]
The code:

from marvin import config
config.setRelease('MPL-6')
gallist = ['8485-1901', '7443-12701']
downloadList(gallist, dltype='map')

The error message:
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-20-64fd525099c0> in <module>()
----> 1 downloadList(gallist, dltype='map')

/Users/fuhengliang/Applications/anaconda/lib/python2.7/site-packages/marvin/utils/general/general.pyc in downloadList(inputlist, dltype, **kwargs)
    827             ifu = '*'
    828 
--> 829         rsync_access.add(name, plate=plateid, drpver=drpver, ifu=ifu, dapver=dapver, dir3d=dir3d,
    830                          mpl=release, bintype=bintype, n=n, mode=binmode, daptype=daptype)
    831 

UnboundLocalError: local variable 'name' referenced before assignment

**Comment by havok2063** [comment]
Fixed for now until public/collab refactor
