### ISSUE TITLE
MPL-4 7443-12701 plots are shifted in tools and web

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#389]
All the plots for 7443-12701 in MPL-4 are shifted upwards.  First noticed in the web in all browsers.  Also a problem with the tools.  This is on the local feedback branch.  

Web
![screen shot 2018-03-09 at 3 37 21 pm](https://user-images.githubusercontent.com/1836302/37228806-de6c7fd2-23af-11e8-8e35-7061b7460412.png)

Tools - MPL-6 on left, MPL-4 on right
![screen shot 2018-03-09 at 3 37 48 pm](https://user-images.githubusercontent.com/1836302/37228813-e7f4a1f6-23af-11e8-85e8-ab6e3a5ff88d.png)

**Comment by bretthandrews** [comment]
We're not going to fix this because it is only a problem in MPL-4 and that release is no longer recommended for use.
