### ISSUE TITLE
implement more complete testing framework

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#39]
<a href="https://github.com/havok2063"><img src="https://avatars.githubusercontent.com/u/1836302?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [havok2063](https://github.com/havok2063)**
_Wednesday Oct 19, 2016 at 09:50 GMT_
_Originally opened as https://github.com/marvin-manga/marvin/issues/83_

----

Ahead of DR14 and near to post-Beta, implement automated and extensive testing environment, with coverage.  This includes using Travis-CI to automate all tests across multiple environments and using Coveralls.io to monitor testing coverage over time.  Repos must be public.  Can be set up for both Python and Javascript environments.  

API tests - python + http requests 
Tools tests - python
Web tests - python + flask + javascript

Python - can use coverage
Javascript - can use grunt-coveralls, mocha+istanbul

Add grunt-coveralls to Gruntfile to map coverage results to coveralls.io.  Look into mocha+instanbul for building actual JS tests and see if we can merge that with grunt-coveralls to pipe output to coveralls.io.  

I think this will potentially save us a load of trouble down the line post-beta trying to 1.) ensure robust quality control on web and api features, 2.) handle community-driven updates on tools, 3.) having to remember to run tests

https://travis-ci.org
https://coveralls.io
https://github.com/coagulant/coveralls-python
http://gruntjs.com/plugins - search coverage
https://github.com/pimterry/grunt-coveralls
https://mochajs.org/
https://github.com/gotwarlost/istanbul

**Comment by albireox** [comment]
I'm totally for this. The main problem, of course, is that our tests are not totally trivial as they require files and a DB. The file part may be relatively easy to solve, we'd just need to have a `test_data` directory with files we use for testing (so, basicaly 8485-1901 in its different incarnations). Maybe we can create a repository in GitHub with test data that Travis can use for testing but that it's not download when the user clones the repo or pip installs it.

The DB issue is probably more complicated. Maybe we can skip those tests (there is already a decorator somewhere to decorate DB tests so that they'll be skipped if there is not a local DB). Most users only will use files or the API, so if we can cover those tests automatically we'll be 90% ok.

**Comment by havok2063** [comment]
Yeah, I agree.  I think we should rethink our testing situation.  Maybe we can create a tiny test db that lives in marvin as well.  Travis sets up a virtual environment for all testing, so we may be able to customize the installation procedure before it runs our tests.  There are many hooks for before_ and after_ different stages.  I know it does load some version of postgresql as well.

**Comment by albireox** [comment]
Closing as of 2.1.4. Framework is in place and tests are passing.
