### ISSUE TITLE
WHAN solution does not mask spaxels properly

### ISSUE THREAD

**Issue by mlmarinelli** [sdss/marvin#392]
Using the WHAN solution linked [here](http://sdss-marvin.readthedocs.io/en/stable/exercises.html):

Spaxels that should be masked are classified as PG and colored as such. Solution code should read: 
fig, ax, cb = mapplot.plot(**dapmap=ewha,** value=value, cmap=cmap, mask=nocov, return_cb=True, cbrange=(0.5, 5.5))

Available WHAN solution additionally still uses getMapRatio instead of created EnhancedMap.

![8606-3701_bad_whan](https://user-images.githubusercontent.com/29264471/37488392-d5533da4-286a-11e8-9b15-fab4a491d5ba.png)
![8606-3701_attempt_2](https://user-images.githubusercontent.com/29264471/37489440-0430db06-286e-11e8-8eab-e84a579c0e67.png)

**Comment by bretthandrews** [comment]
same as #376

**Comment by bretthandrews** [comment]
For now, I have changed the WHAN diagram notebook to now only plot the spaxels with SNR >= 1. You have to manually create an ivar array and set it to 0 where the SNR of the input parameters  is < 1:

```
# Set ivar to 0 where the SNR < 1
niiha_low_snr = mapplot.mask_low_snr(niiha.value, niiha.ivar, snr_min=1)
ewha_low_snr = mapplot.mask_low_snr(ewha.value, ewha.ivar, snr_min=1)
ewnii_low_snr = mapplot.mask_low_snr(ewnii.value, ewnii.ivar, snr_min=1)
low_snr = np.logical_or(niiha_low_snr, ewha_low_snr, ewnii_low_snr)

ivar = copy.deepcopy(value)
ivar[low_snr] = 0
```

Then we change the plotting call to include `ivar=ivar` and add `use_masks='NOCOV':
```
fig, ax, cb = mapplot.plot(value=value, ivar=ivar, mask=nocov, cmap=cmap, use_masks='NOCOV',
                           return_cb=True, cbrange=(0.5, 5.5),
                           title='WHAN Diagram {}'.format(plateifu))
```

However, this solution is only temporary, and we are working on a more intuitive way to plot categorical maps with low SNR regions masked.
![whan](https://user-images.githubusercontent.com/12723826/37557262-7f8069de-29c7-11e8-9fca-c82d29311568.png)

**Comment by bretthandrews** [comment]
FYI these changes have not yet been pushed to master yet
