### ISSUE TITLE
SII in BPT diagram should use sum of 6717 and 6732

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#400]
Copied from Eric Liang's email:

> I've just noticed Marvin plots BPT diagrams (OIII vs SII) with SII 6718 line only. But as far as I know, people usually use sum(SII 6718, SII 6732) in literature, since the ratio between the two lines varies from case to case. Also, at least in some galaxies —if not all — the two lines are nearly equally strong, so omitting one of them could cause a considerable difference.

Looking at the literature this seems to be the case.

**Comment by ericliang45** [comment]
Thanks for creating this issue. Figure 1 in the Ke06 paper shows that the definition originates from the Ke01 paper. In the Ke01 paper, the denotation is "[S II] λλ6717, 31". In addition, I consulted Kai Zhang and some other MaNGA members. They said people usually refer to the sum of the two lines for S II.

Ref: Kewley L. J., Dopita M. A., Sutherland R. S., Heisler C. A., Trevena J., 2001a, ApJ, 556, 121

**Comment by albireox** [comment]
Thanks for confirming this Eric. Yes, I agree that seems to be the standard denotation, although it is never completely spelled that it refers to the sum.This should be fixed soon.
