### ISSUE TITLE
__dir__ autocomplete is broken in iPython 6.3.0

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#402]
It seems that in iPython 6.3.0 (released today) the autocomplete for (at least) Maps properties does not work. Doing `dir(maps)` still gives you the full list of properties, and they can be accessed doing, e.g., `maps.emline_instsigma_oii_3727`, but the autocomplete feature does not work.

iPython 5.6.0 (also released today) doesn't have this problem so I'm not sure this is a change in behaviour or a bug. Maybe it's worth waiting a bit before fixing this.

**Comment by bretthandrews** [comment]
https://xkcd.com/1172/

**Comment by albireox** [comment]
> And blessed are the patient, for they shall close issues without having to do any work.

For reference, this is a bug in Jedi (davidhalter/jedi/issues/1027) that has been fixed but not yet released. iPython 6.3.1 reverts to its own internal completion system by default which fixes the problem for now.
