### ISSUE TITLE
Example in API doc fails

### ISSUE THREAD

**Issue by ericliang45** [sdss/marvin#404]
From the following page:
http://sdss-marvin.readthedocs.io/en/stable/api/api.html?highlight=Interaction
I tried the example code and it failed from "response = Interaction(url.format(name=plateifu))" with an error message "No URL Map found. Cannot make remote call".

I guess there is a bug either with marvin or with the doc.

ps: for comparison, I tried "from marvin.tools.maps import Maps; Maps(plateifu = plateifu)" and this works.

**Comment by bretthandrews** [comment]
@ericliang45 Thanks for submitting this issue! Unfortunately, I wasn't able to reproduce your error, so I'm not sure what went wrong for you (perhaps Marvin was down at the time). Would you mind trying again?

Here's what I tried:
```python
from marvin import config
config.mode = 'remote'
from marvin.api.api import Interaction
plateifu = '7443-12701'
url = config.urlmap['api']['getCube']['url']
response = Interaction(url.format(name=plateifu))
```

**Comment by ericliang45** [comment]
Hi Brett, I tried the code you provided on both my local machine and a server and still got the same error on both machines. Please see the attached screenshot. For both I was using iPython shell with Marvin 2.2.3.

Local machine:
/Users/fuhengliang/Desktop/local.png

Server:
/Users/fuhengliang/Desktop/server.png

**Comment by ericliang45** [comment]
Hi Brett, I tried the code you provided on both my local machine and a server and still got the same error on both machines. Please see the attached screenshot. For both I was using iPython shell with Marvin 2.2.3.

Local machine:
<img width="1272" alt="local" src="https://user-images.githubusercontent.com/23513046/38535308-73c8a95c-3cb5-11e8-9ad0-d25ba8da9543.png">

Server:
<img width="1226" alt="server" src="https://user-images.githubusercontent.com/23513046/38535312-7800a7e0-3cb5-11e8-93c0-349a654378e9.png">

**Comment by bretthandrews** [comment]
@ericliang45 I just tried this again in Python 2.7 and 3.6, and it works for me. Would you mind trying that code snippet again?

**Comment by ericliang45** [comment]
Yeah, it also works for me now (both on the local machine and on a server). Thanks.
