### ISSUE TITLE
Need to add passlib to requirements

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#413]
I did a fresh install of marvin and it now requires `passlib` because of the brain master branch but this package is not currently in Marvin's requirements file.

I wasn't sure what version of `passlib` is needed, so I'll leave it to you @havok2063. Also, we might want to consider creating a Brain requirements file.

We should do a patch release to fix this.

**Comment by havok2063** [comment]
I believe the pypi installations only install the submodule version that was in place when you built the package.  Same thing with tagging.  I believed we tagged `2.2.5` before I started hacking the brain with the new authentication stuff.  Could this be an issue with your environment paths not getting reset?

**Comment by bretthandrews** [comment]
Thanks @havok2063 that was the problem
