### ISSUE TITLE
Sensible error message for galaxies in the target list but not yet in Marvin web

### ISSUE THREAD

**Issue by karenlmasters** [sdss/marvin#414]
Would it be possible to have a different error message for entries in the target list, but not the DRPall? 

The below is a potential MaNGA target, and it would just be nice if the response is "Sorry that Plate or ID Designation is for a galaxy which has not yet been observed by MaNGA. Not all possible MaNGA targets will be observed" (or something similar and more clever in Marvin style). 

"MarvinError: mangaid2plateifu was not able to find a plate-ifu for mangaid=1-95058 either local or remotely.. "

**Comment by havok2063** [comment]
This should be possible but we'd need to change some of the underlying lookup functionality to check directly the manga sample/target DB, which we currently don't do in Marvin.  I think it would be useful to look up what manga targets have not yet been observed.

**Comment by karenlmasters** [comment]
For now could just say - "this is either not a correct plate-ifu or hasn't
been observed yet" (or similar).

Karen.

**Comment by havok2063** [comment]
I've implemented a utility function to check the target status of a mangaid, `target_status` and `target_is_observed`.  The galaxy web page now returns a slightly more sensible error message if a target is not a valid one, or is but has not yet been observed.  This is included in PR #407.

**Comment by bretthandrews** [comment]
Is it possible for a query to return `target_status` and `target_is_observed`?

**Comment by havok2063** [comment]
Not without more work.  Querying non-database things is a bit of a refactor of the query system.  Although we could probably create new properties that live on a ModelClass that call these functions.  We might be able to circumvent refactoring the Query tool that way.  Currently, they can only be used programmatically as a utility function.
