### ISSUE TITLE
problems with downloadList()

### ISSUE THREAD

**Issue by YiqingLiu** [sdss/marvin#418]
Hello, 

I am trying to download DRP cubes according to the manga_ids. Below are my code for it. 

from marvin import config
from marvin.utils.general import downloadList
config.setRelease('MPL-6')
galLs = loadtxt('selSamp_ID.tab', dtype=str)[:,0]  # mangaID 
downloadList(galLs, dltype='cube')

I also have the '.netrc' file in my home directory with: 
machine api.sdss.org
   login sdss
   password XXXXXX

However, when I run 'python3 download.py', it requests my password. Typing 'XXXX' does not work, and it always report: 
['no DB connection found']
Sentry responded with an API error: RateLimited(Creation of this event was denied due to rate limiting)

Apart from Marvin, are there any other efficient ways to download cubes and maps if I only know the manga_ids? 

Many thanks.

**Comment by albireox** [comment]
Hi @YiqingLiu,

First, please do not write down passwords in the issues. This is a public repository and that would allow other people to know the common password. I edited your comment to remove it.

Not sure why writing the password when you get prompted does not work, maybe @havok2063 can comment on that. But I think you netrc file is not complete. As described [here](http://sdss-marvin.readthedocs.io/en/stable/installation.html#set-up-your-netrc), your `.netrc` must be

```
machine api.sdss.org
   login sdss
   password <password>

machine data.sdss.org
   login sdss
   password <password>
```

where `<password>` is the default SDSS password (the one you were using). Make sure your `.netrc` has the permissions set to 600.

Can you try that and let us know if that does not fix the problem?

**Comment by YiqingLiu** [comment]
Hi Jose,

Apologise for typing the password.

I just tried again and found it worked. However, I have another question.
Right now all the downloaded data are stored in the
directory '/Users/yiqingliu/sas/mangawork/manga/spectro/redux/v2_3_1'.  Is
it possible for me to change the default path?

Besides, bintype='VOR10' is not available for Marvin downloading, is it?
Are there any other ways to download them according to the manga_ids?

Thanks,

Yiqing

2018-06-26 22:40 GMT+01:00 José Sánchez-Gallego <notifications@github.com>:

**Comment by albireox** [comment]
Hi Yiqing,

Glad that it worked. Yes, you can change the default path to your SAS by setting the environment variable `SAS_BASE_DIR` to what you want. For instance, if you set `SAS_BASE_DIR=/Users/yiqingliu/Documents/sas` everything will be stored under that structure. You can see more details [here](http://sdss-marvin.readthedocs.io/en/stable/installation.html#local-sas-directory-structure).

No, right now I don't think there is a way to download MPL-6 maps that are not SPX or HYB10. To download them, you can use [sdss_access](https://github.com/sdss/sdss_access) (and the [docs](http://sdss-access.readthedocs.io/en/latest/index.html)). You'll need to figure out the plate-ifu for each of your mangaids. You can do that using Marvin, e.g.,

```python
from marvin.utils.general import mangaid2plateifu
plateifu = mangaid2plateifu(mangaid)
```

and then you can use sdss_access to download the maps or other products for that plateifu.

**Comment by havok2063** [comment]
I'll just add that even if you change your `SAS_BASE_DIR` environment variable, the directory structure within that path will be the same `mangawork/manga/spectro/redux/v2_3_1`.  Marvin requires that path structure, so that part cannot be changed.

**Comment by albireox** [comment]
I think we can close this now. Please, feel free to reopen or post any other question that you have.

**Comment by YiqingLiu** [comment]
Thanks very much, Jose and Brian.

Apologise for my silence. I haven't got a chance to try it yet.
But I think these comments are helpful. I will let you know if there are
problems when I test it.

Thanks again.

Yiqing

2018-07-02 7:43 GMT+01:00 José Sánchez-Gallego <notifications@github.com>:

**Comment by YiqingLiu** [comment]
Dear Jose and Brian,

Thanks very much for your help last time.  Now I am trying to download the
DRP cube in our server, and similar problems happen again.

When I use 'downloadList(gallist, dltype='cube')', I get:
Sentry responded with an API error: RateLimited(Creation of this event was
denied due to rate limiting)
['no DB connection found']
['no DB connection found']
...

When I try 'cc = Cube(mangaid=MGid[i], download=True)', I am told:
OSError: filename
/mnt/zfsusers/YqL/sas/mangawork/manga/spectro/redux/v2_3_1/8938/stack/manga-8938-12701-LOGCUBE.fits.gz
cannot be found: [Errno 2] No such file or directory:
'/mnt/zfsusers/YqL/sas/mangawork/manga/spectro/redux/v2_3_1/8938/stack/manga-8938-12701-LOGCUBE.fits.gz'

However when I go to
/mnt/zfsusers/YqL/sas/mangawork/manga/spectro/redux/v2_3_1/8938/stack/,
I do find the file 'manga-8938-12701-LOGCUBE.fits.gz' downloaded there.

Could you please help?

Yiqing

2018-07-02 20:18 GMT+01:00 Yiqing Liu <halfxianr@gmail.com>:
