### ISSUE TITLE
Marvin query runs indefinitely

### ISSUE THREAD

**Issue by sjshamsi** [sdss/marvin#419]
Hello,

I've been trying to run the Marvin Query tool, running it for a simple instance and picked the example from the Marvin documentation First Steps/My First Query page. I run the code:
`from marvin.tools.query import doQuery`
`q, r = doQuery(searchfilter='nsa.z < 0.2 and ifu.name=19*')`

We get
`INFO: No release version set. Setting default to MPL-6`
`Your parsed filter is:` 
`and_(nsa.z<0.2, ifu.name=19*)`
in the textbox, and my Jupyter notebook line indicates that the code is still running ( [*]).

The same code from above should recreate the event.

I expected it to return with a database of galaxies numbering the upper limit (since I didn't provide a number for max amount of results.

 - OS: ubuntu 16.04 LTS
 - Firefox
 - Marvin 2.2.5

I do have permissions 600 for .netrc.

**Comment by havok2063** [comment]
Hi, 

Can you try this query again?  I tried this query in my iPython terminal and in a Jupyter notebook and the query ran ok and finished successfully.

**Comment by sjshamsi** [comment]
Hello,

I had a colleague run the bit of code for me and he was able to get some results back, so the issue might be on my end. Is there anything I can try to make it work?

**Comment by havok2063** [comment]
Hmm.. I'm not sure.  Does it give any warning or error message of any kind?  Can you try the same thing inside a standard iPython terminal rather than a Jupyter notebook and see if it reports any kind of message, or behaves the same?  If there is no output it'll be hard to diagnose what's going on, but we'll try.  What country are you in?

**Comment by havok2063** [comment]
Closing this until this happens again.
