### ISSUE TITLE
config not automatically checking netrc

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#422]
**Describe the bug**
The config is not automatically checking the netrc file for collaboration access.

**To Reproduce**
Steps to reproduce the behaviour:
```python
from marvin import config
config.access  # 'public'
```

**Expected behaviour**
```python
from marvin import config
config.access  # 'collab'
```

If I manually enable auto-checking for netrc, it works:
```python
In [6]: config._custom_config.get('auto_check_netrc', None)
Out[6]: False

In [7]: config.access
Out[7]: 'public'

In [8]: config._custom_config
Out[8]:
{'add_github_message': True,
 'auto_check_netrc': False,
 'download': False,
 'use_sentry': True}

In [9]: config._custom_config['auto_check_netrc'] = True

In [10]: config._check_netrc()

In [11]: config.access
Out[11]: 'collab'
```

**Comment by bretthandrews** [comment]
I found this in a branch ("sigmaplot") that branches off of the "dr15" branch, so perhaps this isn't merged in quite yet, but it broke the tests in tools/test_map.py

**Comment by havok2063** [comment]
Yeah, it doesn't automatically check for it.  You have to specify it in your marvin.yaml config file, that lives in `~/.marvin/marvin.yaml`  That's the desired behavior.   

Yeah I can't be certain which tests are still working and which do not.  I take a stab at fixing some of them, get sick of it, and move on.

**Comment by bretthandrews** [comment]
Closing this issue because it will be fixed in documentation.
