### ISSUE TITLE
Spectrum.plot should accept kwargs to be passed to pyplot.plot

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#425]
Currently there are only a few parameters of the plot in `Spectrum.plot` that can be customised without having to hack the axes after the plot has been created. For instance, if you want to add a label to the spectrum line to generate a legend, you need to do

```python
ax = my_bin.flux.plot(show_std=True, n_sigma=3)
ax.lines[0].set_label('flux')
```

`Spectrum.plot` should accept a dict of kwargs to be passed directly to `ax.plot()`, which should solve many of these problems.

**Comment by havok2063** [comment]
Kate just independently asked about the spectrum plotter accepting general matplotlib keywords.   Upvoting for relevance.
