### ISSUE TITLE
Should we do something about the HYB model cube binning?

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#427]
@kbwestfall raised the subtlety that the `HYB10` model cube datashould be compared with the binned flux or the DRP logcube depending on the extension. See [https://trac.sdss.org/wiki/MANGA/TRM/TRM_MPL-7/DAPDataModel#HYBbinningscheme](here) and in particular

> The binned spectra provided in the HYB LOGCUBE files are from the Voronoi binning step; however, the emission-line models are fit to the individual spaxels. When using the LOGCUBE files for this binning scheme:
> - The stellar-continuum fits (obtained by computing MODEL - EMLINE - EMLINE_BASE) should be compared to the Voronoi binned spectra in the file, but
> - the best-fitting model spectra (stellar continuum + gas emission) in the MODEL extension should be compared to the individual spectra from the DRP LOGCUBE file!

Not sure we need to do something about it apart from documenting. Maybe raise a warning when accessing these attributes in the modelcube?

**Comment by havok2063** [comment]
We probably should do something here.  I think at least documenting it somewhere and raising warnings when attempting to use it the wrong way.  Is there anything we can to enforce or ensure the correct usage?  i.e. in terms of handling the data/extensions for them?
