### ISSUE TITLE
Provide access to VAC data

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#428]
This is already half-coded but I don't think there was an issue to define the scope of this implementation.

We agreed to provide some VAC integration in Marvin by implementing a class that the VAC owners can subclass to return contributed data. Implementation details (to be discussed):

- We won't load data into the DB. All VAC data access must happen via files stored in the SAS and downloaded to the user's local SAS.
- The parent class defines general methods such as downloading file(s) from the SAS.
- Each subclass defines the SAS path(s) of the file(s) to download.
- Each subclass defines the name of the VAC.
- Each subclass has a method with a predefined name (e.g., `get_vac_data()`) that performs the match between plate-ifu and the VAC data and returns a dictionary with the object VAC data. In principle the output format does not need to be restricted to a dictionary but it would be good to set some guidelines on what the method should return so that the user can have some expectation.
- Whe `get_vac_data()` gets called it must check whether the local VAC file exists and, otherwise, download the VAC (this may be a configurable option).
- The parent class somehow (metaclass?) registers all its subclasses and acts as a MixIn for `MarvinToolsClass`.
- `MarvinToolsClass`, on init, creates a container property `.vacs` which is a (dotable) dictionary of VAC properties, each one returning the result of `get_vac_data()` method its VAC subclass.

**Comment by havok2063** [comment]
This has been implemented.
