### ISSUE TITLE
Add Documentation on how to login

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#431]
**Describe the bug**
Error message when trying retrieve data remotely without logging in is not helpful.

**To Reproduce**
maps = Maps(plateifu='7443-12703')
BrainError: No URL Map found. Cannot make remote call

**Expected behaviour**
BrainError: No URL Map found. Cannot make remote call. Try logging in with
```python
from marvin import config
config.login()
```

**Comment by havok2063** [comment]
Included in #407.  Can reorganize in the great doc-reorg of 2018.
