### ISSUE TITLE
Improvements to pixmask and quality_flag

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#462]
Right now the `pixmask` and `quality_flag` properties are a bit inconsistent. A few improvements could be:

- [x] `pixmask` and `quality_flag` can be moved to `MarvinToolsClass`. The name of the `QUAL` mask can be defined in the subclasses.
- [x] For `pixmask`, the maskbit flag can always be found in `header['MASKNAME']` so it doesn't need to be hardcoded.
- [x] Right now `pixmask` is only present in the `Map`. It should be added to all the quantities, probably directly in `QuantityMixIn`. When initialising a quantity, the parent class can define the pixmask flag to use.
- [x] `QuantityMixIn.masked` should use `DONOTUSE` instead of masking everything > 0.

**Comment by bretthandrews** [comment]
`Map.masked` masked out spaxels with the `NOCOV`, `UNRELIABLE`, and `DONOTUSE` bits set, which was Kyle's recommendation, so `QuantityMixIn.masked` should do the same to avoid changing the behavior of this attribute.
