### ISSUE TITLE
Tests failing because of updated stellar_sigmacorr message

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#508]
The following tests seem to fail because the error message for the stellar_sigmacorr in ML-6 has changed. I'm not sure if this has been there for a while or is the result of some regression due to a recent merge.

- python/marvin/tests/tools/test_map.py:202 TestMap.test_stellar_sigma_values[MPL-6-SPX-GAU-MILESHC-8485-1901-local-nodb]
- python/marvin/tests/tools/test_map.py:202 TestMap.test_stellar_sigma_values[MPL-6-SPX-GAU-MILESHC-8485-1901-remote-nodb]
- python/marvin/tests/tools/test_map.py:202 TestMap.test_stellar_sigma_values[MPL-6-SPX-GAU-MILESHC-8485-1901-auto-nodb]
- python/marvin/tests/tools/test_map.py:409 TestMapArith.test_stellar_sigma_correction_MPL4[MPL-6-SPX-GAU-MILESHC-8485-1901]
- python/marvin/tests/tools/test_map.py:202 TestMap.test_stellar_sigma_values[MPL-6-HYB10-GAU-MILESHC-8485-1901-local-nodb]
- python/marvin/tests/tools/test_map.py:202 TestMap.test_stellar_sigma_values[MPL-6-HYB10-GAU-MILESHC-8485-1901-remote-nodb]
- python/marvin/tests/tools/test_map.py:202 TestMap.test_stellar_sigma_values[MPL-6-HYB10-GAU-MILESHC-8485-1901-auto-nodb]
- python/marvin/tests/tools/test_map.py:409 TestMapArith.test_stellar_sigma_correction_MPL4[MPL-6-HYB10-GAU-MILESHC-8485-1901]

**Comment by havok2063** [comment]
Whoops, sorry about that.  I didn't update the tests after I changed the string message that was raised.  This is fixed in the recent pushes to `master`.
