### ISSUE TITLE
Tick values don't adjust when skycoords=True

### ISSUE THREAD

**Issue by astromariarosa** [sdss/marvin#510]
**Describe the bug**
When plotting a map with sky_coords set to True, the tick values are not correct, and seem to just represent spaxel offset, not arcsec offset.

**To Reproduce**
import matplotlib.pyplot as plt
from marvin.tools.maps import Maps
maps = Maps(plateifu='8623-9102')
dn4000 = maps['specindex_dn4000']
spx_snr = maps['spx_snr']
mask_snr = (spx_snr.value < 5) * dn4000.pixmask.labels_to_value('DONOTUSE')

dn4000.plot(sky_coords=True, mask=mask_snr, title=r'$D_n 4000$', cmap='rainbow', cblabel=r'$\AA$')
plt.show()

**Expected behavior**
From reading the documentation, the internal set_extent function should center the spaxel coordinates and multiply by 0.5 to convert to arcsec offset when sky_coords=True. 

**Screenshots**
When sky_coords=True:
![marvin-sky_coords](https://user-images.githubusercontent.com/29264471/43788155-be2c25d6-9a3a-11e8-93ae-d8b9aa02e526.png)

When sky_coords=False:
![marvin-spaxels](https://user-images.githubusercontent.com/29264471/43788175-c8fdfa3e-9a3a-11e8-9253-64f563be481e.png)

**Desktop (please complete the following information):**
 - OS: OS X 10.11.6
 - Browser: Chrome, Jupyter Notebook
 - Version: Marvin version 2.2.5

**Comment by bretthandrews** [comment]
Hi @astromariarosa!

Thank you very much for finding this bug and reporting it!

Cheers,
Brett

**Comment by bretthandrews** [comment]
Divide arcsec by 2 since the spaxel width is 0.5 arcsec.
