### ISSUE TITLE
Add credits for StringFolder?

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#514]
I'm not sure but it seems `StringFolder` and `string_folding_wrapper` were copied from somewhere but they are not credited. If that's the case we should. I'm also not sure it can work since an import for `intern` is missing and it would only work in Python 2 because it uses a `basestring`.

**Comment by havok2063** [comment]
We can credit it.  I'll look up where I found it.  As for the Python 3 issues with `intern` and `basestring`, those have been fixed in the `queryopt` branch.  

Also, have you stared at my code long enough to know when it wasn't me?  What gave it away or is this a new VS Code extension?

**Comment by albireox** [comment]
It sticks with 79-character lines and uses double quotes for docstrings ... so yes, I have stared at your code long enough to know what it isn't you.

**Comment by havok2063** [comment]
This has been added in PR #485.
