### ISSUE TITLE
Can't load map using Maps

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#520]
**Describe the bug**

Error when loading a map using Maps in marvin tools

**To Reproduce**
Steps to reproduce the behaviour:

maps = Maps(plateifu='7443-12703')

**Expected behaviour**

To get the map without any message

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari] (if the issue is related to Marvin Web)
 - Version of Marvin [e.g. 2.0.2]
2.2.6

**Additional context**

maps = Maps(plateifu='7443-12703')

home/hector/.local/lib/python3.7/site-packages/sdss_marvin-2.3.0.dev0-py3.7.egg/marvin/tools/mixins/mma.py:139: MarvinUserWarning: local mode failed. Trying remote now.
  warnings.warn('local mode failed. Trying remote now.', MarvinUserWarning)
/home/hector/.local/lib/python3.7/site-packages/sdss_marvin-2.3.0.dev0-py3.7.egg/marvin/__init__.py:323: MarvinUserWarning: Cannot retrieve URLMap. Remote functionality will not work: Requests Connection Error: HTTPSConnectionPool(host='dr15.sdss.org', port=443): Max retries exceeded with url: /api/marvin/api/general/getroutemap?release=DR15 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)')))
  MarvinUserWarning)

**Comment by albireox** [comment]
I think this is a known issue that has showed up before. @havok2063 may know better.

**Comment by havok2063** [comment]
So, there's this in the error message.  `/home/hector/.local/lib/python3.7/site-packages/sdss_marvin-2.3.0.dev0-` and `/api/marvin/api/general/getroutemap?release=DR15`.  This is a development version of marvin that is not running on the server.  This version will not be ready until we officially announce it.  Or prepare for the vetting.   Everyone should be using marvin version `2.2.6`.  I think we can close this for now.
