### ISSUE TITLE
Problem with Map/Spec view on the web

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#521]
**Describe the bug**
The Map/Spec view on the web doesn't show anything and it appears an error message:
Error : Error: Could not get spaxel: Multiple rows were found for one()

**To Reproduce**
Steps to reproduce the behaviour:
- go to the web, use MPL-7
- go to 7443-12703

**Expected behaviour**
the spectrum and maps should display

**Screenshots**

![screenshot from 2018-08-23 11-00-34](https://user-images.githubusercontent.com/7560892/44530037-ed028900-a6c3-11e8-9da2-9f05ff5bb4e2.png)

**Desktop (please complete the following information):**
OS X, Ubuntu
 - Browser [e.g. chrome, safari] (if the issue is related to Marvin Web) 
Firefox, Safari, Chrome
 - Version of Marvin [e.g. 2.0.2]
2.2.6

**Comment by havok2063** [comment]
Thanks, María.  Looking into this it seems there are galaxies with duplicate spaxel entries loaded into the database for MPL-7 compared to MPL-6.  I'll need to look further into to identify which galaxies and clean it out.

**Comment by havok2063** [comment]
There were ~2600 galaxies that had duplicate spaxel and rss fiber information loaded.  Additionally there were 12 galaxies that had no fiber information loaded.  I have cleaned out the database of duplicates and loaded the missing data.  I've done some checks and the cube, spaxel, and maps, and models count for MPL-7 matches expected counts from files and MPL-6.   Closing this.
