### ISSUE TITLE
No SDSS image in Marvin Web

### ISSUE THREAD

**Issue by karenlmasters** [sdss/marvin#522]
I don't see the SDSS image (and hexagon) in Marvin web. This has been persistent for a while. Happens with Map/Specview either on or off. Screenshots are attached. 

<img width="1205" alt="screen shot 2018-08-27 at 10 44 51" src="https://user-images.githubusercontent.com/4124677/44666380-3f0a1e00-a9e6-11e8-94ed-b9f468411c15.png">
<img width="583" alt="screen shot 2018-08-27 at 10 44 09" src="https://user-images.githubusercontent.com/4124677/44666381-40d3e180-a9e6-11e8-850a-d9812f914dbf.png">

Using Firefox on OS 10.13.3 (High Sierra).

**Comment by havok2063** [comment]
Hi @karenlmasters, this is a Firefox issue.  Recent Firefox versions have changed how they handle authentication, or at least the authentication to data.sdss.org needed to get the images.  It no longer prompts to authenticate.  To get around this, you can manually navigate to any location on the SAS and authenticate.  Then Firefox should work.  Chrome and Safari browsers both work fine.

**Comment by havok2063** [comment]
Closing this.
