### ISSUE TITLE
web spaxel view broken for HYB10 defaults when central region is masked.  

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#523]
**Describe the bug**
The dynamic spaxel explorer for 8936-12705 for MPL-7 produces an error about incorrect binid.  

`Error : Error: Could not get spaxel: coordinates (37, 37) do not correspond to a valid binid.
`
**To Reproduce**
1. Go to https://sas.sdss.org/marvin2/galaxy/8936-12705/
2. Click on Map/Spec View
3. See error

**Expected behavior**
It displays correctly for MPL-6.  MPL-7 should work the same.  

<img width="1769" alt="8937-12705_mpl7" src="https://user-images.githubusercontent.com/1836302/44735938-cc6b7200-aabb-11e8-8011-89189d0f82e1.png">

**Additional context**
This may be related to the recent database issues with duplicate/missing spaxels.

**Comment by havok2063** [comment]
Looking into this, I don't think this is a real bug.  This is an issue with default Maps in MPL-7 begin the `HYB10` scheme.  The central RA, DEC converts to coord [37, 37] which does not have a corresponding bin id.  This HYB call for MPL-6 also fails.  The crash for grabbing a spaxel from a cube the call to  `cube.getSpaxel` also tries to get the maps and models properties, and then fails.  The web works in MPL-6 because the default bintype is `SPX`.  I think the solution here is to call `getSpaxel` for the web with `properties=False`.  This will at least return the original spaxel.  But I will be unable to grab any of the maps or modelcube properties for the `HYB` binnings.  Maybe this is a problem only in `2.2.6` with the old binning code.

**Comment by havok2063** [comment]
Well, I got this error once in the web.  I consistently get the error regarding the binid with the Tools.  However the web now magically works for MPL-7 for this galaxy.  In a fresh browser.  So this needs reproduction.

**Comment by havok2063** [comment]
So this is and is not a bug.  The issue here is that this galaxy has its central region masked out.  See the attached image.  This prevents the original dynamic explorer to load.  Since `HYB10` is now the default, we should change the web viewer so it 

1. can always safely grab the unbinned spaxel regardless of the maps/models properties
2. can always safely fail or plot the model fit and maps.  

Does this require any change to `cube.getSpaxel` or `cube.getMaps` and `maps.getMap` ?

<img width="1754" alt="8937-12705_mpl6" src="https://user-images.githubusercontent.com/1836302/44735768-5c5cec00-aabb-11e8-9932-398f58610bf2.png">

**Comment by albireox** [comment]
Is this still a problem? Checking with the version in `lore` it seems there is no crash and the central spaxel is displayed correctly. There is no model fit but that's correct, I think, since the spaxel is masked out. Was this a problem with the previous implementation of Bin that is now fixed?

**Comment by havok2063** [comment]
This may have been a problem with the previous implementation of Bin that is now fixed.  It seems ok now in `lore`.  We can probably close this for now.
