### ISSUE TITLE
7443-12701 displays gray maps in web for MPL-7

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#532]
**Describe the bug**
7443-12701 displays blank gray maps in the web for MPL-7 

**To Reproduce**
1. Using the `vetround2` branch, in web for MPL-7
2. Go to the galaxy page for 7443-12701
3. Click on Map/Spec View
4. Maps are gray

**Expected behavior**
It shows the proper maps

**Screenshots**

<img width="1590" alt="screen shot 2018-10-04 at 1 28 01 am" src="https://user-images.githubusercontent.com/1836302/46454625-0c85da80-c775-11e8-9ac3-a9a8dd0e5a0c.png">

**Addtional Context**
I checked the same thing with the Tools and maps display correctly.

**Comment by bretthandrews** [comment]
<img width="1343" alt="screen shot 2018-10-04 at 10 26 41 am" src="https://user-images.githubusercontent.com/12723826/46481349-349b2b00-c7c1-11e8-954e-0ef5c0c0d828.png">

It worked for me

**Comment by havok2063** [comment]
can you try this locally with the `vetround2` branch?

**Comment by bretthandrews** [comment]
I get gray maps locally

**Comment by havok2063** [comment]
Ok.  that's what I get as well.

**Comment by albireox** [comment]
If you're using the local database from SAS I think that file does not contain the HYB10 for 7443-12701. It does contain the VOR10 and that displays fine. So I think this is a non issue.
