### ISSUE TITLE
Elliptical Coordinates in Web Query Drop Down

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#533]
**Is your feature request related to a problem? Please describe.**
I want to search on elliptical coordinates.

**Describe the solution you'd like**
Add the following properties to the web query drop down:
`spaxelprop.spx_ellcoo_elliptical_azimuth`
`spaxelprop.spx_ellcoo_elliptical_radius`
`spaxelprop.spx_ellcoo_r_re`

**Comment by havok2063** [comment]
This has been implemented but is turned off while spaxel queries are disabled.  Whenever they get turned back on, these should now be available in the dropdown.
