### ISSUE TITLE
Add downloadList dltype='modelcube'

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#538]
**Describe the bug**
There is no modelcube option for `downloadList`.

**Expected behavior**
```
from marvin.utils.general import downloadList
downloadList(['8485-1901'], dltype='modelcube')
```
Downloads modelcubes.

**Comment by bretthandrews** [comment]
Related to #536 and #537.

**Comment by albireox** [comment]
Closing as per PR #576
