### ISSUE TITLE
BrainError: No URL Map found. Cannot make remote call

### ISSUE THREAD

**Issue by KateRowlands** [sdss/marvin#544]
I don't know whether I've got something messed up in my python environment (I upgraded marvin and followed all the instructions) but I keep getting the same error from the marvin brain whenever I try to use any tools:

import marvin
my_cube = marvin.tools.Cube('7443-12703')
my_cube

Produces:

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/tools/mixins/mma.py:139: MarvinUserWarning: local mode failed. Trying remote now.
  warnings.warn('local mode failed. Trying remote now.', MarvinUserWarning)
//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/__init__.py:326: MarvinUserWarning: Cannot retrieve URLMap. Remote functionality will not work: a bytes-like object is required, not 'str'
  MarvinUserWarning)
---------------------------------------------------------------------------
BrainError                                Traceback (most recent call last)
<ipython-input-32-2481cc75b7e4> in <module>()
      1 import marvin
----> 2 my_cube = marvin.tools.Cube('7443-12703')
      3 my_cube

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/tools/cube.py in __init__(self, input, filename, mangaid, plateifu, mode, data, release, drpall, download, nsa_source)
     76             self._load_cube_from_db(data=self.data)
     77         elif self.data_origin == 'api':
---> 78             self._load_cube_from_api()
     79 
     80         self._init_attributes(self)

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/tools/cube.py in _load_cube_from_api(self)
    235         """Calls the API and retrieves the necessary information to instantiate the cube."""
    236 
--> 237         url = marvin.config.urlmap['api']['getCube']['url']
    238 
    239         try:

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/core/core.py in __missing__(self, key)
     35 
     36         if len(self.keys()) == 0:
---> 37             raise BrainError('No URL Map found. Cannot make remote call')
     38         else:
     39             raise BrainError('Key {0} not found in urlmap.'.format(key))

BrainError: No URL Map found. Cannot make remote call

**Comment by KateRowlands** [comment]
Due to incorrect .netrc setup.

**Comment by bretthandrews** [comment]
@KateRowlands Thanks for reporting back about the underlying issue!
