### ISSUE TITLE
Crash when using Maps

### ISSUE THREAD

**Issue by KateRowlands** [sdss/marvin#545]
maps = Maps(mangaid='1-209232') 

produces:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-e60cd60ec0a6> in <module>()
----> 1 maps = Maps(mangaid='1-209232')

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/tools/maps.py in __init__(self, input, filename, mangaid, plateifu, mode, data, release, drpall, download, nsa_source, bintype, template, template_kin)
     97                                   mangaid=mangaid, plateifu=plateifu,
     98                                   mode=mode, data=data, release=release,
---> 99                                   drpall=drpall, download=download)
    100 
    101         NSAMixIn.__init__(self, nsa_source=nsa_source)

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/tools/core.py in __init__(self, input, filename, mangaid, plateifu, mode, data, release, drpall, download)
    116         MMAMixIn.__init__(self, input=input, filename=filename, mangaid=mangaid,
    117                           plateifu=plateifu, mode=mode, data=data, release=release,
--> 118                           download=download)
    119 
    120         # drop breadcrumb

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/tools/mixins/mma.py in __init__(self, input, filename, mangaid, plateifu, mode, data, release, drpall, download, ignore_db)
    116         self._forcedownload = download if download is not None else config.download
    117 
--> 118         self._determine_inputs(input)
    119 
    120         assert self.mode in ['auto', 'local', 'remote']

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/tools/mixins/mma.py in _determine_inputs(self, input)
    185             self.plateifu = mangaid2plateifu(self.mangaid,
    186                                              drpall=self._drpall,
--> 187                                              drpver=self._drpver)
    188 
    189         elif self._plate:

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/utils/general/general.py in mangaid2plateifu(mangaid, mode, drpall, drpver)
    328     """
    329 
--> 330     from marvin import config, marvindb
    331     from marvin.api.api import Interaction
    332 

ImportError: cannot import name 'marvindb'

I am using the public version of Marvin but collab produces the same result, and with MPL-7.

**Comment by KateRowlands** [comment]
Due to incorrect .netrc setup.

**Comment by bretthandrews** [comment]
@KateRowlands Thanks for the update!
