### ISSUE TITLE
Update docs to reflect change in Query searchfilter kwarg

### ISSUE THREAD

**Issue by KateRowlands** [sdss/marvin#547]
myfilter = 'nsa.z < 0.1'

# create a query
query = Query(searchfilter=myfilter)
results = query.run()

produces:

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/tools/query.py:236: MarvinUserWarning: No local database found. Cannot perform queries.
  warnings.warn('No local database found. Cannot perform queries.', MarvinUserWarning)
//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/tools/query.py:226: MarvinUserWarning: local mode failed. Trying remote now.
  warnings.warn('local mode failed. Trying remote now.', MarvinUserWarning)
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py in _checkResponse(self, response)
    197         try:
--> 198             isbad = response.raise_for_status()
    199         except requests.HTTPError as http:

//anaconda/envs/msaviz/lib/python3.6/site-packages/requests/models.py in raise_for_status(self)
    934         if http_error_msg:
--> 935             raise HTTPError(http_error_msg, response=self)
    936 

HTTPError: 422 Client Error: UNPROCESSABLE ENTITY for url: https://lore.sdss.utah.edu/public/marvin/api/query/cubes/

During handling of the above exception, another exception occurred:

BrainError                                Traceback (most recent call last)
//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/tools/query.py in _run_remote(self, start, end, query_type)
    355         try:
--> 356             ii = Interaction(route=url, params=self._remote_params, stream=True, datastream=self.return_all)
    357         except Exception as e:

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py in __init__(self, route, params, request_type, auth, timeout, headers, stream, datastream, send)
     53         if self.url and send:
---> 54             self._sendRequest(request_type)
     55         elif not self.url and send:

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py in _sendRequest(self, request_type)
    289             # Check the response if it's good
--> 290             self._checkResponse(self._response)
    291 

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py in _checkResponse(self, response)
    220                 self._closeRequestSession()
--> 221                 raise BrainError('Requests Http Status Error: {0}\nValidation Errors:\n{1}'.format(http, json_data))
    222             else:

BrainError: Requests Http Status Error: 422 Client Error: UNPROCESSABLE ENTITY for url: https://lore.sdss.utah.edu/public/marvin/api/query/cubes/
Validation Errors:
{'validation_errors': {'searchfilter': ['Missing data for required field.']}}

During handling of the above exception, another exception occurred:

MarvinError                               Traceback (most recent call last)
<ipython-input-75-ee5568721bca> in <module>()
      4 # create a query
      5 query = Query(searchfilter=myfilter)
----> 6 results = query.run()

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/tools/query.py in run(self, start, end, query_type)
    313 
    314         if self.data_origin == 'api':
--> 315             results = self._run_remote(start=start, end=end, query_type=query_type)
    316         elif self.data_origin == 'db':
    317             results = self._run_local(start=start, end=end, query_type=query_type)

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/tools/query.py in _run_remote(self, start, end, query_type)
    356             ii = Interaction(route=url, params=self._remote_params, stream=True, datastream=self.return_all)
    357         except Exception as e:
--> 358             raise MarvinError('API Query call failed: {0}'.format(e))
    359         else:
    360             # retrive and set some parameters

MarvinError: API Query call failed: Requests Http Status Error: 422 Client Error: UNPROCESSABLE ENTITY for url: https://lore.sdss.utah.edu/public/marvin/api/query/cubes/
Validation Errors:
{'validation_errors': {'searchfilter': ['Missing data for required field.']}}.
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.

**Comment by KateRowlands** [comment]
Incorrect documentation - 'searchfilter' should be 'search_filter'

**Comment by bretthandrews** [comment]
Occurences of "searchfilter" littered throughout documentation.

**Comment by bretthandrews** [comment]
Fixed in e03f1483

**Comment by bretthandrews** [comment]
Also converted `returnparams` to `return_params` in b986c26a
