### ISSUE TITLE
Query tries to use wrong release version

### ISSUE THREAD

**Issue by KateRowlands** [sdss/marvin#552]
release MPL-6
making remote call to /public/marvin/api/query/getallparams/ MPL-6
length of keys 1676
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-2b678633f6ef> in <module>()
----> 1 from marvin.tools.query import Query
      2 
      3 # search for galaxies with an NSA redshift < 0.1
      4 myfilter = 'nsa.z < 0.1'
      5 

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/tools/query.py in <module>()
     25 from marvin.core import marvin_pickle
     26 from marvin.core.exceptions import MarvinError, MarvinUserWarning
---> 27 from marvin.tools.results import Results, remote_mode_only
     28 from marvin.utils.general import temp_setattr
     29 from marvin.utils.datamodel.query import datamodel

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/tools/results.py in <module>()
     29 from marvin.tools.modelcube import ModelCube
     30 from marvin.tools.rss import RSS
---> 31 from marvin.utils.datamodel.query import datamodel
     32 from marvin.utils.datamodel.query.base import ParameterGroup
     33 from marvin.utils.general import (downloadList, get_images_by_list, map_bins_to_column, temp_setattr,

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/utils/datamodel/query/__init__.py in <module>()
     12 
     13 from .base import QueryDataModelList
---> 14 from .MPL import MPL4, MPL5, MPL6, MPL7, DR15
     15 
     16 mpllist = [MPL4, MPL5, MPL6, MPL7, DR15]

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/utils/datamodel/query/MPL.py in <module>()
     44 EX6 = set(EX5) - set(['obsinfo', 'dapall'])
     45 
---> 46 MPL6 = QueryDataModel(release='MPL-6', groups=groups(), aliases=['MPL6', 'v2_3_1', '2.1.3'], exclude=EX6, dapdm=datamodel['MPL-6'])
     47 
     48 # MPL-7

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/utils/datamodel/query/base.py in __init__(self, release, groups, aliases, exclude, **kwargs)
     55         self.bitmasks = get_maskbits(self.release)
     56         self._mode = kwargs.get('mode', config.mode)
---> 57         self._get_parameters()
     58         self._check_datamodels()
     59 

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/utils/datamodel/query/base.py in _get_parameters(self)
     87             else:
     88                 self._mode = 'remote'
---> 89             self._get_parameters()
     90 
     91     def _get_from_remote(self):

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/utils/datamodel/query/base.py in _get_parameters(self)
     81             self._cleanup_keys()
     82         elif self._mode == 'remote':
---> 83             self._get_from_remote()
     84         elif self._mode == 'auto':
     85             if config.db:

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/utils/datamodel/query/base.py in _get_from_remote(self)
    122                 PARAM_CACHE.update(ii.getData())
    123                 self._check_aliases()
--> 124                 for key in PARAM_CACHE.keys():
    125                     self._keys = PARAM_CACHE[key] if key in PARAM_CACHE else []
    126                     print('length of keys', len(self._keys))

RuntimeError: dictionary changed size during iteration

Steps for reproduction:

from marvin import config
from marvin.tools.query import Query

myfilter = 'nsa.z < 0.1'
query = Query(search_filter=myfilter)

print(config.release)
>> DR15

Similar crashes (but with switching to MPL-4 were happening with Maps).

If the code is run again then the crash doesn't happen.

**Comment by havok2063** [comment]
I think this is fixed with recent changes to how the Query DataModel gets populated.  I went back to making per release API calls rather than a single API call to grab all releases.  For now, this eliminates the in-place modification of the `PARAM_CACHE` which looks like the underlying error here.  I tested this in a clean, nodb, DR15 zone and feel safe closing this.
