### ISSUE TITLE
Query does not return correct parameters if they are not in the filter

### ISSUE THREAD

**Issue by KateRowlands** [sdss/marvin#553]
**Describe the bug**
Running a query with parameters in params not in the filter does not return the parameters.

**To Reproduce**
```
filter = 'spaxelprop.emline_gflux_oi_6302>0. and nsa.elpetro_mass > 1E9'

params = ['spaxelprop.emline_gflux_oi_6302', 'spaxelprop.emline_gflux_ha_6564']

q = Query(search_filter=filter, returnparams=params, limit=1000)
r = q.run()

r.columns.display
['Manga-ID',
 'Plate-IFU',
 'Emline_Gflux_Oi_6302',
 'Elpetro_Mass',
 'Spaxel X',
 'Spaxel Y',
 'Bintype',
 'Template']
```

**Expected behavior**
Returns results, including spaxelprop.emline_gflux_ha_6564.

**Comment by havok2063** [comment]
This is due to a syntax error in `q = Query(search_filter=filter, returnparams=params, limit=1000)
`.  The new syntax is `q = Query(search_filter=filter, return_params=params, limit=1000)`

**Comment by havok2063** [comment]
In principle, it could be removed.  I may be passing in other keywords via `doQuery` and the query API calls that aren't explicitly set in the Query init.  That shouldn't be the case but maybe.  I'll have to look back into it.

**Comment by havok2063** [comment]
I've removed the `kwargs` argument from Query.  There was one issue found with an unaccounted for kwarg when getting a full column.  So far no other issues with `kwargs` have shown up.  The tests still pass.  I found additional bugs regarding paginating remote results when doing this which I've fixed.  I think it's safe to closing this for now.
