### ISSUE TITLE
typo in Galaxy Tools documentation

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#561]
Bug report from Kate Rowlands. 

**Describe the bug**
Typo in "The data is delivered as quantities with attached variance and mask, as well ass associated properties."

**To Reproduce**
1. Go to Galaxy Tools section in docs

**Expected behavior**
No typo

**Comment by albireox** [comment]
Well, that's embarrassing. Fixed in 982e393699647bbc273e073bd039ae50ae433021
