### ISSUE TITLE
Documentation: Lean tutorial deprecation error with Marvin 2.3.0dev

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#562]
**Describe the bug**

Deprecation error when running Lean tutorial with Marvin 2.3.0dev

**To Reproduce**
1. spax = galaxies[0].getSpaxel(x=28, y=24, xyorig='lower', model=True)

**Additional context**

MarvinDeprecationError                    Traceback (most recent call last)
<ipython-input-23-3dc8769d194c> in <module>()
----> 1 spax = galaxies[0].getSpaxel(x=28, y=24, xyorig='lower', model=True)

~/anaconda/envs/python3/lib/python3.6/site-packages/marvin/tools/maps.py in getSpaxel(self, x, y, ra, dec, drp, models, model, **kwargs)
    567         if model is not None:
    568             raise marvin.core.exceptions.MarvinDeprecationError(
--> 569                 'the model parameter has been deprecated. Use models.')
    570 
    571         return marvin.utils.general.general.getSpaxel(

MarvinDeprecationError: the model parameter has been deprecated. Use models.
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.

**Comment by bretthandrews** [comment]
Fixed!
