### ISSUE TITLE
matpltolib version

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#569]
We have `matplotlib` pinned to `2.2.2`. Do we really need that specific version or can we change it to `matplotlib>=2.2.2`?

**Comment by havok2063** [comment]
Where is that pinned?  In the `requirements.txt`, I see `matplotlib>=1.5.3`

**Comment by bretthandrews** [comment]
I was having problems building on RTD, but if it's working then go ahead and relax it

**Comment by albireox** [comment]
Fixed in 32a6ebb6e6489d8c0c8f663ba0821ed2a289fda9
