### ISSUE TITLE
Crash when loading remote ModelCube

### ISSUE THREAD

**Issue by KateRowlands** [sdss/marvin#578]
from marvin.tools.modelcube import ModelCube
from marvin import config

plateifu_sel = '7443-6102'

config.mode = 'auto'
config.download = True
config.setRelease('DR15')
cc = ModelCube(plateifu_sel)

cc.binned_flux

**produces**

---------------------------------------------------------------------------
MarvinError                               Traceback (most recent call last)
<ipython-input-30-8a7db41c0f26> in <module>()
     15 cc = ModelCube(plateifu_sel)
     16 
---> 17 cc.binned_flux

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/tools/modelcube.py in binned_flux(self)
    567                         mask=binned_flux_mask,
    568                         redcorr=self._redcorr,
--> 569                         binid=self.get_binid(model),
    570                         unit=model.unit,
    571                         pixmask_flag=model.pixmask_flag)

//anaconda/envs/msaviz/lib/python3.6/site-packages/marvin/tools/modelcube.py in get_binid(self, model)
    543             if response.results['error'] is not None:
    544                 raise MarvinError('found a problem while getting the binid from API: {}'
--> 545                                   .format(str(response.results['error'])))
    546 
    547             binid_map_data = np.array(response.getData()['binid'])

MarvinError: found a problem while getting the binid from API: cannot make a list of Quantities.  Get list of values with q.value.list().
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.

**Comment by albireox** [comment]
Hi @KateRowlands. Thanks for sending this one. I think this is the same as #548, which is already fixed but not yet released.
