### ISSUE TITLE
Impossible to load from file if MANGA_LOCALHOST not set

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#579]
**Describe the bug**
It seems that if you don't have `MANGA_LOCALHOST=1` set the local mode always fails to use the file, even if it exists and is in the right location.

**To Reproduce**
1. Unset any `MANGA_LOCALHOST` envvar.
2. Run the code

```python
In [1]: import marvin
INFO: No release version set. Setting default to DR15

In [3]: my_cube = marvin.tools.Cube('7443-12701')
/Users/albireo/Documents/Repo/manga/marvin/python/marvin/tools/mixins/mma.py:139: MarvinUserWarning: local mode failed. Trying remote now.
  warnings.warn('local mode failed. Trying remote now.', MarvinUserWarning)

In [4]: my_cube
Out[4]: <Marvin Cube (plateifu='7443-12701', mode='remote', data_origin='api')>
```

**Expected behavior**
`my_cube` should have been opened from a file.

**Additional context**
This problem happens because when not using `MANGA_LOCALHOST=1` `getDbMachine` returns `None`, which sets `config.db=None` which in turn lefts `marvindb=None`. When the MMA is called, `mma.py:273` fails when calling `testDbConnection(marvindb.session)`. As a result, if `mode='auto'`, the local mode fails even if the file exists.

On a related note, if `MANGA_LOCALHOST` is not set, doing `forceDbOff()` fails with an ugly message:

```python
In [2]: marvin.config.forceDbOff()

AttributeError                            Traceback (most recent call last)
<ipython-input-2-ba019a917ab3> in <module>
----> 1 marvin.config.forceDbOff()

~/Documents/Repo/manga/marvin/python/marvin/__init__.py in forceDbOff(self)
    567         config.db = None
    568         from marvin import marvindb
--> 569         marvindb.forceDbOff()
    570
    571     def forceDbOn(self):

AttributeError: 'NoneType' object has no attribute 'forceDbOff'
```

**Comment by havok2063** [comment]
We never changed the input to the MMA so that `marvin.tools.Cube('7443-12701')` pulls from files.  I think you still have to specify `filename` explicitly.  I think it's trying to do what it's supposed to.  It recognizes the plateifu and goes into remote mode since there is no db.  

Regarding the `config.forceDbOff`, in principle no one without a db should be using it, but this was a big change to remove the `marvindb` from the code and set it to `None`.  It's no wonder I missed some places where it's called.

**Comment by albireox** [comment]
No, according to our [decision tree](https://sdss-marvin.readthedocs.io/en/stable/_images/Mode_Decision_Tree.png), if we a plate-ifu, there is no DB but the file exist, we open the file. This is what I think we have always assumed it would happen, anyway. I think it's not difficult to fix but I don't want to add a hack that breaks things somewhere else since I don't know everything `marvindb` is used for.

The `forceDbOff` is not a big issue. Just would be nicer for it to fail with a more descriptive message.

**Comment by havok2063** [comment]
Yeah, you're right.  Changing the code so all db stuff is ignored introduced more problems than it solved.  Just to shave off import times.   It worked ok when `marvindb` was still initialized but empty.  `marvindb` is used and imported everywhere.  Now that it is `None` those imports and usages need to be addressed.  It looks like this code in `mma._doLocal` needs to be patched.  This might work...

```
            from marvin import marvindb
            if marvindb:
                testDbConnection(marvindb.session)

            if marvindb and marvindb.db and not self._ignore_db:
                self.mode = 'local'
                self.data_origin = 'db'   
```

**Comment by albireox** [comment]
Yeah, that was my guess. I tested that yesterday and it doesn't seem to produce any problem but I didn't run the tests.

**Comment by havok2063** [comment]
This is now fixed.  I'll just note here that DR15 has a different sas directory path than MPL-7.   So you may find it still accesses things remotely.  In that case, check that you've copied the files into the right path.
