### ISSUE TITLE
Error when identifyng unique bins in Marvin tools tutorial (WP)

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#582]
**Describe the bug**

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-20-a19e14fa01fe> in <module>()
      3 my_map = Maps('7443-12703', bintype='HYB10')
      4 binid_kin = my_map.binid_stellar_continua
----> 5 __, unique_indices = numpy.unique(binid_kin, return_index=True)

~/anaconda/envs/python3/lib/python3.6/site-packages/numpy/lib/arraysetops.py in unique(ar, return_index, return_inverse, return_counts, axis)
    221     ar = np.asanyarray(ar)
    222     if axis is None:
--> 223         return _unique1d(ar, return_index, return_inverse, return_counts)
    224     if not (-ar.ndim <= axis < ar.ndim):
    225         raise ValueError('Invalid axis kwarg specified for unique')

~/anaconda/envs/python3/lib/python3.6/site-packages/numpy/lib/arraysetops.py in _unique1d(ar, return_index, return_inverse, return_counts)
    283         ar.sort()
    284         aux = ar
--> 285     flag = np.concatenate(([True], aux[1:] != aux[:-1]))
    286 
    287     if not optional_returns:

ValueError: all the input arrays must have same number of dimensions

**To Reproduce**
from marvin.tools.maps import Maps
import numpy
my_map = Maps('7443-12703', bintype='HYB10')
binid_kin = my_map.binid_stellar_continua
__, unique_indices = numpy.unique(binid_kin, return_index=True)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] osx
 - Browser [e.g. chrome, safari] safari
 - Version [e.g. 22] Marvin 2.3.0dev

**Additional context**

The tutorial can be found here:
https://testng.sdss.org/dr15/manga/manga-tutorials/marvin-tutorial/marvin-tools/

**Comment by albireox** [comment]
I'll have a look.

**Comment by havok2063** [comment]
SInce this is relevant for the Word Press documentation and today is the last day for the WP docs to be in place according to Anne-Marie, this should be fixed by today.

**Comment by margudo** [comment]
I'm accessing remotely with `sasurl https://lore.sdss.utah.edu/public/`
Maybe is just me, it works for you and worked for Amy when she checked the tutorials

**Comment by albireox** [comment]
It would be good to understand why it doesn't work for you. Can you try again and send the output of running

```python
from marvin.tools.maps import Maps
import numpy
my_map = Maps('7443-12703', bintype='HYB10')
binid_kin = my_map.binid_stellar_continua
print(my_map)
print(binid_kin)
print(binid_kin.value)
```

**Comment by margudo** [comment]
`>>> print(my_map)
<Marvin Maps (plateifu='7443-12703', mode='remote', data_origin='api', bintype='HYB10', template='GAU-MILESHC')>
>>> print(binid_kin)
[[-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 ...
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]]
>>> print(binid_kin.value)
[[-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 ...
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]]
`

**Comment by margudo** [comment]
`<Marvin Maps (plateifu='7443-12703', mode='remote', data_origin='api', bintype='HYB10', template='GAU-MILESHC')>
[[-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 ...
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]]
[[-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 ...
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]]`

**Comment by albireox** [comment]
Mmm. So, you do get the map with the correct data. The problem seems to be in numpy when doing the unique. There is a similar issue [here](https://gis.stackexchange.com/questions/191227/numpy-unique-valueerror-all-the-input-arrays-must-have-same-number-of-dimensio). Not sure if it's the same problem.

What version of numpy are you using? Can you also try doing

```python
from marvin.tools.maps import Maps
import numpy
my_map = Maps('7443-12703', bintype='HYB10')
binid_kin = my_map.binid_stellar_continua
__, unique_indices = numpy.unique(numpy.array(binid_kin.value), return_index=True)
```

**Comment by margudo** [comment]
I can run that without any problem
I'm using numpy '1.14.2'

**Comment by margudo** [comment]
Problem solved updating numpy!
Closing

**Comment by albireox** [comment]
Sure. You can try with 

```python
from marvin.tools.maps import Maps
import numpy
my_map = Maps('7443-12703', bintype='HYB10')
binid_kin = my_map.binid_stellar_continua
__, unique_indices = numpy.unique(binid_kin.value, return_index=True)
```

and see if that works. In principle, `binid_kin` and `binid_kin.value` should work the same; the former is just a numpy array with extra attributes. But it seems numpy is having problems with it ...

I think it's still worth updating the WP to be sure it works for everybody.

**Comment by margudo** [comment]
WP updated! Thanks!

Please have a look to the last code of the tutorial, I'm having error (see docs slack channel)
