### ISSUE TITLE
Brain error in authentication

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#585]
**Describe the bug**

brain.core.exceptions.BrainError: Key login not found in urlmap.

**To Reproduce**

>>> from marvin import config
INFO: No release version set. Setting default to DR15
/Users/maria/anaconda/envs/python3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
>>> config.release
'DR15'
>>> config.access = 'collab'
>>> config.setRelease('MPL-7')
>>> 
>>> config.login()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/maria/anaconda/envs/python3/lib/python3.6/site-packages/marvin/__init__.py", line 709, in login
    url = self.urlmap['api']['login']['url']
  File "/Users/maria/anaconda/envs/python3/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/core/core.py", line 39, in __missing__
    raise BrainError('Key {0} not found in urlmap.'.format(key))
brain.core.exceptions.BrainError: Key login not found in urlmap.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] OSX
 - Version [e.g. 22] Marvin 2.3.0dev

**Additional context**

**Comment by havok2063** [comment]
If `login` isn't in the `urlmap` list of available routes, that most likely means it is set using the wrong `sasurl`.  Check that `config.sasurl` is set to use `lore.sdss.utah.edu`.  If it's not you need to set up your marvin to use the test servers instead.

**Comment by margudo** [comment]
Closing
The problem is fixed setting `config.sasurl` to use `lore.sdss.utah.edu`
