### ISSUE TITLE
MarvinError: No URL Map found.  Cannot make remote query calls!.

### ISSUE THREAD

**Issue by mmckay18** [sdss/marvin#595]
**Describe the bug**
When I try to run: 
q0, r0 = doQuery(search_filter='radial(198.189117, 46.934990, 0.01)')

I get the following error:
MarvinError: No local database found.  Query cannot be run in local mode.

MarvinError: No URL Map found.  Cannot make remote query calls!.

I ran the same code last week but I did not get this error and I did not make any changes to my conda environment.

**To Reproduce**
Steps to reproduce the behaviour:
1. run from marvin.tools.query import doQuery
2. run q0, r0 = doQuery(search_filter='radial(198.189117, 46.934990, 0.01)')

3. Get error:
/Users/mmckay/conda/envs/astroconda/lib/python3.6/site-packages/marvin/tools/query.py:236: MarvinUserWarning: No local database found. Cannot perform queries.
  warnings.warn('No local database found. Cannot perform queries.', MarvinUserWarning)
/Users/mmckay/conda/envs/astroconda/lib/python3.6/site-packages/marvin/__init__.py:331: MarvinUserWarning: Cannot retrieve URLMap. Remote functionality will not work: Requests Connection Error: HTTPSConnectionPool(host='dr15.sdss.org', port=443): Max retries exceeded with url: /marvin/api/general/getroutemap?release=DR15&compression=json (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))
  MarvinUserWarning)
/Users/mmckay/conda/envs/astroconda/lib/python3.6/site-packages/marvin/__init__.py:332: ResourceWarning: unclosed <socket.socket fd=64, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('2601:602:9e80:523c:dce6:823a:8618:ae64', 50197, 0, 0), raddr=('2001:1948:414:13::80', 443, 0, 0)>
  self.urlmap = URLMapDict()
---------------------------------------------------------------------------
MarvinError                               Traceback (most recent call last)
~/conda/envs/astroconda/lib/python3.6/site-packages/marvin/tools/query.py in _set_mma(self)
    223             try:
--> 224                 self._do_local()
    225             except MarvinError as e:

~/conda/envs/astroconda/lib/python3.6/site-packages/marvin/tools/query.py in _do_local(self)
    236             warnings.warn('No local database found. Cannot perform queries.', MarvinUserWarning)
--> 237             raise MarvinError('No local database found.  Query cannot be run in local mode')
    238         else:

MarvinError: No local database found.  Query cannot be run in local mode.
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.

During handling of the above exception, another exception occurred:

MarvinError                               Traceback (most recent call last)
<ipython-input-7-b0549778d749> in <module>()
     11 
     12 #Query MaNGA galaxies
---> 13 q0, r0 = doQuery(search_filter='radial(198.189117, 46.934990, 0.01)')
     14 q1, r1 = doQuery(search_filter='radial(132.912735, 57.107433, 0.01)')
     15 q2, r2 = doQuery(search_filter='radial(163.219131, 43.428398, 0.01)')

~/conda/envs/astroconda/lib/python3.6/site-packages/marvin/tools/query.py in doQuery(**kwargs)
     67     end = kwargs.pop('end', None)
     68     query_type = kwargs.pop('query_type', None)
---> 69     q = Query(**kwargs)
     70     try:
     71         res = q.run(start=start, end=end, query_type=query_type)

~/conda/envs/astroconda/lib/python3.6/site-packages/marvin/tools/query.py in __init__(self, search_filter, return_params, return_type, targets, quality, mode, return_all, default_params, nexus, sort, order, caching, limit, count_threshold, verbose, release)
    189 
    190         # define the Query MMA
--> 191         self._set_mma()
    192 
    193         # initialize a query

~/conda/envs/astroconda/lib/python3.6/site-packages/marvin/tools/query.py in _set_mma(self)
    225             except MarvinError as e:
    226                 log.debug('local mode failed. Trying remote now.')
--> 227                 self._do_remote()
    228 
    229         # Sanity check to make sure data_origin has been properly set.

~/conda/envs/astroconda/lib/python3.6/site-packages/marvin/tools/query.py in _do_remote(self)
    244 
    245         if not config.urlmap:
--> 246             raise MarvinError('No URL Map found.  Cannot make remote query calls!')
    247         else:
    248             self.mode = 'remote'

MarvinError: No URL Map found.  Cannot make remote query calls!.
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.

**Expected behaviour**
query and retrieve data

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Mojave version 10.14.2
 - Browser [e.g. chrome, safari] (if the issue is related to Marvin Web)
 - Version of Marvin [e.g. 2.0.2] - 2.3.0

**Additional context**

**Comment by havok2063** [comment]
Hi @mmckay18.  I tried loading up marvin in my own environment and I'm having a similar issue.
```
from marvin import config
config.urlmap
/Users/Brian/anaconda2/envs/marvindev/lib/python3.5/site-packages/marvin/__init__.py:331: MarvinUserWarning: Cannot retrieve URLMap. Remote functionality will not work: Requests Connection Error: HTTPSConnectionPool(host='dr15.sdss.org', port=443): Max retries exceeded with url: /marvin/api/general/getroutemap?release=DR15&compression=json (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))
  MarvinUserWarning) 
```
I think there is an issue with the SSL certificates for the `dr15.sdss.org` domain.  I get the same problem when trying a standard http request

```
import requests
requests.get('https://dr15.sdss.org/flipper')
SSLError: HTTPSConnectionPool(host='dr15.sdss.org', port=443): Max retries exceeded with url: /flipper (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))
```

I will need to reach out to the IT people at Utah to fix the problem.  I'll report back once it is solved.

**Comment by havok2063** [comment]
@mmckay18 The SSL certificate issue I think has been fixed.  Can you please try again?  I will try to implement something to detect if this happen and ensure a cleaner exit and more verbose error message .

**Comment by havok2063** [comment]
This has been fixed.
