### ISSUE TITLE
conda env create -f marvin_2.3.0_env.yml. Error

### ISSUE THREAD

**Issue by qiqiw960223** [sdss/marvin#596]
Hi, I just installed Marvin using the pip command and whenever I try to use any of the marvin tools, I get "BrainError: No URL Map found. Cannot make remote call". (As below)

![image](https://user-images.githubusercontent.com/46541623/51700141-ff1a8780-1fd3-11e9-8feb-be4de99ef24b.png)
![image](https://user-images.githubusercontent.com/46541623/51700187-1f4a4680-1fd4-11e9-9a8f-92c6fc88c795.png)

I tried to go back and see if I did something wrong or missed something during setup, and realized that I could not do "conda env create -f marvin_2.3.0_env.yml." on the installation instruction page, and keep getting the error "SpecNotFound: Can't process without a name", when I try to setup the conda environment. Is there a link missing on the installation page for setting up the conda environment? (there is a "link here" in the paragraph about setting up the environment, but there is no link.)

Thanks!

**Comment by havok2063** [comment]
Hi @qiqiw960223 Can you try again to use any of the Marvin Tools?  We were having a problem with out SSL certificates for the d15.sdss.org domain name.  This problem caused all remote use of the Tools to break temporarily.  I think it has been fixed now.  Local use of the Tools for files would still work.   Let me know if this works for you now.     

Yeah, you're right, the link on in the installation documentation is not up to date with the conda environment information.  Thanks for noticing that.  I forgot about it.  I will update that soon.

**Comment by qiqiw960223** [comment]
Thanks! I confirm that Marvin Tools work for me now!
