### ISSUE TITLE
Web Query

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#627]
**Describe the bug**
Error generating webtable: __init__() got an unexpected keyword argument 'returnparams'

**To Reproduce**
1. Go to https://sas.sdss.org/marvin/search/
2. Search for "nsa.sersic_logmass >= 10 and nsa.sersic_logmass <= 11"
3. See error: Error generating webtable: __init__() got an unexpected keyword argument 'returnparams'

**Screenshots**
<img width="1099" alt="screen shot 2019-02-06 at 12 58 54 pm" src="https://user-images.githubusercontent.com/12723826/52362788-50cd0400-2a0f-11e9-903c-422ead833f4c.png">

**Comment by havok2063** [comment]
Fixed in 2.3.2
