### ISSUE TITLE
Make marvin use pip-installable version of sdss-access and tree

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#644]

**Comment by havok2063** [comment]
In principle, I agree with this.  However, I make regular enough changes to `tree` and `sdss_access` for Marvin where I don't want to fully tag a new public release for these products every time I'm making changes or small updates.  I like having marvin depend on a more flexible version of these products.  I think we can hash out a good workflow though that satisfies both conditions.

**Comment by havok2063** [comment]
Completed.
