### ISSUE TITLE
Add most common spectral lines in the observed frame in marvin-web

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#648]
**Is your feature request related to a problem? Please describe.**
Because the web plot shows spectra in the observed frame it's not always easy to identify spectral features.

**Describe the solution you'd like**
Add an option to overlay the main spectral lines (those from the DAP) on top of the plot and shifted to the observed frame. This could also be added as an option for the tools plots.

**Describe alternatives you've considered**
Could be implemented along with #112.

**Comment by havok2063** [comment]
This has been implemented and merged into 2.3.5 for MPL-9
