### ISSUE TITLE
I could not use python code using Marvin after SDSS-Marvin update.

### ISSUE THREAD

**Issue by mj-astrotoy** [sdss/marvin#654]
**Describe the bug**
I could not use my python code using Marvin library after I updated marvin.

I got following error massage.
`"MarvinError: DRP version v2_3_1 not found in lookup table. No associated MPL version. Should one be added?  Check for typos."`

I tested the location causing this error with run the code line by line.
When I called Maps in the following simple part of code (third line), the error was made.
I use 'maps' files from sdss, located in local environment. 
(I am not using marvin server to get data.)

```
from marvin.tools.maps import Maps
pname="7957-6102"
maps = Maps(filename='./data/manga-'+pname+'-MAPS-SPX-GAU-MILESHC.fits.gz') 
```

**Comment by havok2063** [comment]
Hi @mj-astrotoy Can you tell me which version of marvin you are using?  You can find out by doing 
```
import marvin
marvin.__version__
```
Certain MPLs are only supported in certain versions of Marvin?   The error message indicates an MPL-6 version number.  Is the version of the file you are loading also from MPL-6?

**Comment by mj-astrotoy** [comment]
Thank you so much your help.

Return of "marvin.__version__"
'2.3.2'

I am using 2.3.2 marvin version. The error would be caused because I use manga map files of MPL-6. 
So, I tried to load map file of MPL-8 with my current marvin. I got the following massage.
"MarvinError: DRP version v2_5_3 not found in lookup table. No associated MPL version. Should one be added?  Check for typos."
I thought the current version of marvin can deal with MPL-8 data. It's not working in my marvin version.

Anyway, I want to open my targets with marvin (I don't need MPL-8 for now). 
Can I call the previous version of marvin in code? If not, should I re-install the previous version of marvin?

Thanks for your help again.

**Comment by havok2063** [comment]
Hmm.  Can you tell me how you installed marvin?  And what operating system you are using?

**Comment by mj-astrotoy** [comment]
I used pip install. And I recently updated it with "pip install -U sdss-marvin" which was suggested in SDSS email from Brian ("MPL-8 DAP products and Marvin 2.3.2 now available", I got this email at March 1). I am using marvin in my macbook (version 10.14.3). In my computer, I installed "anaconda" tools a long time ago. But I don't use anaconda to work the manga data with Marvin.

**Comment by havok2063** [comment]
Hmm. Ok.  I can't seem to recreate the error using marvin 2.3.2 in collab mode.  I can recreate the error when using marvin in public mode.   So you may be running marvin in `access='public'` mode. 

Can you do 
```
from marvin import config
config.access
config.release
```
and tell me what it says.   If `config.access` says `"public"` then you are configured only for public data, and will be unable to view MPL data.  If that's the case, you can follow the instructions [here](https://sdss-marvin.readthedocs.io/en/latest/installation.html#sdss-collaboration-access) on how to set up marvin for collaboration access.

**Comment by mj-astrotoy** [comment]
In [15]: from marvin import config
In [16]: config.access
Out[16]: 'public'
In [17]: config.release
Out[17]: 'DR15'

Oh, my marvin is running pubilic mode! Thank you so much!

**Comment by havok2063** [comment]
No problem!  Glad it's an easy fix.
