### ISSUE TITLE
Unexpected units in ModelCube

### ISSUE THREAD

**Issue by zpace** [sdss/marvin#658]
I noticed that ModelCubes have unexpected units for the fit arrays. Since the TRM specifies, for instance, that the units of `dap_logcube['STELLAR']` are `1e-17 erg/s/cm2/angstrom/spaxel`, I anticipated that a ModelCube would have the same thing. Instead, the unit `Angstrom-1` is omitted. This stems from the [MPL-8 datamodel](https://github.com/sdss/marvin/blob/master/python/marvin/utils/datamodel/dap/MPL8.py)

This prevents, for example, subtracting the stellar-continuum fits from the DRP LOGCUBE. Simply plotting both the DRP LOGCUBE flux alongside the DAP stellar fit without their units does not indicate that there was any unit transformation under-the-hood (if it were so, the DRP and DAP stellar fits would diverge as wavelength changed, yes?)

Here's an example:

```
>>> dap_logcube = marvin.tools.modelcube.ModelCube('7960-12705')
>>> dap_logcube.stellarcont_fit.unit
Unit("1e-17 erg / (cm2 s spaxel)")
```

For the time being, I can can simply operate on the unitless arrays, but could you confirm whether this is intended behavior?

**Desktop (please complete the following information):**
 - OS: Linux (OpenSuSE)
 - `marvin.__version__`: 2.3.2

**Comment by havok2063** [comment]
@zpace Thanks for pointing this out.  This indeed looks like a bug.  Going far back as MPL-5 ModelCubes.  I double-checked the TRMs for MPL5-8 and the DAP files for MPL-6 and 8 and `Angstroms` are indeed a part of the unit.  It doesn't look like an MPL-8 change.  It's a bug in our DAP DataModel.  I'll do some checking to make sure that's the case and make this fix.

**Comment by kbwestfall** [comment]
Just wanted to confirm that the model cube units shouldn't have changed in MPL-8.  Should still be per angstrom.

**Comment by havok2063** [comment]
Glad we caught this just 4 MPLs in...

**Comment by havok2063** [comment]
This has now been fixed and pushed into `master`.  It will be available on the next patch release of marvin.
