### ISSUE TITLE
SSL Error when trying to load Images

### ISSUE THREAD

**Issue by KiyoakiOmori** [sdss/marvin#659]
**Describe the bug**
As the title states, I get an SSL Error whenever I try to load a remote image

**To Reproduce**

**Expected behavior**
Simply Loading an image with Marvin's Image Utilities.

**Screenshots**
Error Code:

> ---------------------------------------------------------------------------
> Error                                     Traceback (most recent call last)
> ~/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname)
>     443             try:
> --> 444                 cnx.do_handshake()
>     445             except OpenSSL.SSL.WantReadError:
> 
> ~/anaconda3/lib/python3.6/site-packages/OpenSSL/SSL.py in do_handshake(self)
>    1805         result = _lib.SSL_do_handshake(self._ssl)
> -> 1806         self._raise_ssl_error(self._ssl, result)
>    1807 
> 
> ~/anaconda3/lib/python3.6/site-packages/OpenSSL/SSL.py in _raise_ssl_error(self, ssl, result)
>    1545         else:
> -> 1546             _raise_current_error()
>    1547 
> 
> ~/anaconda3/lib/python3.6/site-packages/OpenSSL/_util.py in exception_from_error_queue(exception_type)
>      53 
> ---> 54     raise exception_type(errors)
>      55 
> 
> Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
> 
> During handling of the above exception, another exception occurred:
> 
> SSLError                                  Traceback (most recent call last)
> ~/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
>     599                                                   body=body, headers=headers,
> --> 600                                                   chunked=chunked)
>     601 
> 
> ~/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
>     342         try:
> --> 343             self._validate_conn(conn)
>     344         except (SocketTimeout, BaseSSLError) as e:
> 
> ~/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py in _validate_conn(self, conn)
>     848         if not getattr(conn, 'sock', None):  # AppEngine might not have  `.sock`
> --> 849             conn.connect()
>     850 
> 
> ~/anaconda3/lib/python3.6/site-packages/urllib3/connection.py in connect(self)
>     355             server_hostname=hostname,
> --> 356             ssl_context=context)
>     357 
> 
> ~/anaconda3/lib/python3.6/site-packages/urllib3/util/ssl_.py in ssl_wrap_socket(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir)
>     358         if HAS_SNI and server_hostname is not None:
> --> 359             return context.wrap_socket(sock, server_hostname=server_hostname)
>     360 
> 
> ~/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname)
>     449             except OpenSSL.SSL.Error as e:
> --> 450                 raise ssl.SSLError('bad handshake: %r' % e)
>     451             break
> 
> SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
> 
> During handling of the above exception, another exception occurred:
> 
> MaxRetryError                             Traceback (most recent call last)
> ~/anaconda3/lib/python3.6/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
>     444                     retries=self.max_retries,
> --> 445                     timeout=timeout
>     446                 )
> 
> ~/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
>     637             retries = retries.increment(method, url, error=e, _pool=self,
> --> 638                                         _stacktrace=sys.exc_info()[2])
>     639             retries.sleep()
> 
> ~/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
>     397         if new_retry.is_exhausted():
> --> 398             raise MaxRetryError(_pool, url, error or ResponseError(cause))
>     399 
> 
> MaxRetryError: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr15/manga/spectro/redux/v2_4_3/7957/stack/images/3701.png (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
> 
> During handling of the above exception, another exception occurred:
> 
> SSLError                                  Traceback (most recent call last)
> <ipython-input-3-57d83f00325b> in <module>()
> ----> 1 image = Image(plateifu=str(plate)+'-'+str(ifu))
>       2 image.plot()
> 
> ~/anaconda3/lib/python3.6/site-packages/marvin/tools/image.py in __init__(self, input, filename, mangaid, plateifu, mode, data, release, download)
>      74             raise MarvinError('Images cannot currently be accessed from the db')
>      75         elif self.data_origin == 'api':
> ---> 76             self._load_image_from_api()
>      77 
>      78         # initialize attributes
> 
> ~/anaconda3/lib/python3.6/site-packages/marvin/tools/image.py in _load_image_from_api(self)
>     180         http = HttpAccess(verbose=False)
>     181         url = http.url("", full=filepath)
> --> 182         response = requests.get(url)
>     183         if not response.ok:
>     184             raise MarvinError('Error: remote filepath {0} does not exist'.format(filepath))
> 
> ~/anaconda3/lib/python3.6/site-packages/requests/api.py in get(url, params, **kwargs)
>      70 
>      71     kwargs.setdefault('allow_redirects', True)
> ---> 72     return request('get', url, params=params, **kwargs)
>      73 
>      74 
> 
> ~/anaconda3/lib/python3.6/site-packages/requests/api.py in request(method, url, **kwargs)
>      56     # cases, and look like a memory leak in others.
>      57     with sessions.Session() as session:
> ---> 58         return session.request(method=method, url=url, **kwargs)
>      59 
>      60 
> 
> ~/anaconda3/lib/python3.6/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
>     510         }
>     511         send_kwargs.update(settings)
> --> 512         resp = self.send(prep, **send_kwargs)
>     513 
>     514         return resp
> 
> ~/anaconda3/lib/python3.6/site-packages/raven/breadcrumbs.py in send(self, request, *args, **kwargs)
>     339             })
>     340         try:
> --> 341             resp = real_send(self, request, *args, **kwargs)
>     342         except Exception:
>     343             _record_request(None)
> 
> ~/anaconda3/lib/python3.6/site-packages/requests/sessions.py in send(self, request, **kwargs)
>     620 
>     621         # Send the request
> --> 622         r = adapter.send(request, **kwargs)
>     623 
>     624         # Total elapsed time of the request (approximately)
> 
> ~/anaconda3/lib/python3.6/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
>     509             if isinstance(e.reason, _SSLError):
>     510                 # This branch is for urllib3 v1.22 and later.
> --> 511                 raise SSLError(e, request=request)
>     512 
>     513             raise ConnectionError(e, request=request)
> 
> SSLError: HTTPSConnectionPool(host='data.sdss.org', port=443): Max retries exceeded with url: /sas/dr15/manga/spectro/redux/v2_4_3/7957/stack/images/3701.png (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
> 

**Desktop:**
 - OS: Ubuntu
 - Browser: Chrome (Jupyter Notebook)

**Comment by havok2063** [comment]
@KiyoakiOmori There was an issue yesterday with the SSL certificates at Utah.  Can you try this again?  If it still does not work, can you post the exact lines of code you are running, so we can attempt to reproduce the error?

**Comment by KiyoakiOmori** [comment]
@havok2063 
I ran the code again, it works perfectly fine now. Thank you for your help!
