### ISSUE TITLE
Can't download certain MPL-8 images

### ISSUE THREAD

**Issue by NickBfudd** [sdss/marvin#660]
**Describe the bug**
I am unable download images of two specific MPL-8 galaxies using the marvin Image tool, receiving the following error:

MarvinError: Error: remote filepath /Users/nicholasboardman/sas/mangawork/manga/spectro/redux/v2_5_3/9878/images/3703.png does not exist.

The returned file path is the same in both cases. The plate-IFU numbers of the two galaxies are 10493-3701 and 9878-3703. I am able to download images of other galaxies without issue

**To Reproduce**

```
import marvin
marvin.config.access = 'collab'
marvin.config.login(refresh=True)
marvin.config.setRelease('MPL-8')
from marvin.tools.image import Image
...
im = Image(mangaid = id,mode = 'remote')
```

The code crashes for manga-ids of 1-352102  and 1-457602; other manga-ids work without problems.

**Expected behaviour**
Images of the galaxies are downloaded, which I can then save to my computer

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS High Sierra Version 10.13.6
 - Version of Marvin: 2.3.2

**Additional context**

**Comment by havok2063** [comment]
@NickBfudd Is this related to your email on the mailing list?  Are these the same galaxies?

**Comment by NickBfudd** [comment]
@havok2063 1-352102 was one of the galaxies in the email on the mailing list, but 1-457602 is new. Btw, I had the plate-IFU numbers wrong in the original version of my original post; the numbers are 10493-3701 and 9878-3703, so the file path I'm getting relates to the latter.

**Comment by NickBfudd** [comment]
@havok2063 I have looked into this issue a little more, and I've noticed that the images for 1-457602 (plate-ifu 9878-3703) are missing on data.sdss.org. I'm guessing that this is the problem; 1-352102 now appears to be downloading without issue, so this is the only galaxy I still need an image for.

**Comment by havok2063** [comment]
@NickBfudd Can you try all these galaxies again and tell me if you are still having the same problem?

**Comment by havok2063** [comment]
Closing this.  Try updating to the latest version of marvin.  If this is still an issue with DR17 or MPL-11, we can open a new issue.
