### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by jakehlee** [sdss/marvin#664]
Super minor issue, there's a broken link to SDSS MaNGA docs on front page of the docs.

**To Reproduce**
1. Go to https://sdss-marvin.readthedocs.io/en/latest/
2. Scroll down to the first blue Note, "This documentation assumes that you are familiar with MaNGA data and its acronyms. If that is not your case, consider reading this."
3. Click on "this"
4. 404

**Expected behavior**
The link should go to https://www.sdss.org/dr15/manga/getting-started/ not https://www.sdss.org/manga/getting-started/

**Comment by albireox** [comment]
Thanks @jakehlee for reporting this! It's changed now in master and will become fixed in the docs when 2.3.3 gets released. You can see the latest documentation at https://sdss-marvin.readthedocs.io/en/latest/.
