### ISSUE TITLE
Sample Selection Tutorial has minor import error

### ISSUE THREAD

**Issue by astromariarosa** [sdss/marvin#670]
**Describe the bug**
Super duper minor, but [Sample Selection Tutorial](https://sdss-marvin.readthedocs.io/en/stable/tutorials/sample-selection.html) has an error.

**To Reproduce**
1. Go to [Sample Selection Tutorial](https://sdss-marvin.readthedocs.io/en/stable/tutorials/sample-selection.html)
2. After, "Let’s open the DRPall file:", code reads:
`from marvin.utils.general import get_drpall_table`
3. Running this yields error:
`ImportError: cannot import name 'get_drpall_table'`

**Expected behavior**
Code should read:
`from marvin.utils.general.general import get_drpall_table`

**Comment by havok2063** [comment]
Thanks for the catch.  We'll update this soon.

**Comment by havok2063** [comment]
This has been fixed by adding `get_drpall_table` to list of imports in __all__ in `marvin.utils.general.general.py`
