### ISSUE TITLE
Missing link to marvin_2.3.0_env.yml on Marvin Installation documentation page

### ISSUE THREAD

**Issue by ameliafm612** [sdss/marvin#675]
**Describe the bug**
Under the 'Quick Install' heading, the documentation says 'If you are using an Anaconda distribution of Python, you may use the following available conda environment, link here', but the link to marvin_2.3.0_env.yml is missing.

**To Reproduce**
Go to https://sdss-marvin.readthedocs.io/en/stable/installation.html
Under Installation: Quick Installation: link here

**Desktop (please complete the following information):**
 - CentOS 7
 - Chrome
 - Version of Marvin 2.3.0?

**Comment by ameliafm612** [comment]
@havok2063 Thanks for this. It kinda worked for marvin_2.3.2. The one issue I had was that conda couldn't use the .yml file, it got PackageNotFound errors (see attached screengrab). I fixed this by deleting the offending packages from the .yml file and trying again to create the environment. This seemed to work. This might be an obscure version of Linux problem though!

The only other comment I would make documentation-wise is you might want to make a note that you can't have any comments at the start of your .netrc file! I has a comment line starting with a #, and it didn't like that. The only reason I bring it up is I assumed a .netrc functioned in a similar manner to a .bashrc, so it took me a little while to figure out the error (I am pretty thick, though).

Marvin 2.3.2 now installed and working fine on a CentOS 7 machine!

![snapshot2](https://user-images.githubusercontent.com/40415417/64865698-ccd89b80-d631-11e9-9338-96c4d2049397.png)

**Comment by havok2063** [comment]
@ameliafm612 Thanks for this.  This is quite helpful.  It seems it dumped my exact environment to the yml file when what I really want is the external python package dependencies, and not any packages connected to specific installations of anaconda or python.  I'll clean up these environment files and try to streamline it a bit. 

Regarding the netrc file, do you know where it barfed?  Did you get a parsing error somewhere?  I tried adding a # comment on each line preceding my machine names and it seemed to still be readable.  However it does not seem to like putting comments inside machine blocks.

**Comment by ameliafm612** [comment]
![snapshot4](https://user-images.githubusercontent.com/40415417/65032251-af117c00-d93a-11e9-8fcd-ab2dc5f0b465.png)
Here is the offending .netrc. That said, I added the comment line back in and it seems to be working fine now... who knows. I'll keep using it, and let you know if there's any more issues. 
Thanks for your help!

**Comment by havok2063** [comment]
The link has been added back into the latest docs to be released soon.  It seems like everything else is working so far.  Closing this for now.
