### ISSUE TITLE
Fuzzy string matching in Maps.getMap() silently returns H-eta for 'H-beta' argument

### ISSUE THREAD

**Issue by zpace** [sdss/marvin#676]
I'm encountering some unexpected behavior with the fuzzy string-matching in `Maps.getMap`, where attempts to retrieve the **H-beta** flux instead return the **H-eta** flux. This seems like a super easy mistake to make for a beginner, so it may be good to document [here, along with the mention of fuzzy logic](https://sdss-marvin.readthedocs.io/en/latest/tools/maps.html#accessing-an-individual-map), or fix entirely.

**To Reproduce**
```python
import marvin.tools
dap_maps = marvin.tools.Maps('8083-12705', release='MPL-8', bintype='SPX', template='MILESHC-MILESHC')
print(dap_maps.getMap('emline_gflux', 'Hb-4861').datamodel.channel.name)
# 'hb_4862'
print(dap_maps.getMap('emline_gflux', 'H-beta').datamodel.channel.name)
# 'heta_3836'
```

Note that this case **does not** raise a `ValueError` (which is what happens when you pass `'H-zeta'`, for example).

**Suggested Fix(es)**

1. [In the docs](https://sdss-marvin.readthedocs.io/en/latest/tools/maps.html#accessing-an-individual-map), the text "Fuzzy key slicing works if the input is unambiguously associated with a particular key" should be explained further. Something like "Unexpected behavior can occur when the provided key is similar to several possible channels: for example, `'H-beta'` returns the channel `heta_3836`).
2. For each channel, have an additional list of keywords that are accepted unambiguously, and attempted before the fuzzy logic (i.e., use the fuzzy logic as a last resort if the channel input does not match any of a set of unambiguous keys)
3. If there's an ambiguity threshold below which an error or warning is raised, increase it; or warn the user when a couple channels match more or less equally closely.

**Desktop (please complete the following information):**
 - OS: Linux (OpenSUSE)
 - Version of Marvin: 2.3.2

**Comment by havok2063** [comment]
@zpace I agree we should probably standardize a response, either ambiguity or no match.  We currently do that if the fuzzy matching returns no result above the threshold or multiple results above the threshold.   It's a bit difficult for cases where the fuzzy matching returns a single match above the threshold, the match with the highest weight.  We take that as the choice, but there's no way to know if it's the "correct" choice.   This is the fuzzy matching library we are using.  https://github.com/seatgeek/fuzzywuzzy.  It has several options for scoring fuzziness.  Feel free to play around with it on some strings and see if you can improve our fuzzy matching.  For the parameter matching in our datamodels, we are using the `WRatio` scorer with a minimum score threshold of 75.  It will be hard to find a solution that works consistently for everything.  We can do our best but at some level it will be up to the user to use more accurate strings.     

Regarding shortcuts, this is currently something not quite implemented in a systematic way, and only in an ad-hoc fashion in `Query`.  This is an intriguing idea, and may be a way of fine-tuning the fuzzy matching.   Currently there's no way to set any shortcuts but we could expose the shortcuts in the config, or implement a system for user customization. 

Feel free to work on improving the documentation and submit a PR.  That'd be a great help.  I think we only discuss fuzziness buried in the individual Maps documentation.

**Comment by havok2063** [comment]
Closing this as the documentation update as been merged.
