### ISSUE TITLE
flagging bad spectra in marvin interactive browser

### ISSUE THREAD

**Issue by mabershady** [sdss/marvin#679]
**Describe the bug**

It is possible to display a spectrum with MapSpec View that has been flagged as bad in the DRP without directly knowing the spectrum is bad (no flags are given)
[Marvin | Galaxy.pdf](https://github.com/sdss/marvin/files/3637549/Marvin.Galaxy.pdf)

**To Reproduce**
Steps to reproduce the behavior: See the attached screen shot.

**Expected behaviour**

It is good to see the spectrum. It is also clear to me, as someone who is familiar with the data, that the unphysical spectrum that is displayed is in an area where the DAP does not return values. I can infer that there is a problem with the data, but I would have to start digging to figure this out.

My recommendation is to add a warning in the spectral plot when the data should not be used 'Do Not Use This Spectrum; See flags....' If a portion of the  spectrum (in wavelength) is ok, mark which portion is ok, and which isn't.

**Screenshots**
[Marvin | Galaxy.pdf](https://github.com/sdss/marvin/files/3637551/Marvin.Galaxy.pdf)

**Desktop (please complete the following information):**
 - OSX: 10.11.6
 - Browser : safari 11.1.2
 - Version of Marvin 2.3.2

**Additional context**

**Comment by havok2063** [comment]
This has been implemented and merged in 2.3.5 for MPL-9.
