### ISSUE TITLE
closing Maps file objects

### ISSUE THREAD

**Issue by zpace** [sdss/marvin#680]
This is maybe related to #396 

When looping through DAP Maps instances for a whole bunch of galaxies, I get `OSError: [Errno 24] Too many open files`. I was able to track down that the file objects are not being closed. This makes sense to me, because for each `Maps` object, there's an underlying HDUList that's being accessed which is never explicitly closed.

For a subclass of `Maps` that I have written, the `__enter__` and `__exit__` methods were one-liners, and I think they should be applicable to other classes in marvin (Cube, ModelCube, etc).

```python

class MarvinMaps(marvin.tools.Maps):

    def __enter__(self):
        return self

    def __exit__(self, type, value, traceback):
        self.data.close()

...
```

This makes `MarvinMaps` a context-manager, which meanse you can do stuff like:

```python

with MarvinMaps(plateifu) as marvin_maps:
    do_some_analysis(marvin_maps)

# file object automatically cleaned up
```

This seems to work, but is there something I'm missing? If not, would `marvin.tools.core.MarvinToolsClass` be the right place to put this?

**Comment by albireox** [comment]
This looks fine to me. Do you want to go ahead and write a PR? One think that you may need to add is a check to be sure the data is a `HDUList`. For example

```python
        if self.data_origin == 'file' and isinstance(self.data, astropy.io.fits.HDUList):
            try:
                self.data.close()
            except Exception as ee:
                warnings.warn('failed to close FITS instance: {0}'.format(ee), MarvinUserWarning)
```

You can have a look at `tools/core.py` in `__del__`. I think you want to add your context manager methods there, so that they apply to all base tool classes.

In principle, if a `Maps` object gets out of scope the `__del__` method should close the object. Are you creating your multiple `Maps` instance with different names, or in an array so that they always stay in the scope?

**Comment by zpace** [comment]
> In principle, if a Maps object gets out of scope the __del__ method should close the object. Are you creating your multiple Maps instance with different names, or in an array so that they always stay in the scope?

I am creating them in a loop... something like

```python
for plateifu in plateifus:
    dap_maps = Maps(plateifu, ...)
    do_some_extra_stuff(dap_maps)
```

By inspecting the open files, I could observe that the open file handlers corresponded to the completed loop iterations. So it appears that `__del__` is not closing the handler in this case.

I'll work on a PR to incorporate these changes.

**Comment by havok2063** [comment]
Generally I think this is a good idea.  It gives people the option of using a Marvin Tool as a context-manager.  So I encourage you to create a PR.  This is only really important when looping over large number of Maps.  Indeed I think it's related to #396.  This means that people will have to use this method in their scripts and loops, so we'll need to have some examples indicating how and when to use it as many people will not be familiar with this.    

I've thought about this as well in particular with the ongoing VAC improvements.  Another solution uses `io.BytesIo` to hold the file data in memory.  That way we can close the file immediately after we read it, but still access the full HDUList.  This should work fine for small numbers of files but for large numbers, we may also want to have a cleanup which clears the io stream from memory.
