### ISSUE TITLE
Adding link to DAP datamodel description in galaxy page

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#682]
**Is your feature request related to a problem? Please describe.**

The meaning of the DAP maps parameters in the galaxy page is not easy to find in the documentation or from the Marvin Web, and it would very helpful for people that is not familiar with MaNGA data products.

**Describe the solution you'd like**

Add a link to the DAP datamodel description in the galaxy page of the Marvin web.

**Describe alternatives you've considered**

**Additional context**

This request is motivated from a question received in the SDSS help desk from a MaNGA collaborator. (copied below)

> "Im sorry for asking this question. I do not find it evident where to look for the meaning of various parameters in the DAP Maps menu in the on-line version of Marvin. Can you tell me where I can find a description or meaning of each DAP Maps"
 
![Captura de pantalla 2019-10-10 a la(s) 11 36 48](https://user-images.githubusercontent.com/7560892/66603745-2fff1480-eb83-11e9-917b-ba47be1aa334.png)

**Comment by havok2063** [comment]
@margudo Thanks for this feedback.  This would be useful to add.  In the meantime, you could point the user to this page, https://www.sdss.org/dr15/manga/manga-data/data-model/#DataAnalysisPipelineOutput, and the maps datamodel, https://data.sdss.org/datamodel/files/MANGA_SPECTRO_ANALYSIS/DRPVER/DAPVER/DAPTYPE/PLATE/IFU/manga-MAPS-DAPTYPE.html, if you haven't already.

**Comment by margudo** [comment]
Thanks @havok2063 
I pointed the user to the description in the Marvin documentation https://sdss-marvin.readthedocs.io/en/stable/datamodel/datamodels.html but I'm realising now that maybe the description is not clear there and it would be better to go to the links you are suggesting. Maybe is also worthy to add those links to sdss documentation in the Marvin documentation.

**Comment by havok2063** [comment]
Thanks @margudo. The DAP properties in the datamodel link in the Marvin docs do have some descriptions in the table but they are hard to find. (You have to know to scroll horizontally.)  I think you're right that we need to improve the text on this page and add the more public DR15 links on the DR15 datamodel page.  The current Marvin datamodel documentation isn't very descriptive for new users.

**Comment by havok2063** [comment]
I've added a new pop up with links about various related info about DAP MAPs.  Will be merged for DR16 tag.
