### ISSUE TITLE
API authentication error

### ISSUE THREAD

**Issue by goyarzun** [sdss/marvin#683]
Unable to perform MPL-7 queries due to API authentication error.
[oyarzun.pdf](https://github.com/sdss/marvin/files/3816758/oyarzun.pdf)

**Comment by goyarzun** [comment]
I should add that I have the .netrc file in my home directory.

**Comment by havok2063** [comment]
Hi @goyarzun `marvin` now requires token authentication to access the API.  We made this change once we released marvin publicly with DR15.  See [here](https://sdss-marvin.readthedocs.io/en/stable/installation.html#sdss-collaboration-access) for information on how to set up `marvin` and authenticate to access MPL data.   This change occurred with `marvin` version `2.3.0`.     Let us know if you have any issues or questions.

**Comment by goyarzun** [comment]
Whoops, thanks for clarifying @havok2063
