### ISSUE TITLE
found a problem when checking if remote cube exists: Requests Connection Error: HTTPSConnectionPool(host='dr15.sdss.org', port=443): Read timed out.

### ISSUE THREAD

**Issue by ddzs1234** [sdss/marvin#690]
**Describe the bug**
![image](https://user-images.githubusercontent.com/57035405/70220013-d2510800-1780-11ea-8374-da9245c277f6.png)
I can't access remote cube data from dr15. 

**Desktop (please complete the following information):**
 - OS:Ubuntu 18.04
 - Browser : Firefox

**Comment by havok2063** [comment]
Hi @ddzs1234, the main site was down for a little while yesterday or a few days ago.  Can you try again?  Your code works for me.  One thing to keep in mind as well is that accessing the full `cube.flux` remotely over the API may take some time, especially for larger cubes.  If you're only interested in a few spaxels, it's faster to either slice `flux` and access only the spaxels you are interested in, or slice `cube` to access individual spaxels.  If you do need the full datacube, you can also try downloading the cube first and accessing it locally as a file.

**Comment by ddzs1234** [comment]
It works well now. thanks for your help!
