### ISSUE TITLE
marvin.core.exceptions.MarvinError: trying to set an invalid release version. Valid releases are: DR15

### ISSUE THREAD

**Issue by ddzs1234** [sdss/marvin#691]
**Describe the bug**
I can't access local data correctly.  when I tried to use the code below, marvin still points to $SAS_BASE_DIR+'/dr15/manga......'.
```
import marvin
import sys
from marvin.tools.cube import Cube

marvin.config.mode = 'local'

def access_data(plateifu):
    dir1='/media/ashley/project/mangawork/manga/spectro/redux/v2_5_3/'
    plate=plateifu.split('-')[0]
    ifu=plateifu.split('-')[1]
    print(plate,ifu)
    f=dir1+str(plate)+'/stack/'+'manga-'+plateifu+'-LOGCUBE.fits.gz'
    cube=Cube(filename=f)
    print(cube.header)
    
if __name__=='__main__':
    plateifu=sys.argv[1]
    access_data(plateifu)
```
![image](https://user-images.githubusercontent.com/57035405/70383719-a6669a00-19ad-11ea-97b9-1084976fd383.png)
I have no idea why I followed this code that 

Then I ADD ''marvin.config.setRelease('v2_5_3')", I got:
marvin.core.exceptions.MarvinError: trying to set an invalid release version. Valid releases are: DR15.

**Comment by havok2063** [comment]
@ddzs1234 Marvin requires a version match between the file you are trying to load and the release set by the `config`.  It looks like by default Marvin is set to use DR15 data but you are trying to load MPL-8 data.  You need to first set the release as MPL-8

```
marvin.config.setRelease('MPL-8')
cube = Cube(filename=...)
```
That said, we could probably make it fail a bit more cleanly when there's a version mismatch between Marvin and the file you are trying to access.  

Have a look [here](https://sdss-marvin.readthedocs.io/en/latest/installation.html#automatically-logging-in) to learn how to set up Marvin to automatically log in for collaboration access.  You can also try [here](https://sdss-marvin.readthedocs.io/en/latest/core/config.html#marvin-custom-yaml) to learn how to set the `default_release` attribute in your custom `marvin.yml` configuration file to MPL-8.

**Comment by havok2063** [comment]
Closing this.  Try updating to the latest version of marvin.  If it's still an issue, we can open a new ticket.
