### ISSUE TITLE
Image cutouts are not loading, regardless of login (public or private) and with Chrome and Safari.  Error message is: "Error: could not get images: sdss_access is not installed."

### ISSUE THREAD

**Issue by kbundy** [sdss/marvin#692]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] (if the issue is related to Marvin Web)
 - Version of Marvin [e.g. 2.0.2]

**Additional context**

**Comment by havok2063** [comment]
@kbundy Thanks for pointing this out.  We had an outdated version of `sdss_access`, the code used to grab images, installed on the lore, the machine where marvin is run.  It should be fixed now.
