### ISSUE TITLE
Marvin down

### ISSUE THREAD

**Issue by jacquelinegit** [sdss/marvin#705]
when accessing marvin through python I get the following, no matter which cube I am trying to load:

raise BrainError('No URL Map found. Cannot make remote call')
brain.core.exceptions.BrainError: No URL Map found. Cannot Make remote call.

So then I tried to go to marvin online ( https://dr15.sdss.org/marvin/ ) and got a 502 Bad Gateway

Any help or explanation appreciated! I am using MaNGA data for my Master's thesis. 

Thanks!
Jacqueline

**Comment by havok2063** [comment]
HI @jacquelinegit .  Marvin is down for the moment for database repair and maintenance.  So the API will not currently work.  We are actively working on setting up a mirror web site and hopefully aiming to get the database back up and running by the end of the week.

**Comment by jacquelinegit** [comment]
Thanks very much for the update!

**Comment by junohsu** [comment]
I tried to access MPL9 data with collab authority and got "BrainError: No URL Map found. Cannot make remote call" as well. Is Marvin still down currently? 

Also, would MPL9 accessible from Marvin web, or MPL10 accessible from Marvin package in the near future? 

Thank you,
Yun-Hsin

**Comment by stirfryannie** [comment]
Hi,
 
I'm also still recieving this error. Is the database still down? 

Stephanie

**Comment by havok2063** [comment]
Hi @junohsu @stirfryannie.  Yeah the database is still down but I'm doing the final cleanup of it now.  Once that is finished, I can restart things at Utah and MPL-9 will be available again.  Marvin should be back up in the next few days.  MPL-10 would become available shortly after that, once I can finish the loading process.

**Comment by junohsu** [comment]
Hi @havok2063 , thank you very much for the update!

**Comment by havok2063** [comment]
Hi @junohsu @stirfryannie @jacquelinegit , the main manga database at Utah is back up and running. You should have access to MPL-10 at Utah now via Marvin Web.  If you update to sdss-marvin 2.5.0 you should be able to access MPL-10 via the Python tools.  You should be able to make remote calls over the API again.
