### ISSUE TITLE
HTTPError(First time user)

### ISSUE THREAD

**Issue by wostling** [sdss/marvin#708]
I am using Juypter notebook.
When I run the following code:
```
from marvin.tools.maps import Maps
from marvin import config
config.access = 'public'
maps = Maps(plateifu='8485-1901')
print(maps)
# get an emission line map
haflux = maps.emline_gflux_ha_6564
values = haflux.value
ivar = haflux.ivar
mask = haflux.mask
haflux.plot()

```
The first error that this returns is:
```
HTTPError: 401 Client Error: UNAUTHORIZED for url: https://dr15.sdss.org/marvin/api/maps/8485-1901/HYB10/GAU-MILESHC/
```
Then I get the error:
```
BrainApiAuthError: API Authentication Error: Please check your authentication method.
```
And then finally this:
```
MarvinError: found a problem when checking if remote maps exists: API Authentication Error: Please check your authentication method.. 
```
I am quite new to this, and so I am not exactly sure what is going on. I installed Marvin through pip, and I just copied the code from a Marvin galaxy page. I added the lines
```
from marvin import config
config.access = 'public'
```
when I got an error, but they did not seem to solve anything. If someone could give step-by-step instructions about how to get this working, it would be great! Thanks in advance!

**Comment by havok2063** [comment]
@wostling Could you update your marvin to latest version, `2.5.0` and try again?  The error you were getting was related to some shuffling that was happening on the server-side while the database was down for maintenance.  Can you let me know if you're still having the same problem?

**Comment by wostling** [comment]
It works now! Thank you very much!
