### ISSUE TITLE
Marvin import problem

### ISSUE THREAD

**Issue by NoraMiau** [sdss/marvin#710]
**Describe the bug**
error when importing marvin new version

**To Reproduce**
import marvin

`NoSectionError                            Traceback (most recent call last)
<ipython-input-9-687634c49f91> in <module>
----> 1 import marvin
      2 from matplotlib import pyplot as plt
      3 from matplotlib import colors
      4 import numpy as np
      5 from matplotlib.colors import ListedColormap, LinearSegmentedColormap

c:\users\nosoc\appdata\local\programs\python\python38\lib\site-packages\marvin\__init__.py in <module>
    789 
    790 
--> 791 config = MarvinConfig()
    792 # up to here - time: 1.6 seconds
    793 

c:\users\nosoc\appdata\local\programs\python\python38\lib\site-packages\marvin\__init__.py in __init__(self)
    116 
    117         # setup some paths
--> 118         self._plantTree()
    119         self._checkSDSSAccess()
    120         self._check_manga_dirs()

c:\users\nosoc\appdata\local\programs\python\python38\lib\site-packages\marvin\__init__.py in _plantTree(self)
    676             self._tree = None
    677         else:
--> 678             self._tree = Tree(key='MANGA', config=tree_config)
    679 
    680     def _checkSDSSAccess(self):

c:\users\nosoc\appdata\local\programs\python\python38\lib\site-packages\tree\tree.py in __init__(self, *args, **kwargs)
     60         self.set_roots(uproot_with=uproot_with)
     61         self.load_config()
---> 62         self.branch_out(limb=self.key)
     63         # add the general directories
     64         if self.key is not None:

c:\users\nosoc\appdata\local\programs\python\python38\lib\site-packages\tree\tree.py in branch_out(self, limb)
    162             leaf = leaf if leaf in self._cfg.sections() else leaf.upper()
    163             self.environ[leaf] = OrderedDict()
--> 164             options = self._cfg.options(leaf)
    165 
    166             for opt in options:

c:\users\nosoc\appdata\local\programs\python\python38\lib\configparser.py in options(self, section)
    673             opts = self._sections[section].copy()
    674         except KeyError:
--> 675             raise NoSectionError(section) from None
    676         opts.update(self._defaults)
    677         return list(opts.keys())

NoSectionError: No section: 'GENERAL'`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Jupyter Notebook in Chrome
 - Version: Python 3, last marvin version

**Additional context**

**Comment by havok2063** [comment]
Hi @NoraMiau can you provide some more context on this?  What version of marvin are you using?  Are you using Anaconda for your Python installation?  Are you a member of the SDSS collaboration?   I can try to reproduce your error on Mac OS but I won't be able to fully reproduce your error since I don't have a machine with Windows 10.

**Comment by NoraMiau** [comment]
Hi! thanks for replying
well, de code was working until last sunday, then I update marvin to the last version (2.5.0) and the bug showed up. Now I can't import marvin...
I don't use anaconda and I'm not a member of the SDSS collaboration.
So, maybe is a Windows's issue?

**Comment by havok2063** [comment]
The error you are getting is in some of the dependencies of Marvin.  It could be Windows related, but could also be a bug with those dependencies introduced in the latest version of marvin.  I'll need to take a look.  In the meantime you should be able to go back to your previous version of marvin and things should still work.

**Comment by havok2063** [comment]
@NoraMiau Can you do the following in an python session and tell me what it says?
```
import tree
tree.__file__
```
It looks like you might be using a standalone package of sdss-tree. If that's the case can you try running `pip install -U sdss-tree` and `pip install -U sdss-access` and trying again?

**Comment by NoraMiau** [comment]
Hi!! Running `pip install -U sdss-tree` and `pip install -U sdss-access` solves the problem!! 
Thank you !!
