### ISSUE TITLE
Installation - check_marvin ValueError

### ISSUE THREAD

**Issue by astromariarosa** [sdss/marvin#717]
**Describe the bug**
Attempted to install Marvin on a new computer in a miniconda environment with collab access and .netrc files set up correctly. Marvin seemed to install without issues, but when I ran check_marvin, Marvin Checks threw a ValueError, which then caused an ImportError.

**To Reproduce**
>(astro) lovelace:~ mariarosamarinelli$ check_marvin

Output: 

System Checks
Your Python Version: 3.7.9
Full Version: 3.7.9 (default, Aug 31 2020, 07:22:35) 
[Clang 10.0.0 ]

OS Checks
Platform: darwin
Full info: posix.uname_result(sysname='Darwin', nodename='lovelace', release='20.1.0', version='Darwin Kernel Version 20.1.0: Sun Oct 18 15:32:00 PDT 2020; root:xnu-7195.41.8~9/RELEASE_ARM64_T8101', machine='x86_64')

Distribution Checks
Is Python from Anaconda or Miniconda? False

Package Checks
Numpy version: 1.19.5
Matplotlib version: 3.3.3
Your Matplotlib backend is MacOSX

Netrc Checks
Have a .netrc file? True
Netrc with permissions 600? True

Marvin Checks
[ERROR]: Traceback (most recent call last):
  File "/Users/mariarosamarinelli/miniconda3/envs/astro/bin/check_marvin", line 63, in <module>
    import marvin
  File "/Users/mariarosamarinelli/miniconda3/envs/astro/lib/python3.7/site-packages/marvin/__init__.py", line 36, in <module>
    NAME, config_file=os.path.join(curdir, 'data/marvin.yml'))
  File "/Users/mariarosamarinelli/miniconda3/envs/astro/lib/python3.7/site-packages/sdsstools/configuration.py", line 175, in get_config
    default_envvars=default_envvars)
  File "/Users/mariarosamarinelli/miniconda3/envs/astro/lib/python3.7/site-packages/sdsstools/configuration.py", line 212, in __init__
    self.load(config)
  File "/Users/mariarosamarinelli/miniconda3/envs/astro/lib/python3.7/site-packages/sdsstools/configuration.py", line 245, in load
    super().__init__(self._parse_config(config))
ValueError: dictionary update sequence element #0 has length 1; 2 is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mariarosamarinelli/miniconda3/envs/astro/bin/check_marvin", line 66, in <module>
    raise ImportError('Marvin cannot be imported! {0}\n{1}'.format(e, traceback))
ImportError: Marvin cannot be imported! dictionary update sequence element #0 has length 1; 2 is required
<traceback object at 0x7fbe094380a0>

**Expected behavior**
To the best of my ability, I've set this virtual environment to be identical to my previous environment, so I wasn't anticipating any issue with set up.

**Comment by havok2063** [comment]
@astromariarosa This looks like an issue with the `sdsstools` package.  In your environment, can you try upgrading it to the latest version, with `pip install -U sdsstools`, and see if that fixes it?

**Comment by astromariarosa** [comment]
check_marvin results in the same error readout after each of the following, in order:
1. updating sdsstools
2. restarting my computer
3. uninstalling sdsstools, restarting my computer, and reinstalling the most updated version of sdsstools
4. uninstalling Marvin, restarting my computer, and reinstalling Marvin.

Sorry for the trouble. Is this something I should open an sdsstools ticket for, or do you have any other ideas?

**Comment by havok2063** [comment]
what version of `marvin` and `sdsstools` are you using?  I'll see if I can recreate it.

**Comment by astromariarosa** [comment]
`sdsstools` Version 0.4.6
`sdss-marvin` Version 2.5.2

**Comment by havok2063** [comment]
Can you check in the location where conda installed marvin and make sure you have a `data/marvin.yml` file included?  If you installed in an environment, it should be something like `envs/[ENV_NAME]/lib/python3.7/site-packages/marvin`.  Can you also check if you have a valid user configuration file, most likely in `~/.marvin/marvin.yml`.    

what happens if you open up ipython and type the following without any extra keywords?
```
from sdsstools import get_config
get_config('marvin')
```

**Comment by astromariarosa** [comment]
Both files existed, but I made a typo when writing the user configuration file. Now that that's fixed, those lines in iPython are returning ` {'check_access': True, 'use_token': '', 'default_release': 'DR15'}`.  

`check_marvin` is returning warnings relating to the DRP/DAP directories because I haven't set those up yet, but everything else seems to be fine. 

Thank you for the help, sorry it was just user error!

**Comment by havok2063** [comment]
Excellent!  Glad to hear it's working now.  And no worries, half my problems stem from my own user error.  ;)  I'll go ahead and close this ticket.
