### ISSUE TITLE
No Results for Newest Marvin Release-Python

### ISSUE THREAD

**Issue by manduhmia** [sdss/marvin#718]
**Describe the bug**
Marvin's newest release not found and MPL not recognized. Trying to change release to MPL-10('v3_0_1'). 
Error code:

BrainError                                Traceback (most recent call last)
~/opt/anaconda3/lib/python3.7/site-packages/marvin/tools/cube.py in _load_cube_from_api(self)
    239         try:
--> 240             response = self._toolInteraction(url.format(name=self.plateifu))
    241         except Exception as ee:

~/opt/anaconda3/lib/python3.7/site-packages/marvin/tools/core.py in _toolInteraction(self, url, params)
    133         params = params or {'release': self._release}
--> 134         return marvin.api.api.Interaction(url, params=params)
    135 

~/opt/anaconda3/lib/python3.7/site-packages/brain/api/api.py in __init__(self, route, params, request_type, auth, timeout, headers, stream, datastream, send, base, verify)
     56         if self.url and send:
---> 57             self._sendRequest(request_type)
     58         elif not self.url and send:

~/opt/anaconda3/lib/python3.7/site-packages/brain/api/api.py in _sendRequest(self, request_type)
    294             # Check the response if it's good
--> 295             self._checkResponse(self._response)
    296 

~/opt/anaconda3/lib/python3.7/site-packages/brain/api/api.py in _checkResponse(self, response)
    258                 self._closeRequestSession()
--> 259                 raise BrainError('Something went wrong on the server side: {0}'.format(errorMsg))
    260 

BrainError: Something went wrong on the server side: Failed to retrieve cube 8314-6101: Could not retrieve cube for plate-ifu 8314-6101: No Results Found: No row was found for one().

**To Reproduce**
1. Go to https://sas.sdss.org/marvin/galaxy/8314-6101/ 
2. Click on 'Use this cube in Python'
3. Paste into Python and run code

**Expected behavior**
Download the newest version of Python to use the data from MPL-10.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version of Marvin *attempted 3.0.1

**Comment by havok2063** [comment]
Closing this as MPL-10 is no longer supported in the web or over remote API access. It still is available via local file mode in marvin.
