### ISSUE TITLE
Problem importin marvin in Python

### ISSUE THREAD

**Issue by espinozagaleas** [sdss/marvin#719]
I am new in Marvin. 
I am trying to use it in SciServer.
I followed instructions in Marvin doc to install it using PIP: pip install sdss-marvin.
Installation looks correct.
I restarted the kernel.
I do: ` import marvin `
I am getting the next error:

> ImportErrorTraceback (most recent call last)
> <ipython-input-3-04982d3355d3> in <module>
> ----> 1 from marvin.tools import Cube
> 
> ~/miniconda3/envs/py38/lib/python3.8/site-packages/marvin/__init__.py in <module>
>     773     os.environ['MARVIN_DIR'] = marvindir
>     774 
> --> 775 from marvin.api.api import Interaction
>     776 from marvin.api.base import arg_validate
>     777 
> 
> ~/miniconda3/envs/py38/lib/python3.8/site-packages/marvin/api/__init__.py in <module>
>       8 from brain.utils.general import build_routemap
>       9 from flask import current_app
> ---> 10 from flask_jwt_extended import fresh_jwt_required
>      11 from webargs import ValidationError, fields, validate
>      12 from webargs.flaskparser import parser, use_args, use_kwargs
> 
> ImportError: cannot import name 'fresh_jwt_required' from 'flask_jwt_extended' (/home/idies/miniconda3/envs/py38/lib/python3.8/site-packages/flask_jwt_extended/__init__.py)
> 

Clearly Marvin is not imported so I can not continue doing anything.

 - OS: CentOS 8
 - Browser: safari
 - Version: 14.0.3

**Comment by havok2063** [comment]
@espinozagaleas If you are using SciServer, `marvin` is already installed in an image you can use when creating new compute containers.   

- Log in to SciServer and access the "Compute" page from your dashboard
- click the "Create Container" button and add a new container name
- select the "Marvin" iamge from the "Compute Image" dropdown 
- Under "Data Volumes" section, select the following volumes:  "Getting Stated" and "MaNGA"

This will create a new compute container with Marvin installed, with access to the DR15 MaNGA dataset.  In general though for troubleshooting Sciserver, it's better to submit directly to their [Feedback and Bug form](https://www.sciserver.org/support/bug-report-and-suggestion-form/)

**Comment by SterlingYM** [comment]
I am also seeing the same error after installing Marvin with ```pip install sdss-marvin``` and try ```import marvin``` in Python.

**Comment by espinozagaleas** [comment]
> @espinozagaleas If you are using SciServer, `marvin` is already installed in an image you can use when creating new compute containers.
> 
> * Log in to SciServer and access the "Compute" page from your dashboard
> * click the "Create Container" button and add a new container name
> * select the "Marvin" iamge from the "Compute Image" dropdown
> * Under "Data Volumes" section, select the following volumes:  "Getting Stated" and "MaNGA"
> 
> This will create a new compute container with Marvin installed, with access to the DR15 MaNGA dataset. In general though for troubleshooting Sciserver, it's better to submit directly to their [Feedback and Bug form](https://www.sciserver.org/support/bug-report-and-suggestion-form/)

Thanks for your answer, now I am able to work in SciServer through the Marvin image. But this is a more general issue, not just for other images in SciServer. I was trying to install Marvin in my Mac and the problem was the same. I will appreciate if you can help me with this issue, I would like install it in my laptop for more mobility. Thanks again.

**Comment by havok2063** [comment]
@SterlingYM @espinozagaleas  It looks like it could be related to the `flask_jwt_extended` package.  It seems `4.0.0` introduced some breaking changes.  See https://flask-jwt-extended.readthedocs.io/en/stable/v4_upgrade_guide/.   Try downgrading `flask_jwt_extended` to the latest `3.x.x` version.

**Comment by SterlingYM** [comment]
Uninstalling Flask-JWT-Extended with
```pip uninstall flask-jwt-extended```
and then
```pip install flask-jwt-extended==3.25.1```
allowed successfully running
```python3 -c 'from flask_jwt_extended import fresh_jwt_required'```
and hence
```python3 -c 'import marvin'```
successfully. Thank you for the suggestion!

**Comment by espinozagaleas** [comment]
Thanks every body for your help. This issue is closed
