### ISSUE TITLE
Here is contents of new yml file (MARVIN 2.5.2.yml) works for Windows!! (in anaconda at least)

### ISSUE THREAD

**Issue by macster9** [sdss/marvin#723]
name: marvin
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - libffi=3.3
  - openssl=1.1.1h
  - pip=20.2.4
  - python=3.8.5
  - setuptools=50.3.1
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - appnope==0.1.0
    - astropy==4.2
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.2.1
    - chardet==3.0.4
    - click==7.1.2
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - docutils==0.16
    - dogpile-cache==0.7.1
    - entrypoints==0.3
    - fast-histogram==0.7
    - flask==1.1.2
    - flask-classful==0.14.2
    - flask-classy==0.6.10
    - flask-jwt-extended==3.25.0
    - future==0.18.2
    - fuzzywuzzy==0.17.0
    - idna==2.10
    - infinity==1.4
    - intervals==0.8.1
    - invoke==1.4.1
    - ipykernel==5.3.4
    - ipython==7.19.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - itsdangerous==1.1.0
    - jedi==0.17.1
    - jinja2==2.11.2
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.7
    - jupyter-console==6.2.0
    - jupyter-core==4.6.3
    - kiwisolver==1.3.0
    - markupsafe==1.1.1
    - marshmallow==2.19.5
    - matplotlib==3.3.2
    - mistune==0.8.4
    - mpl-scatter-density==0.6
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - networkx==2.5
    - notebook==6.1.4
    - numpy==1.19.2
    - packaging==20.4
    - pandas==1.1.3
    - pandocfilters==1.4.3
    - parso==0.7.0
    - passlib==1.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.0.1
    - prometheus-client==0.8.0
    - prompt-toolkit==3.0.8
    - ptyprocess==0.6.0
    - pygments==2.7.2
    - pyjwt==2.6.0
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - python-levenshtein==0.12.0
    - pytz==2020.1
    - pyyaml==5.3.1
    - pyzmq==19.0.2
    - qtconsole==4.7.7
    - raven==6.10.0
    - requests==2.24.0
    - requests-futures==1.0.0
    - scipy==1.5.2
    - sdss-marvin==2.5.0
    - sdsstools==0.3.1
    - semantic-version==2.8.5
    - send2trash==1.5.0
    - six==1.15.0
    - sqlalchemy==1.3.20
    - sqlalchemy-utils==0.34.1
    - terminado==0.9.1
    - testpath==0.4.4
    - tornado==6.0.4
    - tqdm==4.50.2
    - traitlets==5.0.5
    - urllib3==1.25.11
    - validators==0.13.0
    - wcwidth==0.2.5
    - webargs==5.4.0
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - wtforms==2.2.1
    - wtforms-components==0.10.4
    - yamlordereddictloader==0.4.0

**Comment by havok2063** [comment]
@macster9 Thanks for sharing this.  You can also try the latest 2.6.0 conda environment file here, https://anaconda.org/SDSS/marvin/files.

**Comment by havok2063** [comment]
Closing this.  A new conda environment for marvin 2.7.1 is out.
