### ISSUE TITLE
Error in retrieving API token

### ISSUE THREAD

**Issue by rlanggin** [sdss/marvin#728]
# login to receive a token
config.login()

# see token
config.token

MarvinError: Error getting login token. API Authentication Error: Please create or check credentials in your local .netrc file. .
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.

I am trying to use marvin to access SDSS collaboration proprietary data and have been having issues with getting a token for the API login from the .netrc file I created.

**Comment by InfinitelyCurious** [comment]
I am also having issues with this. Did you ever get it answered?

**Comment by havok2063** [comment]
Related to #744

**Comment by Kiddverified** [comment]
How can I get API Token?.??

**Comment by havok2063** [comment]
https://sdss-marvin.readthedocs.io/en/latest/installation.html#access-and-authentication

But everything is released publicly now.  You can avoid token by just accessing dr17.sdss.org/marvin or using the python Marvin in `config.access=public` mode, and setting the release to DR17.  

Going to go ahead and close this.
