### ISSUE TITLE
Installation Issue with pip

### ISSUE THREAD

**Issue by astrosteph** [sdss/marvin#741]
Hi, trying to simply pip install into python (version Python 3.7.0). 
Linux info:
 OS: CentOS Linux 7 (Core)
 Kernel: Linux 3.10.0-693.5.2.el7.x86_64

Pip checks some requirements and downloads some packages, gives a few errors: 

`ERROR: jinja2 3.0.1 has requirement MarkupSafe>=2.0, but you'll have markupsafe 1.0 which is incompatible.
ERROR: flask 2.0.1 has requirement Werkzeug>=2.0, but you'll have werkzeug 0.14.1 which is incompatible.
ERROR: sdsstools 0.4.13 has requirement packaging<21.0,>=20.4, but you'll have packaging 21.0 which is incompatible.
ERROR: sdsstools 0.4.13 has requirement six<2.0.0,>=1.14.0, but you'll have six 1.11.0 which is incompatible.
ERROR: flask-jwt-extended 3.25.1 has requirement Flask<2.0,>=1.0, but you'll have flask 2.0.1 which is incompatible.
ERROR: marvin-sqlalchemy-boolean-search 0.2.1 has requirement pyparsing>=2.4, but you'll have pyparsing 2.2.0 which is incompatible.
`

Begins to install collected packages, and uninstall existing installations, before giving the fatal error:

`ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
`

Any easy way to resolve this?

**Comment by havok2063** [comment]
@astrosteph Has this been resolved?  Have you tried updating to the latest version of Marvin?
