### ISSUE TITLE
Marvin-sdss-cube

### ISSUE THREAD

**Issue by marcduransala2000** [sdss/marvin#755]
Hi, this is my problem:

I have already installed "sdss-marvin"
And I have checked that it works with other packages, but in the specific library cube (marvin.tools.cube), it doesn't.

I've put this in the code:
from marvin.tools.cube import Cube
cube = Cube(plateifu='7958-9101')

and it says this error( attached in the message)
![issue](https://user-images.githubusercontent.com/95348918/144220471-a3eb0d2e-79e3-49b8-a2b6-227489014966.png)

Is there a problem in the server? How to solve it?

Thank you very much,

Marc

**Comment by havok2063** [comment]
Hi @marcduransala2000 which data release are you trying to access?  I've been doing some database maintenance and cleanup lately ahead of the final SDSS DR17.  The server may be intermittently down until Monday or so.  This particualar error you are having might be fixed though.  Can you try again?

**Comment by marcduransala2000** [comment]
I've tried to access into SDSS DR16,15 and 17 but it doesn't work this specific package:

from marvin.tools.cube import Cube
cube = Cube(plateifu='7958-9101')

But on the other hand for example, the maps package it works:

from marvin.tools.maps import Maps
maps = Maps(plateifu='7958-9101')

I don't know why. What I could do to solve this problem?

Thank you very much,

Marc

**Comment by marcduransala2000** [comment]
This is the error shown
![error4](https://user-images.githubusercontent.com/95348918/144758318-b6c9f0de-7a48-4195-97bb-3f87332f3628.png)

**Comment by havok2063** [comment]
@marcduransala2000 I've been performing database and website maintenance.  They have been down this week.  Everything should be back up by tomorrow afternoon.  I would try again then.

**Comment by marcduransala2000** [comment]
all good right now, thank you!
