### ISSUE TITLE
Error with Investigating Gas and Stellar Kinematics Exercise

### ISSUE THREAD

**Issue by TheRealEKL** [sdss/marvin#767]
Hello, when I download the Jupyter Notebook for the Marvin exercise "Investigating Gas and Stellar Kinematics", I receive this error: 
<img width="1078" alt="Screen Shot 2022-02-15 at 3 52 21 PM" src="https://user-images.githubusercontent.com/99765196/154147236-58430032-c1c7-418e-8297-7b6af58fba62.png">

I am using this exercise as a reference to learn how to multiply / divide maps to acquire a new map. Specifically, I am trying to learn how to do this in order to complete the "Computing Star-Formation Rates and SFR Densities using Marvin" exercise which has no solution. Thank you!

**Comment by astromariarosa** [comment]
I'm unsure if there are nuances I'm missing regarding the intention of those lines, but swapping the first two lines with `diff = havel - stvel` and then explicitly updating the ivar, mask, etc. as originally written works for me. 

For the Marvin team: if this is a valid approach, could this be updated in the Kinematics exercise?

**Comment by havok2063** [comment]
@TheRealEKL  Sorry the delay in seeing this.  This has been an outstanding issue with this notebook for a while but haven't had the time to look into it.  @astromariarosa If that solution works, and makes a working notebook, then yeah I think it's reasonable to update the notebook.  Would you mind submitting a PR with those changes?

**Comment by havok2063** [comment]
This is fixed in the latest 2.7.3 release of marvin.  The docs should now be updated.
