### ISSUE TITLE
"BrainError" when trying to load Maps file remotely: "No URL Map found. Cannot make remote call"

### ISSUE THREAD

**Issue by piper-maxwell** [sdss/marvin#769]
**Describe the bug**
Hello,

I am trying to load Maps file remotely using Marvin. I have been able to do this, using these same lines of code, many times in the past. However, recently it has been taking longer and longer to load the Maps files, and today I got a new "BrainError", saying I cannot make the remote call to the file. 

I am using Marvin version 2.7.2 and have set the data release to DR17. Any help is greatly appreciated! Let me know if I can provide any more information to help troubleshoot.

![Screen Shot 2022-03-15 at 7 34 40 PM](https://user-images.githubusercontent.com/101685221/158505951-13224b81-a0c9-4192-acd6-7261fe57100e.png)

**Comment by havok2063** [comment]
Hi @piper-maxwell , can you please try again?  Marvin was experiencing increased API usage which shutdown its web and other services.  We realized this today and are currently dealing with it.  Marvin should be back up and running now.  This may have been the cause of your issue.  Let us know.  

Also, roughly how many galaxies are you iterating over in your loop?  Does it crash at the same place each time in the loop?

**Comment by piper-maxwell** [comment]
Hi @havok2063,

Yes, this looks to be the cause of my issue - everything seems to be working again, thank you! 

Also, I was only iterating through ~120 galaxies, however the BrainError was called on the first iteration of the loop. Even after changing which galaxy was first in the loop, the BrainError was called. 

Thanks for the reply!
