### ISSUE TITLE
Unable to use marvin ID to access marvin on the web data

### ISSUE THREAD

**Issue by ledwar04** [sdss/marvin#773]
Unable to get information from Marvin on the Web, after typing the marvin ID into the search box. Also fails for plate-ID, also fails when using the 'roulette' feature and clicking on one of the images.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] (if the issue is related to Marvin Web)
 - Version of Marvin [e.g. 2.0.2]

**Additional context**

**Comment by havok2063** [comment]
Hi @ledwar04 can you provide an example galaxy you are trying to access, which data release, and marvin website?

**Comment by ledwar04** [comment]
Works now!
________________________________

**Comment by havok2063** [comment]
Great!
