### ISSUE TITLE
Error messages on jinja2, flask, json 

### ISSUE THREAD

**Issue by gmleeb** [sdss/marvin#793]
**Describe the bug**
I re-installed the macOS Monterey 12.6.2, and didn't installed any other software other than Xcode. 
After installed Xcode, I installed only 'numpy', 'astropy', and 'matplotlib'. 
The python3.9.6 I'm using is default python in my mac.

To install marvin, I just used "pip install sdss-marvin". 
Then, when I type "import marvin" in python3, the following error massages show up.
 
![Screen Shot 2023-01-20 at 5 25 03 PM](https://user-images.githubusercontent.com/123153816/213649836-d0e21cf3-4a48-4819-bd14-599aa176357b.png)

So, I opened the file '(/Users/gmlee/Library/Python/3.9/lib/python/site-packages/jinja2/__init__.py'
and changed the last line from "from .utils import select_autoescape as _select_autoescape_" to 
"from .utils import select_autoescape as _escape_"

after that, when I import marvin, the other error massages shows up as below.

![Screen Shot 2023-01-20 at 5 50 34 PM](https://user-images.githubusercontent.com/123153816/213654278-533a0097-cbc7-43c4-a462-5f819b2345ba.png)

This time, in "/Users/gmlee/Library/Python/3.9/lib/python/site-packages/flask/__init__.py" file, I just made the modules imported from 'jinja2' as a comments as below.

![Screen Shot 2023-01-20 at 5 58 24 PM](https://user-images.githubusercontent.com/123153816/213655744-c56c9bfd-b639-408b-926c-bbf0ca877a54.png)

But, it shows another error massages relating flask and json as below, and I couldn't do anything further, so I'm reporting this issue here. 

![Screen Shot 2023-01-20 at 5 46 56 PM](https://user-images.githubusercontent.com/123153816/213656339-84a02ae1-debe-42a1-be3f-3016fd5e42c6.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6.2

**Comment by havok2063** [comment]
@gmleeb I don't recommended editing the code of package dependencies within your python's `site-packages` folder, as that can lead to unintended dire consequences.  Instead you should upgrade or downgrade the packages as needed to resolve the issue.  You should be able to resolve this by either upgrading `flask>2.1` and `jinja2>3.1` or downgrading `jinja2<3.1` and/or `flask` to a lower version.  See #791.

**Comment by Dvorak365** [comment]
I've had the same problem. Upgrading flask and jinja2 has changed the error messages, but there are still incompatibility issues

Here are some screenshots of the different dependency incompatibilities I've been getting when upgrading different packages:
pip -U "flask-jwt-extended>=3.8,<3.9"
![image](https://github.com/sdss/marvin/assets/129003349/98c0aadd-6ebe-464d-aafc-80b7b4c47bf0)

pip -U "werkzeug<2.1,>=2.0"
![image](https://github.com/sdss/marvin/assets/129003349/b7e46d2b-2ab5-47c7-a682-cd1e45f6a88b)

pip -U "flask>2.1,<2.3"
pip -U "werkzeug<2.1,>=2.0"
![image](https://github.com/sdss/marvin/assets/129003349/dcf7095d-6c01-4899-b225-80d03277cab1)

What versions of these packages do I need to get marvin to run?
Thanks in advance

**Comment by havok2063** [comment]
@gmleeb @Dvorak365 I installed marvin fresh in a new Python 3.10 conda environment and these are the package versions needed to import marvin:

```
werkzeug=2.0.3
packaging=20.9
jinja2=3.0.3
itsdangerous=2.0.1
flask-jwt-extended=3.25.1
flask=1.1.2
```

**Comment by Dvorak365** [comment]
That's fixed it, thanks so much for your help!

**Comment by matteoalpe1993** [comment]
Hello, I followed exactly the procedure in this post. Below versions installed:
werkzeug=2.0.3
packaging=20.9
jinja2=3.0.3
itsdangerous=2.0.1
flask-jwt-extended=3.25.1
flask=1.1.2

However, it still create an issue and I cannot import marvin (pip installed version 2.8)

What am I doing wrong?

<img width="1029" alt="Image" src="https://github.com/user-attachments/assets/949ef118-7559-4c99-b68c-e77e179d1f5c" />

**Comment by havok2063** [comment]
@matteoalpe1993 can you please update to marvin 2.8.2 and try again?
