### ISSUE TITLE
packaging version > 22 breaks legacy version syntax

### ISSUE THREAD

**Issue by Jack3690** [sdss/marvin#794]
New error popped up after installing Marvin

InvalidVersion                            Traceback (most recent call last)
<ipython-input-29-bc4277317e3e> in <module>
     12 
     13   # Get SDSS Image
---> 14   optical=maps.getImage()
     15 
     16   # Crop Image to match IFU size

10 frames
/usr/local/lib/python3.8/dist-packages/marvin/tools/core.py in getImage(self)
    300         ''' Retrieves the Image :class:`~marvin.tools.image.Image` for this object '''
    301 
--> 302         image = marvin.tools.image.Image(plateifu=self.plateifu, release=self.release)
    303         return image

/usr/local/lib/python3.8/dist-packages/marvin/tools/image.py in __init__(self, input, filename, mangaid, plateifu, mode, data, release, download)
     75             raise MarvinError('Images cannot currently be accessed from the db')
     76         elif self.data_origin == 'api':
---> 77             self._load_image_from_api()
     78 
     79         # initialize attributes

/usr/local/lib/python3.8/dist-packages/marvin/tools/image.py in _load_image_from_api(self)
    170         ''' Load an image from a remote location '''
    171 
--> 172         filepath = self._getFullPath()
    173         response = requests.get(self.url)
    174         if not response.ok:

/usr/local/lib/python3.8/dist-packages/marvin/tools/image.py in _getFullPath(self)
    132 
    133         plate, ifu = self.plateifu.split('-')
--> 134         dir3d = self._get_image_dir()
    135 
    136         name = 'mangaimage'

/usr/local/lib/python3.8/dist-packages/marvin/tools/image.py in _get_image_dir(self)
    121 
    122         # get the appropriate image directory
--> 123         is_mastar = target_is_mastar(self.plateifu, drpver=self._drpver)
    124         image_dir = 'mastar' if is_mastar else 'stack'
    125         return image_dir

/usr/local/lib/python3.8/dist-packages/marvin/utils/general/general.py in target_is_mastar(plateifu, drpver, drpall)
   1729     '''
   1730 
-> 1731     row = get_drpall_row(plateifu, drpver=drpver, drpall=drpall)
   1732     return row['srvymode'] == 'APOGEE lead'
   1733 

/usr/local/lib/python3.8/dist-packages/marvin/utils/general/general.py in get_drpall_row(plateifu, drpver, drpall)
    987 
    988     # get the drpall table
--> 989     drpall_table = get_drpall_table(drpver=drpver, drpall=drpall, hdu='MANGA')
    990     in_table = plateifu in drpall_table['plateifu']
    991     # check the mastar extension

/usr/local/lib/python3.8/dist-packages/marvin/utils/general/general.py in get_drpall_table(drpver, drpall, hdu)
   1769 
   1770     # check for hdu
-> 1771     hduext = hdu if check_versions(drpver, 'v2_5_3') else 'MANGA'
   1772     if hdu not in drpTable[drpver]:
   1773         drpall = drpall if drpall else get_drpall_path(drpver=drpver)

/usr/local/lib/python3.8/dist-packages/marvin/utils/general/general.py in check_versions(version1, version2)
   1859     '''
   1860 
-> 1861     return parse(version1) >= parse(version2)
   1862 
   1863 

/usr/local/lib/python3.8/dist-packages/packaging/version.py in parse(version)
     50     # type: (str) -> Union[LegacyVersion, Version]
     51     """
---> 52     Parse the given version string and return either a :class:`Version` object
     53     or a :class:`LegacyVersion` object depending on if the given version is
     54     a valid PEP 440 version or a legacy version.

/usr/local/lib/python3.8/dist-packages/packaging/version.py in __init__(self, version)
    195 
    196 
--> 197 _legacy_version_component_re = re.compile(r"(\d+ | [a-z]+ | \.| -)", re.VERBOSE)
    198 
    199 _legacy_version_replacement_map = {

**InvalidVersion: Invalid version: 'v3_1_1'**

**Comment by Jack3690** [comment]
from marvin.tools.maps import Maps

plateifu = '8934-3701'
maps = Maps(plateifu=plateifu,mode='remote')
optical=maps.getImage()

**Comment by havok2063** [comment]
Hmm I can't reproduce the error with your code.  What version of `marvin` are you using?  And which data release are you trying to load?

**Comment by Jack3690** [comment]
I am using sdss-marvin 2.8.0. I am installing using pip.

I am trying to load DR17

**Comment by Jack3690** [comment]
I have checked the fix and it works. Thank you so much.
