### ISSUE TITLE
cannot import name 'safe_str_cmp' from 'werkzeug.security'

### ISSUE THREAD

**Issue by KuabNad** [sdss/marvin#798]
When importing 
from marvin.tools.image import Image
I got error:
cannot import name 'safe_str_cmp' from 'werkzeug.security'

The full output:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 17
     14 import random
     16 from photutils.aperture import Aperture
---> 17 from marvin.tools.image import Image
     18 from marvin.tools.maps import Maps

File ~/anaconda3/envs/marvin/lib/python3.8/site-packages/marvin/__init__.py:792
    789     marvindir = moduledir.rsplit('/', 2)[0]
    790     os.environ['MARVIN_DIR'] = marvindir
--> 792 from marvin.api.api import Interaction
    793 from marvin.api.base import arg_validate
    795 # Provide access to base submodules from the marvin namespace

File ~/anaconda3/envs/marvin/lib/python3.8/site-packages/marvin/api/__init__.py:10
      8 from brain.utils.general import build_routemap
      9 from flask import current_app
---> 10 from flask_jwt_extended import fresh_jwt_required
     11 from webargs import ValidationError, fields, validate
     12 from webargs.flaskparser import parser, use_args, use_kwargs

File ~/anaconda3/envs/marvin/lib/python3.8/site-packages/flask_jwt_extended/__init__.py:1
----> 1 from .jwt_manager import JWTManager
      2 from .utils import (
      3     create_access_token, create_refresh_token, current_user, decode_token,
      4     get_csrf_token, get_current_user, get_jti, get_jwt_claims, get_jwt_identity,
   (...)
      7     get_raw_jwt_header
      8 )
      9 from .view_decorators import (
     10     fresh_jwt_required, jwt_optional, jwt_refresh_token_required, jwt_required,
     11     verify_fresh_jwt_in_request, verify_jwt_in_request,
     12     verify_jwt_in_request_optional, verify_jwt_refresh_token_in_request
     13 )

File ~/anaconda3/envs/marvin/lib/python3.8/site-packages/flask_jwt_extended/jwt_manager.py:28
     15 from flask_jwt_extended.exceptions import (
     16     JWTDecodeError, NoAuthorizationError, InvalidHeaderError, WrongTokenError,
     17     RevokedTokenError, FreshTokenRequired, CSRFError, UserLoadError,
     18     UserClaimsVerificationError
     19 )
     20 from flask_jwt_extended.default_callbacks import (
     21     default_expired_token_callback, default_user_claims_callback,
     22     default_user_identity_callback, default_invalid_token_callback,
   (...)
     26     default_decode_key_callback, default_encode_key_callback,
     27     default_jwt_headers_callback)
---> 28 from flask_jwt_extended.tokens import (
     29     encode_refresh_token, encode_access_token
     30 )
     31 from flask_jwt_extended.utils import get_jwt_identity
     34 class JWTManager(object):

File ~/anaconda3/envs/marvin/lib/python3.8/site-packages/flask_jwt_extended/tokens.py:6
      3 from calendar import timegm
      5 import jwt
----> 6 from werkzeug.security import safe_str_cmp
      8 from flask_jwt_extended.exceptions import JWTDecodeError, CSRFError
     11 def _create_csrf_token():

ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/anaconda3/envs/marvin/lib/python3.8/site-packages/werkzeug/security.py)

**Comment by havok2063** [comment]
@KuabNad can you check what version of `werkzeug`, `jinja2` is installed?  there are some issues around a few package dependencies that may be related.  See https://github.com/sdss/marvin/issues/791

**Comment by KuabNad** [comment]
Thanks, 
Indeed, issue #791 is the same.
