### ISSUE TITLE
Marvin fails to download cube

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#81]
When I try to download a cube I get

```
In [5]: cc = Cube(plateifu='9002-12701', mode='remote')

In [6]: cc
Out[6]: <Marvin Cube (plateifu='9002-12701', mode='remote', data_origin='api')>

In [7]: cc.download()
user [sdss]:
password:
SDSS_ACCESS> syncing... please wait
SDSS_ACCESS> Done!
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-165ccee54e8d> in <module>()
----> 1 cc.download()

/Users/albireo/Documents/Repo/manga/marvin/python/marvin/tools/cube.pyc in download(self)
    112
    113         return super(Cube, self).download('mangacube', ifu=ifu,
--> 114                                           drpver=self._drpver, plate=plate)
    115
    116     def __repr__(self):

/Users/albireo/Documents/Repo/manga/marvin/python/marvin/core/core.pyc in download(self, pathType, **pathParams)
    173             rsync_access.commit()
    174             paths = rsync_access.get_paths()
--> 175             self.filename = paths[0]  # doing this for single files, may need to change
    176
    177     def _getFullPath(self, pathType=None, url=None, **pathParams):

TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by albireox** [comment]
More on this. If I unset my `SAS_BASE_DIR`, I get this message before SDSS_ACCESS starts syncing

`There is no file with filetype='mangacube' to access in the tree module loaded`

**Comment by havok2063** [comment]
Are you testing using sdss_access in a clean non-module environment?  Or is this error generated when using it the other module+svn directory way?

**Comment by albireox** [comment]
AFAIK I'm using a completely clear environment with only the extern modules. I have disabled all my modules, and marvin does not load anything. The tree and sdss_access in extern seem up to date.

**Comment by havok2063** [comment]
Hmm.. Can you recreate the rsync steps in iPython in that environment, and instead of committing to download, print what get_paths() is?

**Comment by albireox** [comment]
`get_path()` returns `None`. The values that `download` receives seem ok. `pathType=mangacube`, and `pathParams={'ifu': '12701', 'drpver': 'v2_0_1', 'plate': '9002'}`

**Comment by havok2063** [comment]
Well I tried the same thing in a terminal after module unloading tree and sdss_access.  Everything worked for me, however the cube is nowhere to be found.  The path was created but is empty, and the sdss_access logs show no errors.  You have this in your command
```
In [7]: cc.download()
user [sdss]:
password:
```
and I don't.  Do you the sdss_access in your .netrc file?  sdss_access is supposed to raise an AccessError if you don't.

**Comment by havok2063** [comment]
Nevermind.  It suddenly showed up!

**Comment by albireox** [comment]
My `.netrc` contains

```
machine api.sdss.org
   login sdss
   password <the password™>
```

I still get asked for the password, though.

**Comment by havok2063** [comment]
That's for the API.  sdss_access is different. You need a new entry of exactly the same thing but change the machine name to data.sdss.org

**Comment by albireox** [comment]
Added data.sdss.org but still having the same problem. Could it be something related with the SAS_URL Marvin thinks it should be using. I don't have any `$SAS_URL` set, but it's weird that it's asking me for the password if it's in the `.netrc`

**Comment by havok2063** [comment]
You shouldn't be getting that user/pass notification if it's in your .netrc.  That is weird.  I don't think you need a $SAS_URL envvar set.  sdss_access does not use that.

**Comment by albireox** [comment]
Ok. As long as it works for both of you and in a clean environment I think it's not worth spending a lot of time in this. It's probably something weird with my system.

**Comment by havok2063** [comment]
You did have that general rsync problem.

**Comment by albireox** [comment]
Yep, it may be related.

**Comment by havok2063** [comment]
Can you dig in the traceback and find the root error?

**Comment by albireox** [comment]
I'll see if I can figure out what sdss_access is doing there. I uninstalled my custom rsync and I'm using the default one with OSX.

**Comment by joelbrownstein** [comment]
I am using a non-default rsync

$ rsync --version
rsync  version 3.1.2  protocol version 31

which is a late-version from macports

On Nov 4, 2016, at 2:41 PM, José Sánchez-Gallego <notifications@github.com<mailto:notifications@github.com>> wrote:


I'll see if I can figure out what sdss_access is doing there. I uninstalled my custom rsync and I'm using the default one with OSX.

**Comment by albireox** [comment]
My non-default version is also v3.1.2, installed with homebrew. It seems to do the same whether I use the default Mac one or the homebrew one.

**Comment by joelbrownstein** [comment]
So its probably not the version.  Do you want to work it out yourself, or show it to me via screen-share?

**Comment by albireox** [comment]
Sure. I can show you my screen. What Adobe Connect room do you want to use?

**Comment by albireox** [comment]
This is now fixed after a fair amount of debugging with Joel. The problem was that my `$MANGA_SPECTRO_REDUX` environment variable contained a double slash in the path and that was messing with a regex. It's fixed in sdss_access in the SVN repo and in the GitHub version, and updated in extern in Marvin.

On a related note, my `.netrc` was being ignored because I had not set it to chmod 600. We should remember to include that in the documentation if it's not already there.
