### ISSUE TITLE
Failure to retrieve a Maps file given MaNGAID

### ISSUE THREAD

**Issue by CalebRichardson2001** [sdss/marvin#813]
**Describe the bug**
Received an error message that Marvin was unable to retrieve the Maps file for given input parameters, with those input parameters being MaNGAIDs

**To Reproduce**
This occured midway through a loop retrieving the HDU files for all unique MaNGAIDs, which are in a list generated by using the method recommended by the SDSS website and the drpall-v3_1_1 file. I don't know if this just affects certain MaNGAIDs, or which MaNGAID caused this unforunately

**Expected behaviour**
I expect Marvin to not throw this error

**Desktop (please complete the following information):**
 - Current version of Marvin, on SciServer

**Additional context**
0;31m---------------------------------------------------------------------------[0m
[0;31mMarvinError[0m                               Traceback (most recent call last)
[0;32m/tmp/ipykernel_13/2463262468.py[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0mhdu_list[0m [0;34m=[0m [0;34m[[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;32mfor[0m [0mval[0m [0;32min[0m [0muniq_vals[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m     [0mdata1[0m [0;34m=[0m [0mMaps[0m[0;34m([0m[0mval[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m     [0mhdu_list[0m[0;34m.[0m[0mappend[0m[0;34m([0m[0mfits[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mdata1[0m[0;34m.[0m[0mfilename[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m     [0mcounter1[0m [0;34m+[0m [0;36m1[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniconda3/envs/py38/lib/python3.8/site-packages/marvin/tools/maps.py[0m in [0;36m__init__[0;34m(self, input, filename, mangaid, plateifu, mode, data, release, drpall, download, nsa_source, bintype, template, template_kin)[0m
[1;32m     95[0m         [0mself[0m[0;34m.[0m[0m_bitmasks[0m [0;34m=[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m
[1;32m     96[0m [0;34m[0m[0m
[0;32m---> 97[0;31m         MarvinToolsClass.__init__(self, input=input, filename=filename,
[0m[1;32m     98[0m                                   [0mmangaid[0m[0;34m=[0m[0mmangaid[0m[0;34m,[0m [0mplateifu[0m[0;34m=[0m[0mplateifu[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m     99[0m                                   [0mmode[0m[0;34m=[0m[0mmode[0m[0;34m,[0m [0mdata[0m[0;34m=[0m[0mdata[0m[0;34m,[0m [0mrelease[0m[0;34m=[0m[0mrelease[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniconda3/envs/py38/lib/python3.8/site-packages/marvin/tools/core.py[0m in [0;36m__init__[0;34m(self, input, filename, mangaid, plateifu, mode, data, release, drpall, download)[0m
[1;32m    114[0m                  mode=None, data=None, release=None, drpall=None, download=None):
[1;32m    115[0m [0;34m[0m[0m
[0;32m--> 116[0;31m         MMAMixIn.__init__(self, input=input, filename=filename, mangaid=mangaid,
[0m[1;32m    117[0m                           [0mplateifu[0m[0;34m=[0m[0mplateifu[0m[0;34m,[0m [0mmode[0m[0;34m=[0m[0mmode[0m[0;34m,[0m [0mdata[0m[0;34m=[0m[0mdata[0m[0;34m,[0m [0mrelease[0m[0;34m=[0m[0mrelease[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    118[0m                           download=download)

[0;32m~/miniconda3/envs/py38/lib/python3.8/site-packages/marvin/tools/mixins/mma.py[0m in [0;36m__init__[0;34m(self, input, filename, mangaid, plateifu, mode, data, release, drpall, download, ignore_db)[0m
[1;32m    125[0m [0;34m[0m[0m
[1;32m    126[0m         [0;32mif[0m [0mself[0m[0;34m.[0m[0mmode[0m [0;34m==[0m [0;34m'local'[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 127[0;31m             [0mself[0m[0;34m.[0m[0m_doLocal[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    128[0m         [0;32melif[0m [0mself[0m[0;34m.[0m[0mmode[0m [0;34m==[0m [0;34m'remote'[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    129[0m             [0mself[0m[0;34m.[0m[0m_doRemote[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniconda3/envs/py38/lib/python3.8/site-packages/marvin/tools/mixins/mma.py[0m in [0;36m_doLocal[0;34m(self)[0m
[1;32m    289[0m                         [0mself[0m[0;34m.[0m[0mdata_origin[0m [0;34m=[0m [0;34m'file'[0m[0;34m[0m[0;34m[0m[0m
[1;32m    290[0m                     [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 291[0;31m                         raise MarvinError('failed to retrieve data using '
[0m[1;32m    292[0m                                           'input parameters.')
[1;32m    293[0m [0;34m[0m[0m

[0;31mMarvinError[0m: failed to retrieve data using input parameters.
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.
MarvinError: failed to retrieve data using input parameters.
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.

**Comment by havok2063** [comment]
@CalebRichardson2001  Are you trying to download the files?  If you're on SciServer then all the files are already local.  You can either access the files directly or through Marvin Maps.  This may have been a temporary issue with SciServer?  Do you have a better traceback than this?  I can't easily read that.

**Comment by CalebRichardson2001** [comment]
> @CalebRichardson2001 Are you trying to download the files? If you're on SciServer then all the files are already local. You can either access the files directly or through Marvin Maps. This may have been a temporary issue with SciServer? Do you have a better traceback than this? I can't easily read that.

Unfortunately no - SciServer does not give fantastic tracebacks when you're running a job

I'm trying to use Marvin (in local mode, with "database" manually turned off) in order to find the MAPS file name associated with a given MaNGAID.

**Comment by CalebRichardson2001** [comment]
I reran the job and it failed at the same point. My gut says it may be that Marvin is struggling with a specific galaxy (potentially multiple galaxies that appear later in the list)

**Comment by havok2063** [comment]
can you record which mangaid it fails at, or the iteration in your loop?  If you know the plate-ifu, you can manually check for the file existence in SciServer.

**Comment by CalebRichardson2001** [comment]
> can you record which mangaid it fails at, or the iteration in your loop? If you know the plate-ifu, you can manually check for the file existence in SciServer.

It fails at mandaid 1-210966. Since I ran it straight from the notebook and not through Jobs, I was also able to get a picture of the traceback
<img width="887" alt="image" src="https://github.com/sdss/marvin/assets/166037873/32918a49-d1ee-469d-861f-78bb056a72fe">

**Comment by CalebRichardson2001** [comment]
Having now iterated through the entire list, starting the loop up again at the next galaxy when one failed. The following all cause the failure: 1-210966, 1-249929, 1-312844, 1-456385, 1-634800, 1-80510, 54-35. 

It was suggested to me that it's possible that these are seven galaxies where the velocity pipeline failed (thus no MAPS file) but spectra was able to be generated, so they WERE in the DRPall file I used to generate the list of available galaxies. I'm going to go poke some DAP files and see what what the value of DAPQUAL is for them

**Comment by CalebRichardson2001** [comment]
Yep, all of them lacked MAPS files. Problem solved, it wasn't Marvin's fault

**Comment by havok2063** [comment]
Yes not all plate-ifus in the drpall file made it through the DAP.  Some made it through different DAP daptype stages, so the number maps files for SPX binning isn't necessarily the same as the HYB10 binning scheme, which is the default bintype that Marvin uses.  To see which cubes made it through the DAP, you can check the dapall file.  Look at the daptype extension you're interested in, then check the `DAPDONE` column.  That will tell you if that cube made it through that stage of the DAP.
