### ISSUE TITLE
Python does not start in Python 3

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#85]
```
[env] AlbireoProˇalbireo: ~ » py3                                                            ~
Python 3.5.2 (default, Oct 11 2016, 09:02:00)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import marvin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/albireo/Documents/Repo/manga/marvin/python/marvin/__init__.py", line 380, in <module>
    config = MarvinConfig()
  File "/Users/albireo/Documents/Repo/manga/marvin/python/marvin/__init__.py", line 67, in __init__
    self._checkConfig()
  File "/Users/albireo/Documents/Repo/manga/marvin/python/marvin/__init__.py", line 229, in _checkConfig
    topkey = self._mpldict.keys()[0]
TypeError: 'odict_keys' object does not support indexing
```

**Comment by albireox** [comment]
Had a quick look at this and the problem is direr than expected. A few things we need to correct in the code:

- dictionary keys in PY3 are not lists so they cannot be indexed. The problem for the error above would be to do `topkey = list(self._mpldict.keys())[0]`. This is likely to happen in many places.
- Even with the relative import from future, imports are still a problem in several places. In particular, the way in which I handled the imports in `maps.py` seems to make PY3 unhappy.
- `marvin_pickle.py` needs to use pickle instead of cPickle for PY3. pickle is different in Python 3 so we'll need to add some tests to make sure it actually works.

We need to discuss how/when we are going to adapt the code to PY3 and how are we going to test any new code to make sure it's working with both versions.

**Comment by bretthandrews** [comment]
Agreed that this seems like it might be a larger task. And I definitely
would like some tests to automatically check.

**Comment by havok2063** [comment]
Kyle agreed to work on getting it working in Python 3.  Installation and import.  We'll have to write the tests on the things we have.  Here is a nice resource on differences. 

http://python-future.org/compatible_idioms.html

**Comment by bretthandrews** [comment]
There are some shebang lines (`#!/usr/bin/env python`) that specify` python2` or` python2.7`, which should be just `python`.
