### ISSUE TITLE
Deployment at Utah requires automatisation

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#88]
Currently it requires a fair amount of time and manual tinkering to deploy a new version at Utah. From @havok2063 notes, these are the necessary steps

```
When ready...

0. Ensure the setup.py has the correct version
1. Create a new PyPi package using twine
 a. in master, python setup.py sdist bdist_wheel
 b. twine register dist/project_name-x.y.z.tar.gz
 c. twine register dist/mypkg-0.1-py2.py3-none-any.whl
 d. remove old version dist/ builds if exist 
 e. twine upload dist/*
 
2. Create a new Github Release (using releases/Draft New Release)
3. Get the new Zenodo DOI and Bibtex entry for the new release
4. Update the README.md and Citation.rst with new software links, bibtex entry, and DOI badge

Go to Utah on sas-vm as manga user. 
 - Git dirpath is /home/manga/software/git/manga/marvin
 - Git modulefile path is /home/manga/software/git/modulefiles
5. git clone sdss/marvin into a new directory with tag name
6. git checkout the new tag
7. git submodule init and update
8. create a new marvin modulefile for new version
 a. update default version in .version
9. create a new wrapmarvin modulefile
10. module unload wrapmarvin
11. module load wrapmarvin/mangawork/marvin_[newversion]
12. go to /etc/nginx
13. change paths to marvin2/static and marvin2/lib inside conf.d/default.conf
14. restart nginx with nginx restart (or stop/start)
15. restart marvin with stopmarvin + startmarvin
16. go back to marvin/master directory and git pull
17. remake the sphinx master documentation with make html

18. sigh...
```

(emphasis on 18). For Utah, most steps are relatively simple to script, with maybe the exception of 13. We should also think about how to deal with Zenodo. Do we really need to manually update the DOI every time we tag a minor version? Maybe it's enough to do it every time we release a major one.

**Comment by joelbrownstein** [comment]
Step 13-14 is not a good way to do this.

I suggest NOT editing conf.d/default.conf at all, but instead have those paths point to a symlink which can be adjusted for the new tag, which would then work without requiring step 14 to restart nginx

**Comment by albireox** [comment]
I like that. I think it's easy and safe to do and script.

**Comment by albireox** [comment]
I've added a symlink `current` in `$MARVIN_DIR` so from now on it's not necessary to change the nginx configuration, just update the symlink to the latest version.

I have also tried to add some code in the `conf.py` in the Sphinx documentation to grab the version from `marvin.__version__` but it fails at Utah because we don't install Marvin as a distribution. WE probably can grab it from the `setup.py` instead, although the code will be a bit uglier.

**Comment by havok2063** [comment]
This has now been automated using the Python invoke package to deliver shell tasks.  See ```tasks.py``` in the main directory.  From inside the master directory, type ```invoke --list``` to see the list of commands.  To set things up at Utah, just run ```invoke setup_utah``` and it should do steps 5-15.  It will do everything up to stopping and starting the marvin apps.  Step 1 is also a new task with ```invoke deploy```.
