### ISSUE TITLE
marvin log needs a method to change the console log level

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#91]
After initializing the log, there is no way to modify the console log level.  This will be useful when turning on verbosity for debug print statements. 

```
import logging
from marvin import log
log.debug('debug statement') # does not print to console
log.error('error') # prints to console
ERROR: error
log.info('this is an info statement') #prints to console (this is the default console log level)
INFO: this is an info statement

# setLevel does not change the console logging level
log.setLevel(logging.DEBUG)
log.debug('new debug')
```

**Comment by joelbrownstein** [comment]
You have to remove the existing handler, and then add a new one configured as you want:
` for handler in log.handlers: log.removeHandler(handler)`
`logger.addHandler(newhandler)`

**Comment by albireox** [comment]
You can also do

```
import logging
from marvin import log
log.debug('debug statement') # does not print to console
log.error('error') # prints to console
log.info('this is an info statement') #prints to console (this is the default console log level)

# setLevel does not change the console logging level
log.sh.setLevel(logging.DEBUG)
log.debug('new debug')
```

[note the `log.sh.setLevel`] That will change the level of the shell logger, but not touch the file streamer. Would that work? I could add a `BrainLogger.setLevel` to change both `log.sh` and `log.fh` at the same time, but that would defeat the purpose of having loggers with different levels.

**Comment by havok2063** [comment]
I think this would be fine.  I'm only interested in changing the console loglevel, for cases on turning on and off debug print statements throughout marvin globally.

**Comment by albireox** [comment]
Sounds good. Closing this.
