### ISSUE TITLE
safari browser does not play well with marvin

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#93]
The Safari web browser does not work well for Marvin.  Until a multi-browser testing suite can be implemented, it is recommended to use Chrome or Firefox.   Alternative is to upgrade Safari to latest Technology Preview version.

**Comment by albireox** [comment]
We implemented a banner some time ago letting people know of this problem. Also, newer versions of Safari are becoming more HTML5 compliant, so this should get better over time.
