### ISSUE TITLE
sqlalchemy-boolean-search not found when installed from pip source

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#97]
One student at the Shanghai meeting was able to install Marvin using pip (it downloaded the source, not the wheel), but it failed when importing marvin because it could not find sqlalchemy-boolean-search. This seems to indicate that the externs are not being installed or that marvin cannot import it from extern. If one manually installs sqlalchemy-boolean-search, the same error happens with wtforms-alchemy.

I have tried to reproduce this error by download the source from PyPI (`sdss-marvin-2.0.5.tar.gz`) and installing it with `python setup.py install` but the version installed in site-packages seems to work fine.

**Comment by aileisun** [comment]
I tried installing marvin from github
` pip install git+git://github.com/sdss/marvin.git`
It's successfully installed 

> Successfully installed sdss-marvin-2.0.9

But it cannot be imported. 
`import marvin`

> 
> /Users/aisun/anaconda2/lib/python2.7/site-packages/marvin/extern/__init__.py in <module>()
>      28 # sdss_access = _import_module('sdss_access', 'sdss_access/python/')
>      29 sqlalchemy_boolean_search = _import_module(
> ---> 30     'sqlalchemy_boolean_search', 'sqlalchemy-boolean-search/')
>      31 wtforms_alchemy = _import_module('wtforms_alchemy', 'wtforms-alchemy/')
>      32 brain = _import_module('brain', 'marvin_brain/python')
> 
> /Users/aisun/anaconda2/lib/python2.7/site-packages/marvin/extern/__init__.py in _import_module(name, relpath)
>      17     try:
>      18         path = os.path.join(os.path.dirname(__file__), relpath)
> ---> 19         fp, filename, description = imp.find_module(name, [path])
>      20         return imp.load_module(name, fp, filename, description)
>      21     except IOError:
> 
> ImportError: No module named sqlalchemy_boolean_search
> 
>

**Comment by bretthandrews** [comment]
It looks like pip doesn't install submodules:
```
(env) (python2) extern: pwd
/Users/andrews/hacks/marvin2017-01-04/env/lib/python2.7/site-packages/marvin/extern
(env) (python2) extern: ls
__init__.py  __init__.pyc
```

This [link](https://stackoverflow.com/questions/12593354/how-to-develop-multiple-pip-packages-in-a-git-project) seems to suggest that we could add them to the requirements file ala
`git+git://github.com/sdss/sqlalchemy-boolean-search/tree/89c8980e2987234101ce8d34e55bab1c2af47d8c`

**Comment by albireox** [comment]
I think the problem with doing `pip install git+git://github.com/sdss/marvin.git` is that the repo gets cloned but the submodules (including sqlalchemy-boolean-search) don't get initiated, so marvin fails on import because it cannot find them.

In principle, we should discourage using both git and pip at the same time: either the normal `pip install` works or the user should clone the repo and initiate the submodules, as the documentation indicates.

@aileisun, could you try again removing all your marvin installations and simply doing `pip install sdss-marvin`? If that fails, or you cannot import marvin, can you post the error message here? I think that's the problem we should try to fix, and not the one derived from using `pip install git+git`.

**Comment by havok2063** [comment]
I think we can close this.  The recommended way of installing marvin is `pip install sdss-marvin`.
