### ISSUE TITLE
Problem import Cube with a given Manga-id

### ISSUE THREAD

**Issue by francbelf** [sdss/marvin#98]
This galaxy has mangaid=1-301579 and plateifu=8462-1902. I can successfully run this

cube = Cube(plateifu='8462-1902')

but this line breaks

cube = Cube(mangaid='1-301579')

and gives this error

MarvinError                               Traceback (most recent call last)
<ipython-input-50-2f6088d13d2a> in <module>()
      5 from marvin.tools.cube import Cube
      6 #cube = Cube(plateifu='8462-1902')
----> 7 cube = Cube(mangaid='1-301579')

/Applications/anaconda/lib/python2.7/site-packages/marvin/tools/cube.pyc in __init__(self, *args, **kwargs)
     74         self._drpall_data = None
     75 
---> 76         super(Cube, self).__init__(*args, **kwargs)
     77 
     78         if self.data_origin == 'file':

/Applications/anaconda/lib/python2.7/site-packages/marvin/core/core.pyc in __init__(self, *args, **kwargs)
     97             self.plateifu = mangaid2plateifu(self.mangaid,
     98                                              drpall=self._drpall,
---> 99                                              drpver=self._drpver)
    100 
    101         if self.mode == 'local':

/Applications/anaconda/lib/python2.7/site-packages/marvin/utils/general/general.pyc in mangaid2plateifu(mangaid, mode, drpall, drpver)
    359         raise MarvinError(
    360             'mangaid2plateifu was not able to find a plate-ifu for '
--> 361             'mangaid={0} either local or remotely.'.format(mangaid))
    362 
    363 

MarvinError: mangaid2plateifu was not able to find a plate-ifu for mangaid=1-301579 either local or remotely.

**Comment by albireox** [comment]
This was a problem with the API call for mangaid2plateifu not accepting POST requests. A stupid mistake and two releases later it seems fixed.
