### ISSUE TITLE
Beautifying Tools Spectum plotting

### ISSUE THREAD

**Issue by francbelf** [sdss/marvin#99]
ax.plot(model_spectrum.wavelength, model_spectrum.flux, 'r')

gives zeroes for regions not fitted by the DAP. I think this is confusing. It would be better to directly display the mask information by shading/otherwise highlighting the regions not fitted. 

Also it would be good to change the default yrange of the plot to get rid of the negative flux levels.

![image](https://cloud.githubusercontent.com/assets/20231691/20416351/68d99d66-ad79-11e6-9aa4-9066914c1dbf.png)

**Comment by bretthandrews** [comment]
In 2.1, the default minimum y value will be 0 for spectrum plotting.

**Comment by albireox** [comment]
Related to #171.

**Comment by havok2063** [comment]
This seems somewhat fixed.  Closing. Can reassess post 2.2 release.
